//
// add_seq_5.c - Hardcoded addition sequences for 5-bit width
//
// Generated by scripts/generate_seq_all.py - DO NOT EDIT MANUALLY
//
// Contains: QQ_add, cQQ_add (static const), CQ_add, cCQ_add (template-init)
//

#include "sequences.h"

#ifdef SEQ_WIDTH_5

#include <stdlib.h>

// SEQ_PI as compile-time constant for static initializers
// (math.h M_PI is not a constant expression in standard C)
#ifndef SEQ_PI
#define SEQ_PI 3.14159265358979323846
#endif

// ============================================================================
// QQ_ADD WIDTH 5 (35 layers)
// Qubit layout: [0,4] = target, [5,9] = control
// ============================================================================

static const gate_t QQ_ADD_5_L0[] = {{.Gate = H,
                                      .Target = 4,
                                      .NumControls = 0,
                                      .Control = {0},
                                      .large_control = NULL,
                                      .GateValue = 0,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L1[] = {{.Gate = P,
                                      .Target = 4,
                                      .NumControls = 1,
                                      .Control = {3},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 2,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L2[] = {{.Gate = P,
                                      .Target = 4,
                                      .NumControls = 1,
                                      .Control = {2},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 4,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L3[] = {{.Gate = P,
                                      .Target = 4,
                                      .NumControls = 1,
                                      .Control = {1},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 8,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L4[] = {{.Gate = P,
                                      .Target = 4,
                                      .NumControls = 1,
                                      .Control = {0},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 16,
                                      .NumBasisGates = 0},
                                     {.Gate = H,
                                      .Target = 3,
                                      .NumControls = 0,
                                      .Control = {0},
                                      .large_control = NULL,
                                      .GateValue = 0,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L5[] = {{.Gate = P,
                                      .Target = 3,
                                      .NumControls = 1,
                                      .Control = {2},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 2,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L6[] = {{.Gate = P,
                                      .Target = 3,
                                      .NumControls = 1,
                                      .Control = {1},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 4,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L7[] = {{.Gate = P,
                                      .Target = 3,
                                      .NumControls = 1,
                                      .Control = {0},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 8,
                                      .NumBasisGates = 0},
                                     {.Gate = H,
                                      .Target = 2,
                                      .NumControls = 0,
                                      .Control = {0},
                                      .large_control = NULL,
                                      .GateValue = 0,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L8[] = {{.Gate = P,
                                      .Target = 2,
                                      .NumControls = 1,
                                      .Control = {1},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 2,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L9[] = {{.Gate = P,
                                      .Target = 2,
                                      .NumControls = 1,
                                      .Control = {0},
                                      .large_control = NULL,
                                      .GateValue = SEQ_PI / 4,
                                      .NumBasisGates = 0},
                                     {.Gate = H,
                                      .Target = 1,
                                      .NumControls = 0,
                                      .Control = {0},
                                      .large_control = NULL,
                                      .GateValue = 0,
                                      .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L10[] = {{.Gate = P,
                                       .Target = 1,
                                       .NumControls = 1,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L11[] = {{.Gate = H,
                                       .Target = 0,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L12[] = {{.Gate = P,
                                       .Target = 0,
                                       .NumControls = 1,
                                       .Control = {5},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L13[] = {{.Gate = P,
                                       .Target = 1,
                                       .NumControls = 1,
                                       .Control = {5},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L14[] = {{.Gate = P,
                                       .Target = 2,
                                       .NumControls = 1,
                                       .Control = {5},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 4,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L15[] = {{.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {5},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 8,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L16[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {5},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 16,
                                       .NumBasisGates = 0},
                                      {.Gate = P,
                                       .Target = 1,
                                       .NumControls = 1,
                                       .Control = {6},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L17[] = {{.Gate = P,
                                       .Target = 2,
                                       .NumControls = 1,
                                       .Control = {6},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L18[] = {{.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {6},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 4,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L19[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {6},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 8,
                                       .NumBasisGates = 0},
                                      {.Gate = P,
                                       .Target = 2,
                                       .NumControls = 1,
                                       .Control = {7},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L20[] = {{.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {7},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L21[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {7},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 4,
                                       .NumBasisGates = 0},
                                      {.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {8},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L22[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {8},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L23[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {9},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI,
                                       .NumBasisGates = 0},
                                      {.Gate = H,
                                       .Target = 0,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L24[] = {{.Gate = P,
                                       .Target = 1,
                                       .NumControls = 1,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L25[] = {{.Gate = H,
                                       .Target = 1,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0},
                                      {.Gate = P,
                                       .Target = 2,
                                       .NumControls = 1,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 4,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L26[] = {{.Gate = P,
                                       .Target = 2,
                                       .NumControls = 1,
                                       .Control = {1},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L27[] = {{.Gate = H,
                                       .Target = 2,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0},
                                      {.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 8,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L28[] = {{.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {1},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 4,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L29[] = {{.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {2},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L30[] = {{.Gate = H,
                                       .Target = 3,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0},
                                      {.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 16,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L31[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {1},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 8,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L32[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {2},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 4,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L33[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {3},
                                       .large_control = NULL,
                                       .GateValue = -SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t QQ_ADD_5_L34[] = {{.Gate = H,
                                       .Target = 4,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0}};

static const gate_t *QQ_ADD_5_LAYERS[] = {
    QQ_ADD_5_L0,  QQ_ADD_5_L1,  QQ_ADD_5_L2,  QQ_ADD_5_L3,  QQ_ADD_5_L4,  QQ_ADD_5_L5,
    QQ_ADD_5_L6,  QQ_ADD_5_L7,  QQ_ADD_5_L8,  QQ_ADD_5_L9,  QQ_ADD_5_L10, QQ_ADD_5_L11,
    QQ_ADD_5_L12, QQ_ADD_5_L13, QQ_ADD_5_L14, QQ_ADD_5_L15, QQ_ADD_5_L16, QQ_ADD_5_L17,
    QQ_ADD_5_L18, QQ_ADD_5_L19, QQ_ADD_5_L20, QQ_ADD_5_L21, QQ_ADD_5_L22, QQ_ADD_5_L23,
    QQ_ADD_5_L24, QQ_ADD_5_L25, QQ_ADD_5_L26, QQ_ADD_5_L27, QQ_ADD_5_L28, QQ_ADD_5_L29,
    QQ_ADD_5_L30, QQ_ADD_5_L31, QQ_ADD_5_L32, QQ_ADD_5_L33, QQ_ADD_5_L34};
static const num_t QQ_ADD_5_GPL[] = {1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
                                     1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1};

static const sequence_t HARDCODED_QQ_ADD_5 = {.seq = (gate_t **)QQ_ADD_5_LAYERS,
                                              .num_layer = 35,
                                              .used_layer = 35,
                                              .gates_per_layer = (num_t *)QQ_ADD_5_GPL};

// ============================================================================
// cQQ_ADD WIDTH 5 (57 layers)
// Qubit layout: [0,4] = target, [5,9] = b, [10] = control
// ============================================================================

static const gate_t cQQ_ADD_5_L0[] = {{.Gate = H,
                                       .Target = 4,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L1[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {3},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L2[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {2},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 4,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L3[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {1},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 8,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L4[] = {{.Gate = P,
                                       .Target = 4,
                                       .NumControls = 1,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 16,
                                       .NumBasisGates = 0},
                                      {.Gate = H,
                                       .Target = 3,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L5[] = {{.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {2},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L6[] = {{.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {1},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 4,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L7[] = {{.Gate = P,
                                       .Target = 3,
                                       .NumControls = 1,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 8,
                                       .NumBasisGates = 0},
                                      {.Gate = H,
                                       .Target = 2,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L8[] = {{.Gate = P,
                                       .Target = 2,
                                       .NumControls = 1,
                                       .Control = {1},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 2,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L9[] = {{.Gate = P,
                                       .Target = 2,
                                       .NumControls = 1,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = SEQ_PI / 4,
                                       .NumBasisGates = 0},
                                      {.Gate = H,
                                       .Target = 1,
                                       .NumControls = 0,
                                       .Control = {0},
                                       .large_control = NULL,
                                       .GateValue = 0,
                                       .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L10[] = {{.Gate = P,
                                        .Target = 1,
                                        .NumControls = 1,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L11[] = {{.Gate = H,
                                        .Target = 0,
                                        .NumControls = 0,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = 0,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L12[] = {{.Gate = P,
                                        .Target = 0,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L13[] = {{.Gate = P,
                                        .Target = 1,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 3 * SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L14[] = {{.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 7 * SEQ_PI / 8,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L15[] = {{.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 15 * SEQ_PI / 16,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L16[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 31 * SEQ_PI / 32,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L17[] = {{.Gate = X,
                                        .Target = 9,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L18[] = {{.Gate = P,
                                        .Target = 0,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L19[] = {{.Gate = P,
                                        .Target = 1,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L20[] = {{.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 8,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L21[] = {{.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 16,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L22[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 32,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L23[] = {{.Gate = X,
                                        .Target = 9,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L24[] = {{.Gate = X,
                                        .Target = 8,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L25[] = {{.Gate = P,
                                        .Target = 1,
                                        .NumControls = 1,
                                        .Control = {8},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L26[] = {{.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {8},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L27[] = {{.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {8},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 8,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L28[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {8},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 16,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L29[] = {{.Gate = X,
                                        .Target = 8,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L30[] = {{.Gate = X,
                                        .Target = 7,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L31[] = {{.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {7},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L32[] = {{.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {7},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L33[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {7},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 8,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L34[] = {{.Gate = X,
                                        .Target = 7,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L35[] = {{.Gate = X,
                                        .Target = 6,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L36[] = {{.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {6},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L37[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {6},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L38[] = {{.Gate = X,
                                        .Target = 6,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L39[] = {{.Gate = X,
                                        .Target = 5,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L40[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {5},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L41[] = {{.Gate = X,
                                        .Target = 5,
                                        .NumControls = 1,
                                        .Control = {10},
                                        .large_control = NULL,
                                        .GateValue = 1,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 0,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 2,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 1,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 4,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 8,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 16,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {9},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 32,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L42[] = {{.Gate = P,
                                        .Target = 1,
                                        .NumControls = 1,
                                        .Control = {8},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 2,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {8},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 4,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {8},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 8,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {8},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 16,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L43[] = {{.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {7},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 2,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {7},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 4,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {7},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 8,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L44[] = {{.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {6},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 2,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {6},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L45[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {5},
                                        .large_control = NULL,
                                        .GateValue = SEQ_PI / 2,
                                        .NumBasisGates = 0},
                                       {.Gate = H,
                                        .Target = 0,
                                        .NumControls = 0,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = 0,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L46[] = {{.Gate = P,
                                        .Target = 1,
                                        .NumControls = 1,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L47[] = {{.Gate = H,
                                        .Target = 1,
                                        .NumControls = 0,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = 0,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L48[] = {{.Gate = P,
                                        .Target = 2,
                                        .NumControls = 1,
                                        .Control = {1},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L49[] = {{.Gate = H,
                                        .Target = 2,
                                        .NumControls = 0,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = 0,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 8,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L50[] = {{.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {1},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L51[] = {{.Gate = P,
                                        .Target = 3,
                                        .NumControls = 1,
                                        .Control = {2},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L52[] = {{.Gate = H,
                                        .Target = 3,
                                        .NumControls = 0,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = 0,
                                        .NumBasisGates = 0},
                                       {.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 16,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L53[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {1},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 8,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L54[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {2},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 4,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L55[] = {{.Gate = P,
                                        .Target = 4,
                                        .NumControls = 1,
                                        .Control = {3},
                                        .large_control = NULL,
                                        .GateValue = -SEQ_PI / 2,
                                        .NumBasisGates = 0}};

static const gate_t cQQ_ADD_5_L56[] = {{.Gate = H,
                                        .Target = 4,
                                        .NumControls = 0,
                                        .Control = {0},
                                        .large_control = NULL,
                                        .GateValue = 0,
                                        .NumBasisGates = 0}};

static const gate_t *cQQ_ADD_5_LAYERS[] = {
    cQQ_ADD_5_L0,  cQQ_ADD_5_L1,  cQQ_ADD_5_L2,  cQQ_ADD_5_L3,  cQQ_ADD_5_L4,  cQQ_ADD_5_L5,
    cQQ_ADD_5_L6,  cQQ_ADD_5_L7,  cQQ_ADD_5_L8,  cQQ_ADD_5_L9,  cQQ_ADD_5_L10, cQQ_ADD_5_L11,
    cQQ_ADD_5_L12, cQQ_ADD_5_L13, cQQ_ADD_5_L14, cQQ_ADD_5_L15, cQQ_ADD_5_L16, cQQ_ADD_5_L17,
    cQQ_ADD_5_L18, cQQ_ADD_5_L19, cQQ_ADD_5_L20, cQQ_ADD_5_L21, cQQ_ADD_5_L22, cQQ_ADD_5_L23,
    cQQ_ADD_5_L24, cQQ_ADD_5_L25, cQQ_ADD_5_L26, cQQ_ADD_5_L27, cQQ_ADD_5_L28, cQQ_ADD_5_L29,
    cQQ_ADD_5_L30, cQQ_ADD_5_L31, cQQ_ADD_5_L32, cQQ_ADD_5_L33, cQQ_ADD_5_L34, cQQ_ADD_5_L35,
    cQQ_ADD_5_L36, cQQ_ADD_5_L37, cQQ_ADD_5_L38, cQQ_ADD_5_L39, cQQ_ADD_5_L40, cQQ_ADD_5_L41,
    cQQ_ADD_5_L42, cQQ_ADD_5_L43, cQQ_ADD_5_L44, cQQ_ADD_5_L45, cQQ_ADD_5_L46, cQQ_ADD_5_L47,
    cQQ_ADD_5_L48, cQQ_ADD_5_L49, cQQ_ADD_5_L50, cQQ_ADD_5_L51, cQQ_ADD_5_L52, cQQ_ADD_5_L53,
    cQQ_ADD_5_L54, cQQ_ADD_5_L55, cQQ_ADD_5_L56};
static const num_t cQQ_ADD_5_GPL[] = {1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                      1, 1, 1, 6, 4, 3, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1};

static const sequence_t HARDCODED_cQQ_ADD_5 = {.seq = (gate_t **)cQQ_ADD_5_LAYERS,
                                               .num_layer = 57,
                                               .used_layer = 57,
                                               .gates_per_layer = (num_t *)cQQ_ADD_5_GPL};

// ============================================================================
// CQ_ADD WIDTH 5 (template-init, 23 layers)
// Qubit layout: [0,4] = target, classical value injected at runtime
// ============================================================================

static sequence_t *cached_CQ_add_5 = NULL;

sequence_t *init_hardcoded_CQ_add_5(void) {
    if (cached_CQ_add_5 != NULL)
        return cached_CQ_add_5;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 23;
    seq->used_layer = 23;
    seq->gates_per_layer = calloc(23, sizeof(num_t));
    seq->seq = calloc(23, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }
    // Layer 0
    seq->gates_per_layer[0] = 1;
    seq->seq[0] = calloc(1, sizeof(gate_t));
    seq->seq[0][0] = (gate_t){.Gate = H,
                              .Target = 4,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 1
    seq->gates_per_layer[1] = 1;
    seq->seq[1] = calloc(1, sizeof(gate_t));
    seq->seq[1][0] = (gate_t){.Gate = P,
                              .Target = 4,
                              .NumControls = 1,
                              .Control = {3},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 2,
                              .NumBasisGates = 0};
    // Layer 2
    seq->gates_per_layer[2] = 2;
    seq->seq[2] = calloc(2, sizeof(gate_t));
    seq->seq[2][0] = (gate_t){.Gate = P,
                              .Target = 4,
                              .NumControls = 1,
                              .Control = {2},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 4,
                              .NumBasisGates = 0};
    seq->seq[2][1] = (gate_t){.Gate = H,
                              .Target = 3,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 3
    seq->gates_per_layer[3] = 2;
    seq->seq[3] = calloc(2, sizeof(gate_t));
    seq->seq[3][0] = (gate_t){.Gate = P,
                              .Target = 4,
                              .NumControls = 1,
                              .Control = {1},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 8,
                              .NumBasisGates = 0};
    seq->seq[3][1] = (gate_t){.Gate = P,
                              .Target = 3,
                              .NumControls = 1,
                              .Control = {2},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 2,
                              .NumBasisGates = 0};
    // Layer 4
    seq->gates_per_layer[4] = 3;
    seq->seq[4] = calloc(3, sizeof(gate_t));
    seq->seq[4][0] = (gate_t){.Gate = P,
                              .Target = 4,
                              .NumControls = 1,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 16,
                              .NumBasisGates = 0};
    seq->seq[4][1] = (gate_t){.Gate = P,
                              .Target = 3,
                              .NumControls = 1,
                              .Control = {1},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 4,
                              .NumBasisGates = 0};
    seq->seq[4][2] = (gate_t){.Gate = H,
                              .Target = 2,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 5
    seq->gates_per_layer[5] = 2;
    seq->seq[5] = calloc(2, sizeof(gate_t));
    seq->seq[5][0] = (gate_t){.Gate = P,
                              .Target = 3,
                              .NumControls = 1,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 8,
                              .NumBasisGates = 0};
    seq->seq[5][1] = (gate_t){.Gate = P,
                              .Target = 2,
                              .NumControls = 1,
                              .Control = {1},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 2,
                              .NumBasisGates = 0};
    // Layer 6
    seq->gates_per_layer[6] = 2;
    seq->seq[6] = calloc(2, sizeof(gate_t));
    seq->seq[6][0] = (gate_t){.Gate = P,
                              .Target = 2,
                              .NumControls = 1,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 4,
                              .NumBasisGates = 0};
    seq->seq[6][1] = (gate_t){.Gate = H,
                              .Target = 1,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 7
    seq->gates_per_layer[7] = 1;
    seq->seq[7] = calloc(1, sizeof(gate_t));
    seq->seq[7][0] = (gate_t){.Gate = P,
                              .Target = 1,
                              .NumControls = 1,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 2,
                              .NumBasisGates = 0};
    // Layer 8
    seq->gates_per_layer[8] = 1;
    seq->seq[8] = calloc(1, sizeof(gate_t));
    seq->seq[8][0] = (gate_t){.Gate = H,
                              .Target = 0,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 9
    seq->gates_per_layer[9] = 1;
    seq->seq[9] = calloc(1, sizeof(gate_t));
    seq->seq[9][0] = (gate_t){.Gate = P,
                              .Target = 0,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 10
    seq->gates_per_layer[10] = 1;
    seq->seq[10] = calloc(1, sizeof(gate_t));
    seq->seq[10][0] = (gate_t){.Gate = P,
                               .Target = 1,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 11
    seq->gates_per_layer[11] = 1;
    seq->seq[11] = calloc(1, sizeof(gate_t));
    seq->seq[11][0] = (gate_t){.Gate = P,
                               .Target = 2,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 12
    seq->gates_per_layer[12] = 1;
    seq->seq[12] = calloc(1, sizeof(gate_t));
    seq->seq[12][0] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 13
    seq->gates_per_layer[13] = 1;
    seq->seq[13] = calloc(1, sizeof(gate_t));
    seq->seq[13][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 14
    seq->gates_per_layer[14] = 1;
    seq->seq[14] = calloc(1, sizeof(gate_t));
    seq->seq[14][0] = (gate_t){.Gate = H,
                               .Target = 0,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 15
    seq->gates_per_layer[15] = 1;
    seq->seq[15] = calloc(1, sizeof(gate_t));
    seq->seq[15][0] = (gate_t){.Gate = P,
                               .Target = 1,
                               .NumControls = 1,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 2,
                               .NumBasisGates = 0};
    // Layer 16
    seq->gates_per_layer[16] = 2;
    seq->seq[16] = calloc(2, sizeof(gate_t));
    seq->seq[16][0] = (gate_t){.Gate = P,
                               .Target = 2,
                               .NumControls = 1,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 4,
                               .NumBasisGates = 0};
    seq->seq[16][1] = (gate_t){.Gate = H,
                               .Target = 1,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 17
    seq->gates_per_layer[17] = 2;
    seq->seq[17] = calloc(2, sizeof(gate_t));
    seq->seq[17][0] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 1,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 8,
                               .NumBasisGates = 0};
    seq->seq[17][1] = (gate_t){.Gate = P,
                               .Target = 2,
                               .NumControls = 1,
                               .Control = {1},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 2,
                               .NumBasisGates = 0};
    // Layer 18
    seq->gates_per_layer[18] = 3;
    seq->seq[18] = calloc(3, sizeof(gate_t));
    seq->seq[18][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 16,
                               .NumBasisGates = 0};
    seq->seq[18][1] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 1,
                               .Control = {1},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 4,
                               .NumBasisGates = 0};
    seq->seq[18][2] = (gate_t){.Gate = H,
                               .Target = 2,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 19
    seq->gates_per_layer[19] = 2;
    seq->seq[19] = calloc(2, sizeof(gate_t));
    seq->seq[19][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {1},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 8,
                               .NumBasisGates = 0};
    seq->seq[19][1] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 1,
                               .Control = {2},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 2,
                               .NumBasisGates = 0};
    // Layer 20
    seq->gates_per_layer[20] = 2;
    seq->seq[20] = calloc(2, sizeof(gate_t));
    seq->seq[20][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {2},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 4,
                               .NumBasisGates = 0};
    seq->seq[20][1] = (gate_t){.Gate = H,
                               .Target = 3,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 21
    seq->gates_per_layer[21] = 1;
    seq->seq[21] = calloc(1, sizeof(gate_t));
    seq->seq[21][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {3},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 2,
                               .NumBasisGates = 0};
    // Layer 22
    seq->gates_per_layer[22] = 1;
    seq->seq[22] = calloc(1, sizeof(gate_t));
    seq->seq[22][0] = (gate_t){.Gate = H,
                               .Target = 4,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    cached_CQ_add_5 = seq;
    return seq;
}

// ============================================================================
// cCQ_ADD WIDTH 5 (template-init, 23 layers)
// Qubit layout: [0,4] = target, [5] = control, classical value injected at runtime
// ============================================================================

static sequence_t *cached_cCQ_add_5 = NULL;

sequence_t *init_hardcoded_cCQ_add_5(void) {
    if (cached_cCQ_add_5 != NULL)
        return cached_cCQ_add_5;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 23;
    seq->used_layer = 23;
    seq->gates_per_layer = calloc(23, sizeof(num_t));
    seq->seq = calloc(23, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }
    // Layer 0
    seq->gates_per_layer[0] = 1;
    seq->seq[0] = calloc(1, sizeof(gate_t));
    seq->seq[0][0] = (gate_t){.Gate = H,
                              .Target = 4,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 1
    seq->gates_per_layer[1] = 1;
    seq->seq[1] = calloc(1, sizeof(gate_t));
    seq->seq[1][0] = (gate_t){.Gate = P,
                              .Target = 4,
                              .NumControls = 1,
                              .Control = {3},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 2,
                              .NumBasisGates = 0};
    // Layer 2
    seq->gates_per_layer[2] = 2;
    seq->seq[2] = calloc(2, sizeof(gate_t));
    seq->seq[2][0] = (gate_t){.Gate = P,
                              .Target = 4,
                              .NumControls = 1,
                              .Control = {2},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 4,
                              .NumBasisGates = 0};
    seq->seq[2][1] = (gate_t){.Gate = H,
                              .Target = 3,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 3
    seq->gates_per_layer[3] = 2;
    seq->seq[3] = calloc(2, sizeof(gate_t));
    seq->seq[3][0] = (gate_t){.Gate = P,
                              .Target = 4,
                              .NumControls = 1,
                              .Control = {1},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 8,
                              .NumBasisGates = 0};
    seq->seq[3][1] = (gate_t){.Gate = P,
                              .Target = 3,
                              .NumControls = 1,
                              .Control = {2},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 2,
                              .NumBasisGates = 0};
    // Layer 4
    seq->gates_per_layer[4] = 3;
    seq->seq[4] = calloc(3, sizeof(gate_t));
    seq->seq[4][0] = (gate_t){.Gate = P,
                              .Target = 4,
                              .NumControls = 1,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 16,
                              .NumBasisGates = 0};
    seq->seq[4][1] = (gate_t){.Gate = P,
                              .Target = 3,
                              .NumControls = 1,
                              .Control = {1},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 4,
                              .NumBasisGates = 0};
    seq->seq[4][2] = (gate_t){.Gate = H,
                              .Target = 2,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 5
    seq->gates_per_layer[5] = 2;
    seq->seq[5] = calloc(2, sizeof(gate_t));
    seq->seq[5][0] = (gate_t){.Gate = P,
                              .Target = 3,
                              .NumControls = 1,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 8,
                              .NumBasisGates = 0};
    seq->seq[5][1] = (gate_t){.Gate = P,
                              .Target = 2,
                              .NumControls = 1,
                              .Control = {1},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 2,
                              .NumBasisGates = 0};
    // Layer 6
    seq->gates_per_layer[6] = 2;
    seq->seq[6] = calloc(2, sizeof(gate_t));
    seq->seq[6][0] = (gate_t){.Gate = P,
                              .Target = 2,
                              .NumControls = 1,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 4,
                              .NumBasisGates = 0};
    seq->seq[6][1] = (gate_t){.Gate = H,
                              .Target = 1,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 7
    seq->gates_per_layer[7] = 1;
    seq->seq[7] = calloc(1, sizeof(gate_t));
    seq->seq[7][0] = (gate_t){.Gate = P,
                              .Target = 1,
                              .NumControls = 1,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = SEQ_PI / 2,
                              .NumBasisGates = 0};
    // Layer 8
    seq->gates_per_layer[8] = 1;
    seq->seq[8] = calloc(1, sizeof(gate_t));
    seq->seq[8][0] = (gate_t){.Gate = H,
                              .Target = 0,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 9
    seq->gates_per_layer[9] = 1;
    seq->seq[9] = calloc(1, sizeof(gate_t));
    seq->seq[9][0] = (gate_t){.Gate = P,
                              .Target = 0,
                              .NumControls = 1,
                              .Control = {5},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Layer 10
    seq->gates_per_layer[10] = 1;
    seq->seq[10] = calloc(1, sizeof(gate_t));
    seq->seq[10][0] = (gate_t){.Gate = P,
                               .Target = 1,
                               .NumControls = 1,
                               .Control = {5},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 11
    seq->gates_per_layer[11] = 1;
    seq->seq[11] = calloc(1, sizeof(gate_t));
    seq->seq[11][0] = (gate_t){.Gate = P,
                               .Target = 2,
                               .NumControls = 1,
                               .Control = {5},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 12
    seq->gates_per_layer[12] = 1;
    seq->seq[12] = calloc(1, sizeof(gate_t));
    seq->seq[12][0] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 1,
                               .Control = {5},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 13
    seq->gates_per_layer[13] = 1;
    seq->seq[13] = calloc(1, sizeof(gate_t));
    seq->seq[13][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {5},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 14
    seq->gates_per_layer[14] = 1;
    seq->seq[14] = calloc(1, sizeof(gate_t));
    seq->seq[14][0] = (gate_t){.Gate = H,
                               .Target = 0,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 15
    seq->gates_per_layer[15] = 1;
    seq->seq[15] = calloc(1, sizeof(gate_t));
    seq->seq[15][0] = (gate_t){.Gate = P,
                               .Target = 1,
                               .NumControls = 1,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 2,
                               .NumBasisGates = 0};
    // Layer 16
    seq->gates_per_layer[16] = 2;
    seq->seq[16] = calloc(2, sizeof(gate_t));
    seq->seq[16][0] = (gate_t){.Gate = P,
                               .Target = 2,
                               .NumControls = 1,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 4,
                               .NumBasisGates = 0};
    seq->seq[16][1] = (gate_t){.Gate = H,
                               .Target = 1,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 17
    seq->gates_per_layer[17] = 2;
    seq->seq[17] = calloc(2, sizeof(gate_t));
    seq->seq[17][0] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 1,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 8,
                               .NumBasisGates = 0};
    seq->seq[17][1] = (gate_t){.Gate = P,
                               .Target = 2,
                               .NumControls = 1,
                               .Control = {1},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 2,
                               .NumBasisGates = 0};
    // Layer 18
    seq->gates_per_layer[18] = 3;
    seq->seq[18] = calloc(3, sizeof(gate_t));
    seq->seq[18][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 16,
                               .NumBasisGates = 0};
    seq->seq[18][1] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 1,
                               .Control = {1},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 4,
                               .NumBasisGates = 0};
    seq->seq[18][2] = (gate_t){.Gate = H,
                               .Target = 2,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 19
    seq->gates_per_layer[19] = 2;
    seq->seq[19] = calloc(2, sizeof(gate_t));
    seq->seq[19][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {1},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 8,
                               .NumBasisGates = 0};
    seq->seq[19][1] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 1,
                               .Control = {2},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 2,
                               .NumBasisGates = 0};
    // Layer 20
    seq->gates_per_layer[20] = 2;
    seq->seq[20] = calloc(2, sizeof(gate_t));
    seq->seq[20][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {2},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 4,
                               .NumBasisGates = 0};
    seq->seq[20][1] = (gate_t){.Gate = H,
                               .Target = 3,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    // Layer 21
    seq->gates_per_layer[21] = 1;
    seq->seq[21] = calloc(1, sizeof(gate_t));
    seq->seq[21][0] = (gate_t){.Gate = P,
                               .Target = 4,
                               .NumControls = 1,
                               .Control = {3},
                               .large_control = NULL,
                               .GateValue = -SEQ_PI / 2,
                               .NumBasisGates = 0};
    // Layer 22
    seq->gates_per_layer[22] = 1;
    seq->seq[22] = calloc(1, sizeof(gate_t));
    seq->seq[22][0] = (gate_t){.Gate = H,
                               .Target = 4,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};
    cached_cCQ_add_5 = seq;
    return seq;
}

// ============================================================================
// DISPATCH HELPERS FOR WIDTH 5
// ============================================================================

const sequence_t *get_hardcoded_QQ_add_5(int bits) {
    (void)bits;
    return &HARDCODED_QQ_ADD_5;
}

const sequence_t *get_hardcoded_cQQ_add_5(int bits) {
    (void)bits;
    return &HARDCODED_cQQ_ADD_5;
}

sequence_t *get_hardcoded_CQ_add_5(int bits) {
    (void)bits;
    return init_hardcoded_CQ_add_5();
}

sequence_t *get_hardcoded_cCQ_add_5(int bits) {
    (void)bits;
    return init_hardcoded_cCQ_add_5();
}

#endif // SEQ_WIDTH_5
