//
// add_seq_4.c - Hardcoded addition sequences for 4-bit width
//
// Generated by scripts/generate_seq_all.py - DO NOT EDIT MANUALLY
//
// Contains: QQ_add, cQQ_add (static const), CQ_add, cCQ_add (template-init)
// Shared QFT/IQFT: static const arrays shared between QQ_add and cQQ_add,
//                  init helpers shared between CQ_add and cCQ_add
//

#include "sequences.h"

#ifdef SEQ_WIDTH_4

#include <stdlib.h>

// SEQ_PI as compile-time constant for static initializers
// (math.h M_PI is not a constant expression in standard C)
#ifndef SEQ_PI
#define SEQ_PI 3.14159265358979323846
#endif

// ============================================================================
// SHARED QFT LAYERS WIDTH 4 (7 layers)
// Used by QQ_ADD and cQQ_ADD composite LAYERS arrays
// ============================================================================

static const gate_t SHARED_QFT_4_L0[] = {{.Gate = H,
                                          .Target = 3,
                                          .NumControls = 0,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 0,
                                          .NumBasisGates = 0}};

static const gate_t SHARED_QFT_4_L1[] = {{.Gate = P,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {2},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 2,
                                          .NumBasisGates = 0}};

static const gate_t SHARED_QFT_4_L2[] = {{.Gate = P,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 4,
                                          .NumBasisGates = 0},
                                         {.Gate = H,
                                          .Target = 2,
                                          .NumControls = 0,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 0,
                                          .NumBasisGates = 0}};

static const gate_t SHARED_QFT_4_L3[] = {{.Gate = P,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 8,
                                          .NumBasisGates = 0},
                                         {.Gate = P,
                                          .Target = 2,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 2,
                                          .NumBasisGates = 0}};

static const gate_t SHARED_QFT_4_L4[] = {{.Gate = P,
                                          .Target = 2,
                                          .NumControls = 1,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 4,
                                          .NumBasisGates = 0},
                                         {.Gate = H,
                                          .Target = 1,
                                          .NumControls = 0,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 0,
                                          .NumBasisGates = 0}};

static const gate_t SHARED_QFT_4_L5[] = {{.Gate = P,
                                          .Target = 1,
                                          .NumControls = 1,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 2,
                                          .NumBasisGates = 0}};

static const gate_t SHARED_QFT_4_L6[] = {{.Gate = H,
                                          .Target = 0,
                                          .NumControls = 0,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 0,
                                          .NumBasisGates = 0}};

// ============================================================================
// SHARED IQFT LAYERS WIDTH 4 (7 layers)
// Used by QQ_ADD and cQQ_ADD composite LAYERS arrays
// ============================================================================

static const gate_t SHARED_IQFT_4_L0[] = {{.Gate = H,
                                           .Target = 0,
                                           .NumControls = 0,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = 0,
                                           .NumBasisGates = 0}};

static const gate_t SHARED_IQFT_4_L1[] = {{.Gate = P,
                                           .Target = 1,
                                           .NumControls = 1,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 2,
                                           .NumBasisGates = 0}};

static const gate_t SHARED_IQFT_4_L2[] = {{.Gate = P,
                                           .Target = 2,
                                           .NumControls = 1,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 4,
                                           .NumBasisGates = 0},
                                          {.Gate = H,
                                           .Target = 1,
                                           .NumControls = 0,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = 0,
                                           .NumBasisGates = 0}};

static const gate_t SHARED_IQFT_4_L3[] = {{.Gate = P,
                                           .Target = 3,
                                           .NumControls = 1,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 8,
                                           .NumBasisGates = 0},
                                          {.Gate = P,
                                           .Target = 2,
                                           .NumControls = 1,
                                           .Control = {1},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 2,
                                           .NumBasisGates = 0}};

static const gate_t SHARED_IQFT_4_L4[] = {{.Gate = P,
                                           .Target = 3,
                                           .NumControls = 1,
                                           .Control = {1},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 4,
                                           .NumBasisGates = 0},
                                          {.Gate = H,
                                           .Target = 2,
                                           .NumControls = 0,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = 0,
                                           .NumBasisGates = 0}};

static const gate_t SHARED_IQFT_4_L5[] = {{.Gate = P,
                                           .Target = 3,
                                           .NumControls = 1,
                                           .Control = {2},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 2,
                                           .NumBasisGates = 0}};

static const gate_t SHARED_IQFT_4_L6[] = {{.Gate = H,
                                           .Target = 3,
                                           .NumControls = 0,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = 0,
                                           .NumBasisGates = 0}};

// ============================================================================
// QQ_ADD WIDTH 4 (22 layers)
// Qubit layout: [0,3] = target, [4,7] = control
// ============================================================================

static const gate_t QQ_ADD_MID_4_L0[] = {{.Gate = P,
                                          .Target = 0,
                                          .NumControls = 1,
                                          .Control = {4},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI,
                                          .NumBasisGates = 0}};

static const gate_t QQ_ADD_MID_4_L1[] = {{.Gate = P,
                                          .Target = 1,
                                          .NumControls = 1,
                                          .Control = {4},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 2,
                                          .NumBasisGates = 0}};

static const gate_t QQ_ADD_MID_4_L2[] = {{.Gate = P,
                                          .Target = 2,
                                          .NumControls = 1,
                                          .Control = {4},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 4,
                                          .NumBasisGates = 0}};

static const gate_t QQ_ADD_MID_4_L3[] = {{.Gate = P,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {4},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 8,
                                          .NumBasisGates = 0},
                                         {.Gate = P,
                                          .Target = 1,
                                          .NumControls = 1,
                                          .Control = {5},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI,
                                          .NumBasisGates = 0}};

static const gate_t QQ_ADD_MID_4_L4[] = {{.Gate = P,
                                          .Target = 2,
                                          .NumControls = 1,
                                          .Control = {5},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 2,
                                          .NumBasisGates = 0}};

static const gate_t QQ_ADD_MID_4_L5[] = {{.Gate = P,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {5},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 4,
                                          .NumBasisGates = 0},
                                         {.Gate = P,
                                          .Target = 2,
                                          .NumControls = 1,
                                          .Control = {6},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI,
                                          .NumBasisGates = 0}};

static const gate_t QQ_ADD_MID_4_L6[] = {{.Gate = P,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {6},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI / 2,
                                          .NumBasisGates = 0}};

static const gate_t QQ_ADD_MID_4_L7[] = {{.Gate = P,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {7},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI,
                                          .NumBasisGates = 0}};

static const gate_t *QQ_ADD_4_LAYERS[] = {
    SHARED_QFT_4_L0,  SHARED_QFT_4_L1,  SHARED_QFT_4_L2,  SHARED_QFT_4_L3,  SHARED_QFT_4_L4,
    SHARED_QFT_4_L5,  SHARED_QFT_4_L6,  QQ_ADD_MID_4_L0,  QQ_ADD_MID_4_L1,  QQ_ADD_MID_4_L2,
    QQ_ADD_MID_4_L3,  QQ_ADD_MID_4_L4,  QQ_ADD_MID_4_L5,  QQ_ADD_MID_4_L6,  QQ_ADD_MID_4_L7,
    SHARED_IQFT_4_L0, SHARED_IQFT_4_L1, SHARED_IQFT_4_L2, SHARED_IQFT_4_L3, SHARED_IQFT_4_L4,
    SHARED_IQFT_4_L5, SHARED_IQFT_4_L6};
static const num_t QQ_ADD_4_GPL[] = {1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2,
                                     1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1};

static const sequence_t HARDCODED_QQ_ADD_4 = {.seq = (gate_t **)QQ_ADD_4_LAYERS,
                                              .num_layer = 22,
                                              .used_layer = 22,
                                              .gates_per_layer = (num_t *)QQ_ADD_4_GPL};

// ============================================================================
// cQQ_ADD WIDTH 4 (39 layers)
// Qubit layout: [0,3] = target, [4,7] = b, [8] = control
// ============================================================================

static const gate_t cQQ_ADD_MID_4_L0[] = {{.Gate = P,
                                           .Target = 0,
                                           .NumControls = 1,
                                           .Control = {8},
                                           .large_control = NULL,
                                           .GateValue = SEQ_PI / 2,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L1[] = {{.Gate = P,
                                           .Target = 1,
                                           .NumControls = 1,
                                           .Control = {8},
                                           .large_control = NULL,
                                           .GateValue = 3 * SEQ_PI / 4,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L2[] = {{.Gate = P,
                                           .Target = 2,
                                           .NumControls = 1,
                                           .Control = {8},
                                           .large_control = NULL,
                                           .GateValue = 7 * SEQ_PI / 8,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L3[] = {{.Gate = P,
                                           .Target = 3,
                                           .NumControls = 1,
                                           .Control = {8},
                                           .large_control = NULL,
                                           .GateValue = 15 * SEQ_PI / 16,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L4[] = {{.Gate = X,
                                           .Target = 4,
                                           .NumControls = 1,
                                           .Control = {8},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L5[] = {{.Gate = P,
                                           .Target = 0,
                                           .NumControls = 1,
                                           .Control = {4},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 2,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L6[] = {{.Gate = P,
                                           .Target = 1,
                                           .NumControls = 1,
                                           .Control = {4},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 4,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L7[] = {{.Gate = P,
                                           .Target = 2,
                                           .NumControls = 1,
                                           .Control = {4},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 8,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L8[] = {{.Gate = P,
                                           .Target = 3,
                                           .NumControls = 1,
                                           .Control = {4},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 16,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L9[] = {{.Gate = X,
                                           .Target = 4,
                                           .NumControls = 1,
                                           .Control = {8},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L10[] = {{.Gate = X,
                                            .Target = 5,
                                            .NumControls = 1,
                                            .Control = {8},
                                            .large_control = NULL,
                                            .GateValue = 1,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L11[] = {{.Gate = P,
                                            .Target = 1,
                                            .NumControls = 1,
                                            .Control = {5},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 2,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L12[] = {{.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {5},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 4,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L13[] = {{.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {5},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 8,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L14[] = {{.Gate = X,
                                            .Target = 5,
                                            .NumControls = 1,
                                            .Control = {8},
                                            .large_control = NULL,
                                            .GateValue = 1,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L15[] = {{.Gate = X,
                                            .Target = 6,
                                            .NumControls = 1,
                                            .Control = {8},
                                            .large_control = NULL,
                                            .GateValue = 1,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L16[] = {{.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {6},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 2,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L17[] = {{.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {6},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 4,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L18[] = {{.Gate = X,
                                            .Target = 6,
                                            .NumControls = 1,
                                            .Control = {8},
                                            .large_control = NULL,
                                            .GateValue = 1,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L19[] = {{.Gate = X,
                                            .Target = 7,
                                            .NumControls = 1,
                                            .Control = {8},
                                            .large_control = NULL,
                                            .GateValue = 1,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L20[] = {{.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {7},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 2,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L21[] = {{.Gate = X,
                                            .Target = 7,
                                            .NumControls = 1,
                                            .Control = {8},
                                            .large_control = NULL,
                                            .GateValue = 1,
                                            .NumBasisGates = 0},
                                           {.Gate = P,
                                            .Target = 0,
                                            .NumControls = 1,
                                            .Control = {4},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 2,
                                            .NumBasisGates = 0},
                                           {.Gate = P,
                                            .Target = 1,
                                            .NumControls = 1,
                                            .Control = {4},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 4,
                                            .NumBasisGates = 0},
                                           {.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {4},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 8,
                                            .NumBasisGates = 0},
                                           {.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {4},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 16,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L22[] = {{.Gate = P,
                                            .Target = 1,
                                            .NumControls = 1,
                                            .Control = {5},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 2,
                                            .NumBasisGates = 0},
                                           {.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {5},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 4,
                                            .NumBasisGates = 0},
                                           {.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {5},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 8,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L23[] = {{.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {6},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 2,
                                            .NumBasisGates = 0},
                                           {.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {6},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 4,
                                            .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_4_L24[] = {{.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {7},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 2,
                                            .NumBasisGates = 0}};

static const gate_t *cQQ_ADD_4_LAYERS[] = {
    SHARED_QFT_4_L0,   SHARED_QFT_4_L1,   SHARED_QFT_4_L2,   SHARED_QFT_4_L3,   SHARED_QFT_4_L4,
    SHARED_QFT_4_L5,   SHARED_QFT_4_L6,   cQQ_ADD_MID_4_L0,  cQQ_ADD_MID_4_L1,  cQQ_ADD_MID_4_L2,
    cQQ_ADD_MID_4_L3,  cQQ_ADD_MID_4_L4,  cQQ_ADD_MID_4_L5,  cQQ_ADD_MID_4_L6,  cQQ_ADD_MID_4_L7,
    cQQ_ADD_MID_4_L8,  cQQ_ADD_MID_4_L9,  cQQ_ADD_MID_4_L10, cQQ_ADD_MID_4_L11, cQQ_ADD_MID_4_L12,
    cQQ_ADD_MID_4_L13, cQQ_ADD_MID_4_L14, cQQ_ADD_MID_4_L15, cQQ_ADD_MID_4_L16, cQQ_ADD_MID_4_L17,
    cQQ_ADD_MID_4_L18, cQQ_ADD_MID_4_L19, cQQ_ADD_MID_4_L20, cQQ_ADD_MID_4_L21, cQQ_ADD_MID_4_L22,
    cQQ_ADD_MID_4_L23, cQQ_ADD_MID_4_L24, SHARED_IQFT_4_L0,  SHARED_IQFT_4_L1,  SHARED_IQFT_4_L2,
    SHARED_IQFT_4_L3,  SHARED_IQFT_4_L4,  SHARED_IQFT_4_L5,  SHARED_IQFT_4_L6};
static const num_t cQQ_ADD_4_GPL[] = {1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                      1, 1, 1, 1, 1, 1, 1, 1, 5, 3, 2, 1, 1, 1, 2, 2, 2, 1, 1};

static const sequence_t HARDCODED_cQQ_ADD_4 = {.seq = (gate_t **)cQQ_ADD_4_LAYERS,
                                               .num_layer = 39,
                                               .used_layer = 39,
                                               .gates_per_layer = (num_t *)cQQ_ADD_4_GPL};

// ============================================================================
// SHARED QFT/IQFT INIT HELPERS WIDTH 4
// Used by CQ_ADD and cCQ_ADD template-init functions
// ============================================================================

static void init_shared_qft_layers_4(sequence_t *seq, int start_layer) {
    // QFT Layer 0
    seq->gates_per_layer[start_layer + 0] = 1;
    seq->seq[start_layer + 0] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 0][0] = (gate_t){.Gate = H,
                                            .Target = 3,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
    // QFT Layer 1
    seq->gates_per_layer[start_layer + 1] = 1;
    seq->seq[start_layer + 1] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 1][0] = (gate_t){.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {2},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 2,
                                            .NumBasisGates = 0};
    // QFT Layer 2
    seq->gates_per_layer[start_layer + 2] = 2;
    seq->seq[start_layer + 2] = calloc(2, sizeof(gate_t));
    seq->seq[start_layer + 2][0] = (gate_t){.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {1},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 4,
                                            .NumBasisGates = 0};
    seq->seq[start_layer + 2][1] = (gate_t){.Gate = H,
                                            .Target = 2,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
    // QFT Layer 3
    seq->gates_per_layer[start_layer + 3] = 2;
    seq->seq[start_layer + 3] = calloc(2, sizeof(gate_t));
    seq->seq[start_layer + 3][0] = (gate_t){.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 8,
                                            .NumBasisGates = 0};
    seq->seq[start_layer + 3][1] = (gate_t){.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {1},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 2,
                                            .NumBasisGates = 0};
    // QFT Layer 4
    seq->gates_per_layer[start_layer + 4] = 2;
    seq->seq[start_layer + 4] = calloc(2, sizeof(gate_t));
    seq->seq[start_layer + 4][0] = (gate_t){.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 4,
                                            .NumBasisGates = 0};
    seq->seq[start_layer + 4][1] = (gate_t){.Gate = H,
                                            .Target = 1,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
    // QFT Layer 5
    seq->gates_per_layer[start_layer + 5] = 1;
    seq->seq[start_layer + 5] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 5][0] = (gate_t){.Gate = P,
                                            .Target = 1,
                                            .NumControls = 1,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = SEQ_PI / 2,
                                            .NumBasisGates = 0};
    // QFT Layer 6
    seq->gates_per_layer[start_layer + 6] = 1;
    seq->seq[start_layer + 6] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 6][0] = (gate_t){.Gate = H,
                                            .Target = 0,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
}

static void init_shared_iqft_layers_4(sequence_t *seq, int start_layer) {
    // IQFT Layer 0
    seq->gates_per_layer[start_layer + 0] = 1;
    seq->seq[start_layer + 0] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 0][0] = (gate_t){.Gate = H,
                                            .Target = 0,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
    // IQFT Layer 1
    seq->gates_per_layer[start_layer + 1] = 1;
    seq->seq[start_layer + 1] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 1][0] = (gate_t){.Gate = P,
                                            .Target = 1,
                                            .NumControls = 1,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 2,
                                            .NumBasisGates = 0};
    // IQFT Layer 2
    seq->gates_per_layer[start_layer + 2] = 2;
    seq->seq[start_layer + 2] = calloc(2, sizeof(gate_t));
    seq->seq[start_layer + 2][0] = (gate_t){.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 4,
                                            .NumBasisGates = 0};
    seq->seq[start_layer + 2][1] = (gate_t){.Gate = H,
                                            .Target = 1,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
    // IQFT Layer 3
    seq->gates_per_layer[start_layer + 3] = 2;
    seq->seq[start_layer + 3] = calloc(2, sizeof(gate_t));
    seq->seq[start_layer + 3][0] = (gate_t){.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 8,
                                            .NumBasisGates = 0};
    seq->seq[start_layer + 3][1] = (gate_t){.Gate = P,
                                            .Target = 2,
                                            .NumControls = 1,
                                            .Control = {1},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 2,
                                            .NumBasisGates = 0};
    // IQFT Layer 4
    seq->gates_per_layer[start_layer + 4] = 2;
    seq->seq[start_layer + 4] = calloc(2, sizeof(gate_t));
    seq->seq[start_layer + 4][0] = (gate_t){.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {1},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 4,
                                            .NumBasisGates = 0};
    seq->seq[start_layer + 4][1] = (gate_t){.Gate = H,
                                            .Target = 2,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
    // IQFT Layer 5
    seq->gates_per_layer[start_layer + 5] = 1;
    seq->seq[start_layer + 5] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 5][0] = (gate_t){.Gate = P,
                                            .Target = 3,
                                            .NumControls = 1,
                                            .Control = {2},
                                            .large_control = NULL,
                                            .GateValue = -SEQ_PI / 2,
                                            .NumBasisGates = 0};
    // IQFT Layer 6
    seq->gates_per_layer[start_layer + 6] = 1;
    seq->seq[start_layer + 6] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 6][0] = (gate_t){.Gate = H,
                                            .Target = 3,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
}

// ============================================================================
// CQ_ADD WIDTH 4 (template-init, 18 layers)
// Qubit layout: [0,3] = target, classical value injected at runtime
// ============================================================================

static sequence_t *cached_CQ_add_4 = NULL;

sequence_t *init_hardcoded_CQ_add_4(void) {
    if (cached_CQ_add_4 != NULL)
        return cached_CQ_add_4;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 18;
    seq->used_layer = 18;
    seq->gates_per_layer = calloc(18, sizeof(num_t));
    seq->seq = calloc(18, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // QFT layers (shared helper)
    init_shared_qft_layers_4(seq, 0);

    // Rotation Layer 7
    seq->gates_per_layer[7] = 1;
    seq->seq[7] = calloc(1, sizeof(gate_t));
    seq->seq[7][0] = (gate_t){.Gate = P,
                              .Target = 0,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Rotation Layer 8
    seq->gates_per_layer[8] = 1;
    seq->seq[8] = calloc(1, sizeof(gate_t));
    seq->seq[8][0] = (gate_t){.Gate = P,
                              .Target = 1,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Rotation Layer 9
    seq->gates_per_layer[9] = 1;
    seq->seq[9] = calloc(1, sizeof(gate_t));
    seq->seq[9][0] = (gate_t){.Gate = P,
                              .Target = 2,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Rotation Layer 10
    seq->gates_per_layer[10] = 1;
    seq->seq[10] = calloc(1, sizeof(gate_t));
    seq->seq[10][0] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 0,
                               .Control = {0},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};

    // IQFT layers (shared helper)
    init_shared_iqft_layers_4(seq, 11);

    cached_CQ_add_4 = seq;
    return seq;
}

// ============================================================================
// cCQ_ADD WIDTH 4 (template-init, 18 layers)
// Qubit layout: [0,3] = target, [4] = control, classical value injected at runtime
// ============================================================================

static sequence_t *cached_cCQ_add_4 = NULL;

sequence_t *init_hardcoded_cCQ_add_4(void) {
    if (cached_cCQ_add_4 != NULL)
        return cached_cCQ_add_4;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 18;
    seq->used_layer = 18;
    seq->gates_per_layer = calloc(18, sizeof(num_t));
    seq->seq = calloc(18, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // QFT layers (shared helper)
    init_shared_qft_layers_4(seq, 0);

    // Rotation Layer 7
    seq->gates_per_layer[7] = 1;
    seq->seq[7] = calloc(1, sizeof(gate_t));
    seq->seq[7][0] = (gate_t){.Gate = P,
                              .Target = 0,
                              .NumControls = 1,
                              .Control = {4},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Rotation Layer 8
    seq->gates_per_layer[8] = 1;
    seq->seq[8] = calloc(1, sizeof(gate_t));
    seq->seq[8][0] = (gate_t){.Gate = P,
                              .Target = 1,
                              .NumControls = 1,
                              .Control = {4},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Rotation Layer 9
    seq->gates_per_layer[9] = 1;
    seq->seq[9] = calloc(1, sizeof(gate_t));
    seq->seq[9][0] = (gate_t){.Gate = P,
                              .Target = 2,
                              .NumControls = 1,
                              .Control = {4},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};
    // Rotation Layer 10
    seq->gates_per_layer[10] = 1;
    seq->seq[10] = calloc(1, sizeof(gate_t));
    seq->seq[10][0] = (gate_t){.Gate = P,
                               .Target = 3,
                               .NumControls = 1,
                               .Control = {4},
                               .large_control = NULL,
                               .GateValue = 0,
                               .NumBasisGates = 0};

    // IQFT layers (shared helper)
    init_shared_iqft_layers_4(seq, 11);

    cached_cCQ_add_4 = seq;
    return seq;
}

// ============================================================================
// DISPATCH HELPERS FOR WIDTH 4
// ============================================================================

const sequence_t *get_hardcoded_QQ_add_4(int bits) {
    (void)bits;
    return &HARDCODED_QQ_ADD_4;
}

const sequence_t *get_hardcoded_cQQ_add_4(int bits) {
    (void)bits;
    return &HARDCODED_cQQ_ADD_4;
}

sequence_t *get_hardcoded_CQ_add_4(int bits) {
    (void)bits;
    return init_hardcoded_CQ_add_4();
}

sequence_t *get_hardcoded_cCQ_add_4(int bits) {
    (void)bits;
    return init_hardcoded_cCQ_add_4();
}

#endif // SEQ_WIDTH_4
