//
// toffoli_clifft_qq_1.c - CDKM QQ Clifford+T addition for 1-bit width
//
// Generated by scripts/generate_toffoli_seq.py --clifford-t - DO NOT EDIT MANUALLY
//
// Contains: Toffoli CDKM QQ Clifford+T addition (static const, zero CCX)
// Algorithm: CDKM ripple-carry adder with CCX->Clifford+T decomposition
// All gates: H/T/Tdg/CX/X (max 1 control) -- fully static const.
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_1

#include <math.h>

// ============================================================================
// TOFFOLI CLIFFT QQ_ADD WIDTH 1 (1 layers)
// Qubit layout: [0] = target, [1] = source
// Total qubits: 2
// All gates: H/T/Tdg/CX/X (max 1 control) -- zero CCX
// ============================================================================

static const gate_t TOFFOLI_CLIFFT_QQ_1_L0[] = {{.Gate = X,
                                                 .Target = 0,
                                                 .NumControls = 1,
                                                 .Control = {1},
                                                 .large_control = NULL,
                                                 .GateValue = 1,
                                                 .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CLIFFT_QQ_1_LAYERS[] = {TOFFOLI_CLIFFT_QQ_1_L0};
static const num_t TOFFOLI_CLIFFT_QQ_1_GPL[] = {1};

static const sequence_t HARDCODED_TOFFOLI_CLIFFT_QQ_1 = {
    .seq = (gate_t **)TOFFOLI_CLIFFT_QQ_1_LAYERS,
    .num_layer = 1,
    .used_layer = 1,
    .gates_per_layer = (num_t *)TOFFOLI_CLIFFT_QQ_1_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 1
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_QQ_add_1(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CLIFFT_QQ_1;
}

#endif // TOFFOLI_SEQ_WIDTH_1
