//
// toffoli_clifft_cla_cq_inc_2.c - BK CLA CQ increment Clifford+T for 2-bit width
//
// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY
//
// Contains: BK CLA CQ_inc (value=1) Clifford+T (static const, zero CCX)
// Algorithm: Brent-Kung CLA with temp-register CQ + classical-bit simplification + CCX->Clifford+T
// All gates are H/T/Tdg/CX/X (max 1 control) -- no dynamic allocation needed.
//

#include "toffoli_sequences.h"
#include <math.h>

#ifdef TOFFOLI_SEQ_WIDTH_2

// ============================================================================
// TOFFOLI CLIFFT CLA CQ_INC WIDTH 2 (9 Clifford+T layers)
// Source: 5 X + 4 CX + 0 CCX = 9 Toffoli gates
// Clifford+T: 0*15 + 4*1 + 5*1 = 9 gates
// Qubit layout: temp[0..1], self[2..3], g[4..4], tree/carry[5..5]
// All gates: H/T/Tdg/CX/X (zero CCX)
// ============================================================================

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L0[] = {{.Gate = X,
                                                         .Target = 0,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L1[] = {{.Gate = X,
                                                         .Target = 4,
                                                         .NumControls = 1,
                                                         .Control = {2},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L2[] = {{.Gate = X,
                                                         .Target = 2,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L3[] = {{.Gate = X,
                                                         .Target = 5,
                                                         .NumControls = 1,
                                                         .Control = {4},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L4[] = {{.Gate = X,
                                                         .Target = 2,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L5[] = {{.Gate = X,
                                                         .Target = 4,
                                                         .NumControls = 1,
                                                         .Control = {2},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L6[] = {{.Gate = X,
                                                         .Target = 0,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L7[] = {{.Gate = X,
                                                         .Target = 2,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_L8[] = {{.Gate = X,
                                                         .Target = 3,
                                                         .NumControls = 1,
                                                         .Control = {5},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CLIFFT_CLA_CQ_INC_2_LAYERS[] = {
    TOFFOLI_CLIFFT_CLA_CQ_INC_2_L0, TOFFOLI_CLIFFT_CLA_CQ_INC_2_L1, TOFFOLI_CLIFFT_CLA_CQ_INC_2_L2,
    TOFFOLI_CLIFFT_CLA_CQ_INC_2_L3, TOFFOLI_CLIFFT_CLA_CQ_INC_2_L4, TOFFOLI_CLIFFT_CLA_CQ_INC_2_L5,
    TOFFOLI_CLIFFT_CLA_CQ_INC_2_L6, TOFFOLI_CLIFFT_CLA_CQ_INC_2_L7, TOFFOLI_CLIFFT_CLA_CQ_INC_2_L8};
static const num_t TOFFOLI_CLIFFT_CLA_CQ_INC_2_GPL[] = {1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_CLIFFT_CLA_CQ_INC_2 = {
    .seq = (gate_t **)TOFFOLI_CLIFFT_CLA_CQ_INC_2_LAYERS,
    .num_layer = 9,
    .used_layer = 9,
    .gates_per_layer = (num_t *)TOFFOLI_CLIFFT_CLA_CQ_INC_2_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 2
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_2(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CLIFFT_CLA_CQ_INC_2;
}

#endif // TOFFOLI_SEQ_WIDTH_2
