//
// toffoli_clifft_cla_dispatch.c - Dispatch for BK CLA Clifford+T sequences
//
// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY
//
// Routes get_hardcoded_toffoli_clifft_cla_*() to per-width implementations.
// BK CLA requires bits >= 2, so no width-1 entries.
//

#include "toffoli_sequences.h"
#include <stddef.h>

// ============================================================================
// FORWARD DECLARATIONS - QQ add (conditionally compiled per width)
// ============================================================================

#ifdef TOFFOLI_SEQ_WIDTH_2
const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_2(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_3
const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_3(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_4
const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_4(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_5
const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_5(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_6
const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_6(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_7
const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_7(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_8
const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_8(int bits);
#endif

// ============================================================================
// FORWARD DECLARATIONS - cQQ add (conditionally compiled per width)
// ============================================================================

#ifdef TOFFOLI_SEQ_WIDTH_2
const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add_2(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_3
const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add_3(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_4
const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add_4(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_5
const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add_5(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_6
const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add_6(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_7
const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add_7(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_8
const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add_8(int bits);
#endif

// ============================================================================
// FORWARD DECLARATIONS - CQ increment (value=1) (conditionally compiled per width)
// ============================================================================

#ifdef TOFFOLI_SEQ_WIDTH_2
const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_2(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_3
const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_3(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_4
const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_4(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_5
const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_5(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_6
const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_6(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_7
const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_7(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_8
const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_8(int bits);
#endif

// ============================================================================
// FORWARD DECLARATIONS - cCQ increment (value=1) (conditionally compiled per width)
// ============================================================================

#ifdef TOFFOLI_SEQ_WIDTH_2
const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_2(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_3
const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_3(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_4
const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_4(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_5
const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_5(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_6
const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_6(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_7
const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_7(int bits);
#endif

#ifdef TOFFOLI_SEQ_WIDTH_8
const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_8(int bits);
#endif

// ============================================================================
// UNIFIED BK CLA CLIFFORD+T QQ ADD DISPATCH
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add(int bits) {
    switch (bits) {
#ifdef TOFFOLI_SEQ_WIDTH_2
    case 2:
        return get_hardcoded_toffoli_clifft_cla_QQ_add_2(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_3
    case 3:
        return get_hardcoded_toffoli_clifft_cla_QQ_add_3(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_4
    case 4:
        return get_hardcoded_toffoli_clifft_cla_QQ_add_4(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_5
    case 5:
        return get_hardcoded_toffoli_clifft_cla_QQ_add_5(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_6
    case 6:
        return get_hardcoded_toffoli_clifft_cla_QQ_add_6(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_7
    case 7:
        return get_hardcoded_toffoli_clifft_cla_QQ_add_7(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_8
    case 8:
        return get_hardcoded_toffoli_clifft_cla_QQ_add_8(bits);
#endif
    default:
        return NULL;
    }
}

// ============================================================================
// UNIFIED BK CLA CLIFFORD+T CQQ ADD DISPATCH
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add(int bits) {
    switch (bits) {
#ifdef TOFFOLI_SEQ_WIDTH_2
    case 2:
        return get_hardcoded_toffoli_clifft_cla_cQQ_add_2(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_3
    case 3:
        return get_hardcoded_toffoli_clifft_cla_cQQ_add_3(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_4
    case 4:
        return get_hardcoded_toffoli_clifft_cla_cQQ_add_4(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_5
    case 5:
        return get_hardcoded_toffoli_clifft_cla_cQQ_add_5(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_6
    case 6:
        return get_hardcoded_toffoli_clifft_cla_cQQ_add_6(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_7
    case 7:
        return get_hardcoded_toffoli_clifft_cla_cQQ_add_7(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_8
    case 8:
        return get_hardcoded_toffoli_clifft_cla_cQQ_add_8(bits);
#endif
    default:
        return NULL;
    }
}

// ============================================================================
// UNIFIED BK CLA CLIFFORD+T CQ INCREMENT (VALUE=1) DISPATCH
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc(int bits) {
    switch (bits) {
#ifdef TOFFOLI_SEQ_WIDTH_2
    case 2:
        return get_hardcoded_toffoli_clifft_cla_CQ_inc_2(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_3
    case 3:
        return get_hardcoded_toffoli_clifft_cla_CQ_inc_3(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_4
    case 4:
        return get_hardcoded_toffoli_clifft_cla_CQ_inc_4(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_5
    case 5:
        return get_hardcoded_toffoli_clifft_cla_CQ_inc_5(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_6
    case 6:
        return get_hardcoded_toffoli_clifft_cla_CQ_inc_6(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_7
    case 7:
        return get_hardcoded_toffoli_clifft_cla_CQ_inc_7(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_8
    case 8:
        return get_hardcoded_toffoli_clifft_cla_CQ_inc_8(bits);
#endif
    default:
        return NULL;
    }
}

// ============================================================================
// UNIFIED BK CLA CLIFFORD+T CCQ INCREMENT (VALUE=1) DISPATCH
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc(int bits) {
    switch (bits) {
#ifdef TOFFOLI_SEQ_WIDTH_2
    case 2:
        return get_hardcoded_toffoli_clifft_cla_cCQ_inc_2(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_3
    case 3:
        return get_hardcoded_toffoli_clifft_cla_cCQ_inc_3(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_4
    case 4:
        return get_hardcoded_toffoli_clifft_cla_cCQ_inc_4(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_5
    case 5:
        return get_hardcoded_toffoli_clifft_cla_cCQ_inc_5(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_6
    case 6:
        return get_hardcoded_toffoli_clifft_cla_cCQ_inc_6(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_7
    case 7:
        return get_hardcoded_toffoli_clifft_cla_cCQ_inc_7(bits);
#endif
#ifdef TOFFOLI_SEQ_WIDTH_8
    case 8:
        return get_hardcoded_toffoli_clifft_cla_cCQ_inc_8(bits);
#endif
    default:
        return NULL;
    }
}
