//
// toffoli_clifft_cla_cq_inc_4.c - BK CLA CQ increment Clifford+T for 4-bit width
//
// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY
//
// Contains: BK CLA CQ_inc (value=1) Clifford+T (static const, zero CCX)
// Algorithm: Brent-Kung CLA with temp-register CQ + classical-bit simplification + CCX->Clifford+T
// All gates are H/T/Tdg/CX/X (max 1 control) -- no dynamic allocation needed.
//

#include "toffoli_sequences.h"
#include <math.h>

#ifdef TOFFOLI_SEQ_WIDTH_4

// ============================================================================
// TOFFOLI CLIFFT CLA CQ_INC WIDTH 4 (133 Clifford+T layers)
// Source: 5 X + 8 CX + 8 CCX = 21 Toffoli gates
// Clifford+T: 8*15 + 8*1 + 5*1 = 133 gates
// Qubit layout: temp[0..3], self[4..7], g[8..10], tree/carry[11..15]
// All gates: H/T/Tdg/CX/X (zero CCX)
// ============================================================================

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L0[] = {{.Gate = X,
                                                         .Target = 0,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L1[] = {{.Gate = X,
                                                         .Target = 8,
                                                         .NumControls = 1,
                                                         .Control = {4},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L2[] = {{.Gate = X,
                                                         .Target = 4,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L3[] = {{.Gate = H,
                                                         .Target = 9,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = 0,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L4[] = {{.Gate = X,
                                                         .Target = 9,
                                                         .NumControls = 1,
                                                         .Control = {8},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L5[] = {{.Gate = TDG_GATE,
                                                         .Target = 9,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = -M_PI / 4.0,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L6[] = {{.Gate = X,
                                                         .Target = 9,
                                                         .NumControls = 1,
                                                         .Control = {5},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L7[] = {{.Gate = T_GATE,
                                                         .Target = 9,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = M_PI / 4.0,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L8[] = {{.Gate = X,
                                                         .Target = 9,
                                                         .NumControls = 1,
                                                         .Control = {8},
                                                         .large_control = NULL,
                                                         .GateValue = 1,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L9[] = {{.Gate = TDG_GATE,
                                                         .Target = 9,
                                                         .NumControls = 0,
                                                         .Control = {0},
                                                         .large_control = NULL,
                                                         .GateValue = -M_PI / 4.0,
                                                         .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L10[] = {{.Gate = X,
                                                          .Target = 9,
                                                          .NumControls = 1,
                                                          .Control = {5},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L11[] = {{.Gate = T_GATE,
                                                          .Target = 9,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L12[] = {{.Gate = T_GATE,
                                                          .Target = 8,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L13[] = {{.Gate = H,
                                                          .Target = 9,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L14[] = {{.Gate = X,
                                                          .Target = 8,
                                                          .NumControls = 1,
                                                          .Control = {5},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L15[] = {{.Gate = T_GATE,
                                                          .Target = 5,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L16[] = {{.Gate = TDG_GATE,
                                                          .Target = 8,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L17[] = {{.Gate = X,
                                                          .Target = 8,
                                                          .NumControls = 1,
                                                          .Control = {5},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L18[] = {{.Gate = H,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L19[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {4},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L20[] = {{.Gate = TDG_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L21[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {5},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L22[] = {{.Gate = T_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L23[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {4},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L24[] = {{.Gate = TDG_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L25[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {5},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L26[] = {{.Gate = T_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L27[] = {{.Gate = T_GATE,
                                                          .Target = 4,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L28[] = {{.Gate = H,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L29[] = {{.Gate = X,
                                                          .Target = 4,
                                                          .NumControls = 1,
                                                          .Control = {5},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L30[] = {{.Gate = T_GATE,
                                                          .Target = 5,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L31[] = {{.Gate = TDG_GATE,
                                                          .Target = 4,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L32[] = {{.Gate = X,
                                                          .Target = 4,
                                                          .NumControls = 1,
                                                          .Control = {5},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L33[] = {{.Gate = H,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L34[] = {{.Gate = X,
                                                          .Target = 10,
                                                          .NumControls = 1,
                                                          .Control = {9},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L35[] = {{.Gate = TDG_GATE,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L36[] = {{.Gate = X,
                                                          .Target = 10,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L37[] = {{.Gate = T_GATE,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L38[] = {{.Gate = X,
                                                          .Target = 10,
                                                          .NumControls = 1,
                                                          .Control = {9},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L39[] = {{.Gate = TDG_GATE,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L40[] = {{.Gate = X,
                                                          .Target = 10,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L41[] = {{.Gate = T_GATE,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L42[] = {{.Gate = T_GATE,
                                                          .Target = 9,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L43[] = {{.Gate = H,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L44[] = {{.Gate = X,
                                                          .Target = 9,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L45[] = {{.Gate = T_GATE,
                                                          .Target = 6,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L46[] = {{.Gate = TDG_GATE,
                                                          .Target = 9,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L47[] = {{.Gate = X,
                                                          .Target = 9,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L48[] = {{.Gate = H,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L49[] = {{.Gate = X,
                                                          .Target = 12,
                                                          .NumControls = 1,
                                                          .Control = {11},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L50[] = {{.Gate = TDG_GATE,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L51[] = {{.Gate = X,
                                                          .Target = 12,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L52[] = {{.Gate = T_GATE,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L53[] = {{.Gate = X,
                                                          .Target = 12,
                                                          .NumControls = 1,
                                                          .Control = {11},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L54[] = {{.Gate = TDG_GATE,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L55[] = {{.Gate = X,
                                                          .Target = 12,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L56[] = {{.Gate = T_GATE,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L57[] = {{.Gate = T_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L58[] = {{.Gate = H,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L59[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L60[] = {{.Gate = T_GATE,
                                                          .Target = 6,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L61[] = {{.Gate = TDG_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L62[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L63[] = {{.Gate = X,
                                                          .Target = 13,
                                                          .NumControls = 1,
                                                          .Control = {8},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L64[] = {{.Gate = X,
                                                          .Target = 14,
                                                          .NumControls = 1,
                                                          .Control = {9},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L65[] = {{.Gate = X,
                                                          .Target = 15,
                                                          .NumControls = 1,
                                                          .Control = {10},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L66[] = {{.Gate = H,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L67[] = {{.Gate = X,
                                                          .Target = 12,
                                                          .NumControls = 1,
                                                          .Control = {11},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L68[] = {{.Gate = TDG_GATE,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L69[] = {{.Gate = X,
                                                          .Target = 12,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L70[] = {{.Gate = T_GATE,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L71[] = {{.Gate = X,
                                                          .Target = 12,
                                                          .NumControls = 1,
                                                          .Control = {11},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L72[] = {{.Gate = TDG_GATE,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L73[] = {{.Gate = X,
                                                          .Target = 12,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L74[] = {{.Gate = T_GATE,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L75[] = {{.Gate = T_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L76[] = {{.Gate = H,
                                                          .Target = 12,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L77[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L78[] = {{.Gate = T_GATE,
                                                          .Target = 6,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L79[] = {{.Gate = TDG_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L80[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L81[] = {{.Gate = H,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L82[] = {{.Gate = X,
                                                          .Target = 10,
                                                          .NumControls = 1,
                                                          .Control = {9},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L83[] = {{.Gate = TDG_GATE,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L84[] = {{.Gate = X,
                                                          .Target = 10,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L85[] = {{.Gate = T_GATE,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L86[] = {{.Gate = X,
                                                          .Target = 10,
                                                          .NumControls = 1,
                                                          .Control = {9},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L87[] = {{.Gate = TDG_GATE,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L88[] = {{.Gate = X,
                                                          .Target = 10,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L89[] = {{.Gate = T_GATE,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L90[] = {{.Gate = T_GATE,
                                                          .Target = 9,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L91[] = {{.Gate = H,
                                                          .Target = 10,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L92[] = {{.Gate = X,
                                                          .Target = 9,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L93[] = {{.Gate = T_GATE,
                                                          .Target = 6,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L94[] = {{.Gate = TDG_GATE,
                                                          .Target = 9,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L95[] = {{.Gate = X,
                                                          .Target = 9,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L96[] = {{.Gate = H,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L97[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {4},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L98[] = {{.Gate = TDG_GATE,
                                                          .Target = 11,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L99[] = {{.Gate = X,
                                                          .Target = 11,
                                                          .NumControls = 1,
                                                          .Control = {5},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L100[] = {{.Gate = T_GATE,
                                                           .Target = 11,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L101[] = {{.Gate = X,
                                                           .Target = 11,
                                                           .NumControls = 1,
                                                           .Control = {4},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L102[] = {{.Gate = TDG_GATE,
                                                           .Target = 11,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L103[] = {{.Gate = X,
                                                           .Target = 11,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L104[] = {{.Gate = T_GATE,
                                                           .Target = 11,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L105[] = {{.Gate = T_GATE,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L106[] = {{.Gate = H,
                                                           .Target = 11,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L107[] = {{.Gate = X,
                                                           .Target = 4,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L108[] = {{.Gate = T_GATE,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L109[] = {{.Gate = TDG_GATE,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L110[] = {{.Gate = X,
                                                           .Target = 4,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L111[] = {{.Gate = H,
                                                           .Target = 9,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L112[] = {{.Gate = X,
                                                           .Target = 9,
                                                           .NumControls = 1,
                                                           .Control = {8},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L113[] = {{.Gate = TDG_GATE,
                                                           .Target = 9,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L114[] = {{.Gate = X,
                                                           .Target = 9,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L115[] = {{.Gate = T_GATE,
                                                           .Target = 9,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L116[] = {{.Gate = X,
                                                           .Target = 9,
                                                           .NumControls = 1,
                                                           .Control = {8},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L117[] = {{.Gate = TDG_GATE,
                                                           .Target = 9,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L118[] = {{.Gate = X,
                                                           .Target = 9,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L119[] = {{.Gate = T_GATE,
                                                           .Target = 9,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L120[] = {{.Gate = T_GATE,
                                                           .Target = 8,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L121[] = {{.Gate = H,
                                                           .Target = 9,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L122[] = {{.Gate = X,
                                                           .Target = 8,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L123[] = {{.Gate = T_GATE,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L124[] = {{.Gate = TDG_GATE,
                                                           .Target = 8,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L125[] = {{.Gate = X,
                                                           .Target = 8,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L126[] = {{.Gate = X,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L127[] = {{.Gate = X,
                                                           .Target = 8,
                                                           .NumControls = 1,
                                                           .Control = {4},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L128[] = {{.Gate = X,
                                                           .Target = 0,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L129[] = {{.Gate = X,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L130[] = {{.Gate = X,
                                                           .Target = 5,
                                                           .NumControls = 1,
                                                           .Control = {13},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L131[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {14},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_L132[] = {{.Gate = X,
                                                           .Target = 7,
                                                           .NumControls = 1,
                                                           .Control = {15},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CLIFFT_CLA_CQ_INC_4_LAYERS[] = {
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L0,   TOFFOLI_CLIFFT_CLA_CQ_INC_4_L1,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L2,   TOFFOLI_CLIFFT_CLA_CQ_INC_4_L3,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L4,   TOFFOLI_CLIFFT_CLA_CQ_INC_4_L5,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L6,   TOFFOLI_CLIFFT_CLA_CQ_INC_4_L7,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L8,   TOFFOLI_CLIFFT_CLA_CQ_INC_4_L9,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L10,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L11,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L12,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L13,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L14,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L15,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L16,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L17,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L18,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L19,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L20,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L21,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L22,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L23,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L24,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L25,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L26,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L27,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L28,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L29,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L30,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L31,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L32,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L33,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L34,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L35,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L36,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L37,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L38,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L39,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L40,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L41,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L42,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L43,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L44,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L45,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L46,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L47,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L48,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L49,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L50,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L51,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L52,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L53,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L54,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L55,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L56,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L57,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L58,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L59,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L60,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L61,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L62,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L63,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L64,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L65,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L66,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L67,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L68,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L69,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L70,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L71,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L72,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L73,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L74,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L75,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L76,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L77,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L78,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L79,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L80,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L81,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L82,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L83,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L84,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L85,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L86,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L87,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L88,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L89,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L90,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L91,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L92,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L93,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L94,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L95,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L96,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L97,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L98,  TOFFOLI_CLIFFT_CLA_CQ_INC_4_L99,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L100, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L101,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L102, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L103,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L104, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L105,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L106, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L107,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L108, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L109,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L110, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L111,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L112, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L113,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L114, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L115,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L116, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L117,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L118, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L119,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L120, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L121,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L122, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L123,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L124, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L125,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L126, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L127,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L128, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L129,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L130, TOFFOLI_CLIFFT_CLA_CQ_INC_4_L131,
    TOFFOLI_CLIFFT_CLA_CQ_INC_4_L132};
static const num_t TOFFOLI_CLIFFT_CLA_CQ_INC_4_GPL[] = {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_CLIFFT_CLA_CQ_INC_4 = {
    .seq = (gate_t **)TOFFOLI_CLIFFT_CLA_CQ_INC_4_LAYERS,
    .num_layer = 133,
    .used_layer = 133,
    .gates_per_layer = (num_t *)TOFFOLI_CLIFFT_CLA_CQ_INC_4_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 4
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_4(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CLIFFT_CLA_CQ_INC_4;
}

#endif // TOFFOLI_SEQ_WIDTH_4
