//
// toffoli_clifft_cla_qq_2.c - BK CLA QQ Clifford+T addition for 2-bit width
//
// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY
//
// Contains: BK CLA QQ_add Clifford+T (static const, zero CCX)
// Algorithm: Brent-Kung parallel prefix CLA with CCX->Clifford+T decomposition
// All gates are H/T/Tdg/CX/X (max 1 control) -- no dynamic allocation needed.
//

#include "toffoli_sequences.h"
#include <math.h>

#ifdef TOFFOLI_SEQ_WIDTH_2

// ============================================================================
// TOFFOLI CLIFFT CLA QQ WIDTH 2 (38 Clifford+T layers)
// Source: 0 X + 8 CX + 2 CCX = 10 Toffoli gates
// Clifford+T: 2*15 + 8*1 + 0*1 = 38 gates
// Qubit layout: a[0..1], b[2..3], g[4..4], tree_anc[5..5], carry[5..5]
// All gates: H/T/Tdg/CX/X (zero CCX)
// ============================================================================

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L0[] = {{.Gate = H,
                                                     .Target = 4,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = 0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L1[] = {{.Gate = X,
                                                     .Target = 4,
                                                     .NumControls = 1,
                                                     .Control = {2},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L2[] = {{.Gate = TDG_GATE,
                                                     .Target = 4,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = -M_PI / 4.0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L3[] = {{.Gate = X,
                                                     .Target = 4,
                                                     .NumControls = 1,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L4[] = {{.Gate = T_GATE,
                                                     .Target = 4,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = M_PI / 4.0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L5[] = {{.Gate = X,
                                                     .Target = 4,
                                                     .NumControls = 1,
                                                     .Control = {2},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L6[] = {{.Gate = TDG_GATE,
                                                     .Target = 4,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = -M_PI / 4.0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L7[] = {{.Gate = X,
                                                     .Target = 4,
                                                     .NumControls = 1,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L8[] = {{.Gate = T_GATE,
                                                     .Target = 4,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = M_PI / 4.0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L9[] = {{.Gate = T_GATE,
                                                     .Target = 2,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = M_PI / 4.0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L10[] = {{.Gate = H,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L11[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L12[] = {{.Gate = T_GATE,
                                                      .Target = 0,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L13[] = {{.Gate = TDG_GATE,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L14[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L15[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L16[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {1},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L17[] = {{.Gate = X,
                                                      .Target = 5,
                                                      .NumControls = 1,
                                                      .Control = {4},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L18[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {1},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L19[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L20[] = {{.Gate = H,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L21[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {2},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L22[] = {{.Gate = TDG_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L23[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L24[] = {{.Gate = T_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L25[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {2},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L26[] = {{.Gate = TDG_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L27[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L28[] = {{.Gate = T_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L29[] = {{.Gate = T_GATE,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L30[] = {{.Gate = H,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L31[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L32[] = {{.Gate = T_GATE,
                                                      .Target = 0,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L33[] = {{.Gate = TDG_GATE,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L34[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L35[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L36[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {1},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_QQ_2_L37[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {5},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CLIFFT_CLA_QQ_2_LAYERS[] = {
    TOFFOLI_CLIFFT_CLA_QQ_2_L0,  TOFFOLI_CLIFFT_CLA_QQ_2_L1,  TOFFOLI_CLIFFT_CLA_QQ_2_L2,
    TOFFOLI_CLIFFT_CLA_QQ_2_L3,  TOFFOLI_CLIFFT_CLA_QQ_2_L4,  TOFFOLI_CLIFFT_CLA_QQ_2_L5,
    TOFFOLI_CLIFFT_CLA_QQ_2_L6,  TOFFOLI_CLIFFT_CLA_QQ_2_L7,  TOFFOLI_CLIFFT_CLA_QQ_2_L8,
    TOFFOLI_CLIFFT_CLA_QQ_2_L9,  TOFFOLI_CLIFFT_CLA_QQ_2_L10, TOFFOLI_CLIFFT_CLA_QQ_2_L11,
    TOFFOLI_CLIFFT_CLA_QQ_2_L12, TOFFOLI_CLIFFT_CLA_QQ_2_L13, TOFFOLI_CLIFFT_CLA_QQ_2_L14,
    TOFFOLI_CLIFFT_CLA_QQ_2_L15, TOFFOLI_CLIFFT_CLA_QQ_2_L16, TOFFOLI_CLIFFT_CLA_QQ_2_L17,
    TOFFOLI_CLIFFT_CLA_QQ_2_L18, TOFFOLI_CLIFFT_CLA_QQ_2_L19, TOFFOLI_CLIFFT_CLA_QQ_2_L20,
    TOFFOLI_CLIFFT_CLA_QQ_2_L21, TOFFOLI_CLIFFT_CLA_QQ_2_L22, TOFFOLI_CLIFFT_CLA_QQ_2_L23,
    TOFFOLI_CLIFFT_CLA_QQ_2_L24, TOFFOLI_CLIFFT_CLA_QQ_2_L25, TOFFOLI_CLIFFT_CLA_QQ_2_L26,
    TOFFOLI_CLIFFT_CLA_QQ_2_L27, TOFFOLI_CLIFFT_CLA_QQ_2_L28, TOFFOLI_CLIFFT_CLA_QQ_2_L29,
    TOFFOLI_CLIFFT_CLA_QQ_2_L30, TOFFOLI_CLIFFT_CLA_QQ_2_L31, TOFFOLI_CLIFFT_CLA_QQ_2_L32,
    TOFFOLI_CLIFFT_CLA_QQ_2_L33, TOFFOLI_CLIFFT_CLA_QQ_2_L34, TOFFOLI_CLIFFT_CLA_QQ_2_L35,
    TOFFOLI_CLIFFT_CLA_QQ_2_L36, TOFFOLI_CLIFFT_CLA_QQ_2_L37};
static const num_t TOFFOLI_CLIFFT_CLA_QQ_2_GPL[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_CLIFFT_CLA_QQ_2 = {
    .seq = (gate_t **)TOFFOLI_CLIFFT_CLA_QQ_2_LAYERS,
    .num_layer = 38,
    .used_layer = 38,
    .gates_per_layer = (num_t *)TOFFOLI_CLIFFT_CLA_QQ_2_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 2
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_2(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CLIFFT_CLA_QQ_2;
}

#endif // TOFFOLI_SEQ_WIDTH_2
