//
// toffoli_clifft_cla_ccq_inc_2.c - BK CLA cCQ increment Clifford+T for 2-bit width
//
// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY
//
// Contains: BK CLA cCQ_inc (value=1) Clifford+T (static const, zero CCX)
// Algorithm: Brent-Kung CLA with controlled temp-register + AND-ancilla MCX decomp +
// CCX->Clifford+T All gates are H/T/Tdg/CX/X (max 1 control) -- no dynamic allocation needed.
//

#include "toffoli_sequences.h"
#include <math.h>

#ifdef TOFFOLI_SEQ_WIDTH_2

// ============================================================================
// TOFFOLI CLIFFT CLA cCQ_INC WIDTH 2 (65 Clifford+T layers)
// Source: 0 X + 5 CX + 4 CCX = 9 Toffoli gates
// Clifford+T: 4*15 + 5*1 + 0*1 = 65 gates
// Qubit layout: temp[0..1], self[2..3], ancilla, ext_ctrl=6, and_anc=7
// All gates: H/T/Tdg/CX/X (zero CCX)
// ============================================================================

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L0[] = {{.Gate = X,
                                                          .Target = 0,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L1[] = {{.Gate = H,
                                                          .Target = 4,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = 0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L2[] = {{.Gate = X,
                                                          .Target = 4,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L3[] = {{.Gate = TDG_GATE,
                                                          .Target = 4,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L4[] = {{.Gate = X,
                                                          .Target = 4,
                                                          .NumControls = 1,
                                                          .Control = {2},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L5[] = {{.Gate = T_GATE,
                                                          .Target = 4,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L6[] = {{.Gate = X,
                                                          .Target = 4,
                                                          .NumControls = 1,
                                                          .Control = {6},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L7[] = {{.Gate = TDG_GATE,
                                                          .Target = 4,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = -M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L8[] = {{.Gate = X,
                                                          .Target = 4,
                                                          .NumControls = 1,
                                                          .Control = {2},
                                                          .large_control = NULL,
                                                          .GateValue = 1,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L9[] = {{.Gate = T_GATE,
                                                          .Target = 4,
                                                          .NumControls = 0,
                                                          .Control = {0},
                                                          .large_control = NULL,
                                                          .GateValue = M_PI / 4.0,
                                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L10[] = {{.Gate = T_GATE,
                                                           .Target = 6,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L11[] = {{.Gate = H,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L12[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {2},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L13[] = {{.Gate = T_GATE,
                                                           .Target = 2,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L14[] = {{.Gate = TDG_GATE,
                                                           .Target = 6,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L15[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {2},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L16[] = {{.Gate = X,
                                                           .Target = 2,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L17[] = {{.Gate = H,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L18[] = {{.Gate = X,
                                                           .Target = 5,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L19[] = {{.Gate = TDG_GATE,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L20[] = {{.Gate = X,
                                                           .Target = 5,
                                                           .NumControls = 1,
                                                           .Control = {4},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L21[] = {{.Gate = T_GATE,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L22[] = {{.Gate = X,
                                                           .Target = 5,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L23[] = {{.Gate = TDG_GATE,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L24[] = {{.Gate = X,
                                                           .Target = 5,
                                                           .NumControls = 1,
                                                           .Control = {4},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L25[] = {{.Gate = T_GATE,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L26[] = {{.Gate = T_GATE,
                                                           .Target = 6,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L27[] = {{.Gate = H,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L28[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {4},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L29[] = {{.Gate = T_GATE,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L30[] = {{.Gate = TDG_GATE,
                                                           .Target = 6,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L31[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {4},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L32[] = {{.Gate = X,
                                                           .Target = 2,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L33[] = {{.Gate = H,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L34[] = {{.Gate = X,
                                                           .Target = 4,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L35[] = {{.Gate = TDG_GATE,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L36[] = {{.Gate = X,
                                                           .Target = 4,
                                                           .NumControls = 1,
                                                           .Control = {2},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L37[] = {{.Gate = T_GATE,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L38[] = {{.Gate = X,
                                                           .Target = 4,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L39[] = {{.Gate = TDG_GATE,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L40[] = {{.Gate = X,
                                                           .Target = 4,
                                                           .NumControls = 1,
                                                           .Control = {2},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L41[] = {{.Gate = T_GATE,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L42[] = {{.Gate = T_GATE,
                                                           .Target = 6,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L43[] = {{.Gate = H,
                                                           .Target = 4,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L44[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {2},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L45[] = {{.Gate = T_GATE,
                                                           .Target = 2,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L46[] = {{.Gate = TDG_GATE,
                                                           .Target = 6,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L47[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {2},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L48[] = {{.Gate = X,
                                                           .Target = 0,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L49[] = {{.Gate = X,
                                                           .Target = 2,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L50[] = {{.Gate = H,
                                                           .Target = 3,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L51[] = {{.Gate = X,
                                                           .Target = 3,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L52[] = {{.Gate = TDG_GATE,
                                                           .Target = 3,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L53[] = {{.Gate = X,
                                                           .Target = 3,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L54[] = {{.Gate = T_GATE,
                                                           .Target = 3,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L55[] = {{.Gate = X,
                                                           .Target = 3,
                                                           .NumControls = 1,
                                                           .Control = {6},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L56[] = {{.Gate = TDG_GATE,
                                                           .Target = 3,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L57[] = {{.Gate = X,
                                                           .Target = 3,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L58[] = {{.Gate = T_GATE,
                                                           .Target = 3,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L59[] = {{.Gate = T_GATE,
                                                           .Target = 6,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L60[] = {{.Gate = H,
                                                           .Target = 3,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = 0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L61[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L62[] = {{.Gate = T_GATE,
                                                           .Target = 5,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L63[] = {{.Gate = TDG_GATE,
                                                           .Target = 6,
                                                           .NumControls = 0,
                                                           .Control = {0},
                                                           .large_control = NULL,
                                                           .GateValue = -M_PI / 4.0,
                                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L64[] = {{.Gate = X,
                                                           .Target = 6,
                                                           .NumControls = 1,
                                                           .Control = {5},
                                                           .large_control = NULL,
                                                           .GateValue = 1,
                                                           .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CLIFFT_CLA_CCQ_INC_2_LAYERS[] = {
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L0,  TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L1,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L2,  TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L3,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L4,  TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L5,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L6,  TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L7,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L8,  TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L9,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L10, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L11,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L12, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L13,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L14, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L15,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L16, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L17,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L18, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L19,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L20, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L21,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L22, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L23,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L24, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L25,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L26, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L27,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L28, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L29,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L30, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L31,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L32, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L33,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L34, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L35,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L36, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L37,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L38, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L39,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L40, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L41,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L42, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L43,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L44, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L45,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L46, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L47,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L48, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L49,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L50, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L51,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L52, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L53,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L54, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L55,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L56, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L57,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L58, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L59,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L60, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L61,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L62, TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L63,
    TOFFOLI_CLIFFT_CLA_CCQ_INC_2_L64};
static const num_t TOFFOLI_CLIFFT_CLA_CCQ_INC_2_GPL[] = {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_CLIFFT_CLA_CCQ_INC_2 = {
    .seq = (gate_t **)TOFFOLI_CLIFFT_CLA_CCQ_INC_2_LAYERS,
    .num_layer = 65,
    .used_layer = 65,
    .gates_per_layer = (num_t *)TOFFOLI_CLIFFT_CLA_CCQ_INC_2_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 2
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_2(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CLIFFT_CLA_CCQ_INC_2;
}

#endif // TOFFOLI_SEQ_WIDTH_2
