#!/usr/bin/env python3
"""Unified generation script for all hardcoded addition sequences (widths 1-16).

This script generates per-width C source files (add_seq_N.c) and a unified dispatch
file (add_seq_dispatch.c) for the hardcoded sequence infrastructure.

It replaces the two earlier scripts:
  - generate_seq_1_4.py (DEPRECATED - kept for reference only)
  - generate_seq_5_8.py (DEPRECATED - kept for reference only)

Generated files contain four addition variants per width:
  - QQ_add:  Quantum-quantum addition (static const sequence)
  - cQQ_add: Controlled quantum-quantum addition (static const sequence)
  - CQ_add:  Classical-quantum addition template (init function with placeholder angles)
  - cCQ_add: Controlled classical-quantum addition template (init function with placeholder angles)

Usage:
  python scripts/generate_seq_all.py                     # Generate all 16 per-width files + dispatch
  python scripts/generate_seq_all.py --width 5           # Generate only add_seq_5.c
  python scripts/generate_seq_all.py --dry-run            # Print to stdout, don't write files
  python scripts/generate_seq_all.py --dry-run --width 8  # Print width 8 to stdout
  python scripts/generate_seq_all.py --validate           # Cross-validate against expected layer counts
  python scripts/generate_seq_all.py --output-dir /tmp    # Write to custom directory

CRITICAL: cQQ_add Block 2 uses bits+bit (b-register qubit) as control for negative
half-rotations, NOT the external control qubit. This is the fix from quick-015 (c891a32).

Generated by: scripts/generate_seq_all.py
"""

import argparse
import math
import os
import sys
from dataclasses import dataclass

# ============================================================================
# Gate dataclass - exact copy from existing generate_seq_5_8.py
# ============================================================================


@dataclass
class Gate:
    gate_type: str  # H, P, X
    target: int
    control: int | None
    value: float

    def to_c(self) -> str:
        if self.gate_type == "H":
            return f"""{{.Gate = H,
                                      .Target = {self.target},
                                      .NumControls = 0,
                                      .Control = {{0}},
                                      .large_control = NULL,
                                      .GateValue = 0,
                                      .NumBasisGates = 0}}"""
        elif self.gate_type == "P":
            return f"""{{.Gate = P,
                                      .Target = {self.target},
                                      .NumControls = 1,
                                      .Control = {{{self.control}}},
                                      .large_control = NULL,
                                      .GateValue = {self.format_angle()},
                                      .NumBasisGates = 0}}"""
        elif self.gate_type == "X":
            return f"""{{.Gate = X,
                                      .Target = {self.target},
                                      .NumControls = 1,
                                      .Control = {{{self.control}}},
                                      .large_control = NULL,
                                      .GateValue = 1,
                                      .NumBasisGates = 0}}"""

    def format_angle(self) -> str:
        """Format angle as SEQ_PI expression."""
        if self.value == 0:
            return "0"

        # Try to express as simple fraction of PI
        ratio = self.value / math.pi

        # Check common fractions
        for denom in [1, 2, 4, 8, 16, 32, 64, 128, 256]:
            for numer in range(-denom * 2, denom * 2 + 1):
                if numer == 0:
                    continue
                if abs(ratio - numer / denom) < 1e-10:
                    if numer == 1 and denom == 1:
                        return "SEQ_PI"
                    elif numer == -1 and denom == 1:
                        return "-SEQ_PI"
                    elif numer == 1:
                        return f"SEQ_PI / {denom}"
                    elif numer == -1:
                        return f"-SEQ_PI / {denom}"
                    elif denom == 1:
                        return f"{numer} * SEQ_PI"
                    else:
                        return f"{numer} * SEQ_PI / {denom}"

        # Fallback to decimal
        return f"{self.value}"


# ============================================================================
# QQ_add generation - exact copy from existing generate_seq_5_8.py
# ============================================================================


def generate_qq_add(bits: int) -> list[list[Gate]]:
    """Generate QQ_add gate sequence matching IntegerAddition.c dynamic generation."""
    layers = []

    # QFT on target register [0, bits-1]
    # MSB-first processing (textbook QFT without swaps)
    for target in range(bits - 1, -1, -1):
        # H gate
        layers.append([Gate("H", target, None, 0)])

        # Controlled phase rotations from lower target bits
        for ctrl in range(target - 1, -1, -1):
            angle = math.pi / (2 ** (target - ctrl))
            layers.append([Gate("P", target, ctrl, angle)])

    # Addition phase: controlled rotations from control register [bits, 2*bits-1]
    rounds = 0
    for bit in range(bits - 1, -1, -1):
        for i in range(bits - rounds):
            target = rounds + i
            control = bits + (bits - 1 - bit)  # = 2*bits - 1 - bit
            value = 2 * math.pi / (2 ** (i + 1))
            layers.append([Gate("P", target, control, value)])
        rounds += 1

    # Inverse QFT on target register
    for target in range(bits):
        # Inverse controlled phase rotations
        for ctrl in range(target):
            angle = -math.pi / (2 ** (target - ctrl))
            layers.append([Gate("P", target, ctrl, angle)])
        # H gate
        layers.append([Gate("H", target, None, 0)])

    return layers


# ============================================================================
# cQQ_add generation - exact copy from existing generate_seq_5_8.py
# Includes quick-015 fix: Block 2 uses bits+bit as control (NOT external control)
# ============================================================================


def generate_cqq_add(bits: int) -> list[list[Gate]]:
    """Generate cQQ_add gate sequence matching IntegerAddition.c dynamic generation."""
    layers = []
    control = 2 * bits  # Conditional control qubit (immediately after both operands)

    # QFT on target register [0, bits-1]
    for target in range(bits - 1, -1, -1):
        layers.append([Gate("H", target, None, 0)])
        for ctrl in range(target - 1, -1, -1):
            angle = math.pi / (2 ** (target - ctrl))
            layers.append([Gate("P", target, ctrl, angle)])

    # Block 1: unconditional half-rotations on Fourier qubits
    for bit in range(bits - 1, -1, -1):
        target_q = bits - 1 - bit  # reversed for textbook QFT
        value = 0
        for i in range(bits - bit):
            value += 2 * math.pi / (2 ** (i + 1)) / 2
        layers.append([Gate("P", target_q, control, value)])

    # Block 2: CNOT + negative half-rotations + CNOT
    # CRITICAL (quick-015 fix): negative half-rotations use bits+bit (b-register qubit)
    # as control, NOT the external control qubit
    rounds = 0
    for bit in range(bits - 1, -1, -1):
        # CNOT
        layers.append([Gate("X", bits + bit, control, 1)])
        # Negative half-rotations
        for i in range(bits - rounds):
            value = 2 * math.pi / (2 ** (i + 1)) / 2
            target_q = rounds + i
            layers.append([Gate("P", target_q, bits + bit, -value)])
        # CNOT
        layers.append([Gate("X", bits + bit, control, 1)])
        rounds += 1

    # Block 3: controlled rotations from b register
    # These can be parallelized
    rounds = 0
    for bit in range(bits - 1, -1, -1):
        parallel_gates = []
        for i in range(bits - rounds):
            value = 2 * math.pi / (2 ** (i + 1)) / 2
            target_q = rounds + i
            parallel_gates.append(Gate("P", target_q, bits + bit, value))
        layers.append(parallel_gates)
        rounds += 1

    # Inverse QFT on target register
    for target in range(bits):
        for ctrl in range(target):
            angle = -math.pi / (2 ** (target - ctrl))
            layers.append([Gate("P", target, ctrl, angle)])
        layers.append([Gate("H", target, None, 0)])

    return layers


# ============================================================================
# Layer optimization - exact copy from existing generate_seq_5_8.py
# ============================================================================


def optimize_layers(layers: list[list[Gate]]) -> list[list[Gate]]:
    """Merge consecutive layers with non-overlapping qubits."""
    if not layers:
        return layers

    optimized = []
    current = list(layers[0])
    current_qubits = set()
    for g in current:
        current_qubits.add(g.target)
        if g.control is not None:
            current_qubits.add(g.control)

    for layer in layers[1:]:
        layer_qubits = set()
        for g in layer:
            layer_qubits.add(g.target)
            if g.control is not None:
                layer_qubits.add(g.control)

        # Can merge if no qubit overlap
        if not current_qubits & layer_qubits:
            current.extend(layer)
            current_qubits.update(layer_qubits)
        else:
            optimized.append(current)
            current = list(layer)
            current_qubits = layer_qubits

    optimized.append(current)
    return optimized


# ============================================================================
# C sequence generation - exact copy from existing generate_seq_5_8.py
# ============================================================================


def generate_c_sequence(name: str, layers: list[list[Gate]], width: int) -> str:
    """Generate C code for a static const sequence."""
    lines = []

    # Generate layer arrays
    for i, layer in enumerate(layers):
        gates_str = ",\n                                     ".join(g.to_c() for g in layer)
        lines.append(f"static const gate_t {name}_{width}_L{i}[] = {{{gates_str}}};")
        lines.append("")

    # Generate layers array
    layer_names = ", ".join(f"{name}_{width}_L{i}" for i in range(len(layers)))
    # Split long lines
    if len(layers) > 6:
        layer_chunks = [layers[i : i + 6] for i in range(0, len(layers), 6)]
        layer_lines = []
        for chunk_idx, chunk in enumerate(layer_chunks):
            start_idx = chunk_idx * 6
            chunk_names = ", ".join(f"{name}_{width}_L{start_idx + i}" for i in range(len(chunk)))
            layer_lines.append(f"    {chunk_names}")
        layers_str = ",\n".join(layer_lines)
        lines.append(f"static const gate_t *{name}_{width}_LAYERS[] = {{\n{layers_str}}};")
    else:
        lines.append(f"static const gate_t *{name}_{width}_LAYERS[] = {{{layer_names}}};")

    # Generate gates per layer array
    gpl = [len(layer) for layer in layers]
    gpl_str = ", ".join(str(g) for g in gpl)
    if len(gpl) > 20:
        gpl_chunks = [gpl[i : i + 20] for i in range(0, len(gpl), 20)]
        gpl_lines = [", ".join(str(g) for g in chunk) for chunk in gpl_chunks]
        gpl_str = ",\n                                      ".join(gpl_lines)
    lines.append(f"static const num_t {name}_{width}_GPL[] = {{{gpl_str}}};")
    lines.append("")

    # Generate sequence struct
    lines.append(
        f"static const sequence_t HARDCODED_{name}_{width} = {{.seq = (gate_t **){name}_{width}_LAYERS,"
    )
    lines.append(f"                                              .num_layer = {len(layers)},")
    lines.append(f"                                              .used_layer = {len(layers)},")
    lines.append(
        f"                                              .gates_per_layer = (num_t *){name}_{width}_GPL}};"
    )

    return "\n".join(lines)


# ============================================================================
# CQ_add template-init generation (NEW)
# ============================================================================


def _generate_qft_layers(bits: int) -> list[list[Gate]]:
    """Generate QFT layers matching the C QFT() function layout.

    The C QFT() produces exactly 2*bits-1 layers with gate packing:
    For j=0..n-1, qubit q=n-1-j:
      - H(q) placed at layer 2*j
      - CP(q, q-i-1, pi/2^(i+1)) placed at layer 2*j+i+1 for i=0..n-2-j

    Multiple gates can share the same layer when they operate on independent qubits.
    """
    n = bits
    total = 2 * n - 1
    layers: list[list[Gate]] = [[] for _ in range(total)]

    for j in range(n):
        q = n - 1 - j
        layers[2 * j].append(Gate("H", q, None, 0))
        for i in range(n - 1 - j):
            angle = math.pi / (2 ** (i + 1))
            layers[2 * j + i + 1].append(Gate("P", q, q - i - 1, angle))

    return layers


def _generate_iqft_layers(bits: int) -> list[list[Gate]]:
    """Generate inverse QFT layers matching the C QFT_inverse() function layout.

    The C QFT_inverse() produces exactly 2*bits-1 layers (reverse of QFT).
    For j=0..n-1, qubit q=n-1-j:
      - CP(q, q-i-1, -pi/2^(i+1)) at layer (2*n-1) - (2*j+i+1) - 1
      - H(q) at layer (2*n-1) - 2*j - 1
    """
    n = bits
    total = 2 * n - 1
    layers: list[list[Gate]] = [[] for _ in range(total)]

    for j in range(n):
        q = n - 1 - j
        for i in range(n - 1 - j):
            layer_idx = total - (2 * j + i + 1) - 1
            angle = -math.pi / (2 ** (i + 1))
            layers[layer_idx].append(Gate("P", q, q - i - 1, angle))
        h_layer = total - 2 * j - 1
        layers[h_layer].append(Gate("H", q, None, 0))

    return layers


def generate_cq_add_template_layers(bits: int) -> list[list[Gate]]:
    """Return the gate structure for CQ_add template matching C QFT layout.

    Structure:
      - QFT on target register [0, bits-1] (2*bits-1 layers, matching C QFT())
      - bits rotation layers: each has one P gate on qubit i with angle placeholder 0
      - Inverse QFT on target register (2*bits-1 layers, matching C QFT_inverse())
      - Total layers: 5 * bits - 2
    """
    layers = []

    # QFT section (2*bits-1 layers)
    layers.extend(_generate_qft_layers(bits))

    # Rotation layers: one P gate per qubit with placeholder angle 0
    for i in range(bits):
        layers.append([Gate("P", i, None, 0)])  # Uncontrolled P (angle injected at runtime)

    # IQFT section (2*bits-1 layers)
    layers.extend(_generate_iqft_layers(bits))

    return layers


def _generate_gate_literal(gate: Gate, is_rotation_placeholder: bool = False) -> str:
    """Generate a (gate_t) compound literal for use in init functions."""
    if gate.gate_type == "H":
        return (
            f"(gate_t){{.Gate = H, .Target = {gate.target}, .NumControls = 0, "
            f".Control = {{0}}, .large_control = NULL, .GateValue = 0, .NumBasisGates = 0}}"
        )
    elif gate.gate_type == "P":
        if gate.control is not None:
            # Controlled P (CP gate)
            angle_str = "0" if is_rotation_placeholder else gate.format_angle()
            return (
                f"(gate_t){{.Gate = P, .Target = {gate.target}, .NumControls = 1, "
                f".Control = {{{gate.control}}}, .large_control = NULL, "
                f".GateValue = {angle_str}, .NumBasisGates = 0}}"
            )
        else:
            # Uncontrolled P gate (rotation placeholder in CQ_add template)
            return (
                f"(gate_t){{.Gate = P, .Target = {gate.target}, .NumControls = 0, "
                f".Control = {{0}}, .large_control = NULL, .GateValue = 0, .NumBasisGates = 0}}"
            )


def generate_cq_add_template_c(bits: int) -> str:
    """Generate C function init_hardcoded_CQ_add_N() for template-init pattern.

    The template pre-allocates the full sequence structure. QFT and IQFT gates have
    fixed angles. Rotation layers get GateValue = 0 (placeholder -- caller injects angles).
    """
    layers = generate_cq_add_template_layers(bits)
    n = bits
    total_layers = len(layers)
    qft_layers = 2 * bits - 1  # Number of QFT layers
    rotation_start = qft_layers
    rotation_end = rotation_start + bits

    lines = []
    lines.append(f"static sequence_t *cached_CQ_add_{n} = NULL;")
    lines.append("")
    lines.append(f"sequence_t *init_hardcoded_CQ_add_{n}(void) {{")
    lines.append(f"    if (cached_CQ_add_{n} != NULL) return cached_CQ_add_{n};")
    lines.append("")
    lines.append("    sequence_t *seq = malloc(sizeof(sequence_t));")
    lines.append("    if (seq == NULL) return NULL;")
    lines.append(f"    seq->num_layer = {total_layers};")
    lines.append(f"    seq->used_layer = {total_layers};")
    lines.append(f"    seq->gates_per_layer = calloc({total_layers}, sizeof(num_t));")
    lines.append(f"    seq->seq = calloc({total_layers}, sizeof(gate_t *));")
    lines.append("    if (seq->gates_per_layer == NULL || seq->seq == NULL) {")
    lines.append("        free(seq->gates_per_layer); free(seq->seq); free(seq); return NULL;")
    lines.append("    }")

    for i, layer in enumerate(layers):
        num_gates = len(layer)
        lines.append(f"    // Layer {i}")
        lines.append(f"    seq->gates_per_layer[{i}] = {num_gates};")
        lines.append(f"    seq->seq[{i}] = calloc({num_gates}, sizeof(gate_t));")
        is_rotation = rotation_start <= i < rotation_end
        for j, gate in enumerate(layer):
            literal = _generate_gate_literal(gate, is_rotation_placeholder=is_rotation)
            lines.append(f"    seq->seq[{i}][{j}] = {literal};")

    lines.append(f"    cached_CQ_add_{n} = seq;")
    lines.append("    return seq;")
    lines.append("}")

    return "\n".join(lines)


# ============================================================================
# cCQ_add template-init generation (NEW)
# ============================================================================


def generate_ccq_add_template_layers(bits: int) -> list[list[Gate]]:
    """Return the gate structure for cCQ_add template matching C QFT layout.

    Structure:
      - QFT on target register [0, bits-1] (2*bits-1 layers, matching C QFT())
      - bits rotation layers: each has one CP gate on qubit i with control=bits and angle 0
      - Inverse QFT on target register (2*bits-1 layers, matching C QFT_inverse())
      - Total layers: 5 * bits - 2
    """
    layers = []

    # QFT section (2*bits-1 layers)
    layers.extend(_generate_qft_layers(bits))

    # Rotation layers: one CP gate per qubit with control at qubit[bits] and placeholder angle 0
    for i in range(bits):
        layers.append([Gate("P", i, bits, 0)])  # CP with control = bits

    # IQFT section (2*bits-1 layers)
    layers.extend(_generate_iqft_layers(bits))

    return layers


def generate_ccq_add_template_c(bits: int) -> str:
    """Generate C function init_hardcoded_cCQ_add_N() for template-init pattern.

    Same pattern as CQ_add but rotation gates are CP (controlled phase) with
    .NumControls = 1, .Control = {bits}.
    """
    layers = generate_ccq_add_template_layers(bits)
    n = bits
    total_layers = len(layers)
    qft_layers = 2 * bits - 1
    rotation_start = qft_layers
    rotation_end = rotation_start + bits

    lines = []
    lines.append(f"static sequence_t *cached_cCQ_add_{n} = NULL;")
    lines.append("")
    lines.append(f"sequence_t *init_hardcoded_cCQ_add_{n}(void) {{")
    lines.append(f"    if (cached_cCQ_add_{n} != NULL) return cached_cCQ_add_{n};")
    lines.append("")
    lines.append("    sequence_t *seq = malloc(sizeof(sequence_t));")
    lines.append("    if (seq == NULL) return NULL;")
    lines.append(f"    seq->num_layer = {total_layers};")
    lines.append(f"    seq->used_layer = {total_layers};")
    lines.append(f"    seq->gates_per_layer = calloc({total_layers}, sizeof(num_t));")
    lines.append(f"    seq->seq = calloc({total_layers}, sizeof(gate_t *));")
    lines.append("    if (seq->gates_per_layer == NULL || seq->seq == NULL) {")
    lines.append("        free(seq->gates_per_layer); free(seq->seq); free(seq); return NULL;")
    lines.append("    }")

    for i, layer in enumerate(layers):
        num_gates = len(layer)
        lines.append(f"    // Layer {i}")
        lines.append(f"    seq->gates_per_layer[{i}] = {num_gates};")
        lines.append(f"    seq->seq[{i}] = calloc({num_gates}, sizeof(gate_t));")
        is_rotation = rotation_start <= i < rotation_end
        for j, gate in enumerate(layer):
            literal = _generate_gate_literal(gate, is_rotation_placeholder=is_rotation)
            lines.append(f"    seq->seq[{i}][{j}] = {literal};")

    lines.append(f"    cached_cCQ_add_{n} = seq;")
    lines.append("    return seq;")
    lines.append("}")

    return "\n".join(lines)


# ============================================================================
# Per-width file generation
# ============================================================================


def generate_width_file(width: int) -> str:
    """Generate complete C source file for one width."""
    output = []

    # Header
    output.append("//")
    output.append(f"// add_seq_{width}.c - Hardcoded addition sequences for {width}-bit width")
    output.append("//")
    output.append("// Generated by scripts/generate_seq_all.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Contains: QQ_add, cQQ_add (static const), CQ_add, cCQ_add (template-init)")
    output.append("//")
    output.append("")
    output.append('#include "sequences.h"')
    output.append("")
    output.append(f"#ifdef SEQ_WIDTH_{width}")
    output.append("")
    output.append("#include <stdlib.h>")
    output.append("")
    output.append("// SEQ_PI as compile-time constant for static initializers")
    output.append("// (math.h M_PI is not a constant expression in standard C)")
    output.append("#ifndef SEQ_PI")
    output.append("#define SEQ_PI 3.14159265358979323846")
    output.append("#endif")
    output.append("")

    # QQ_ADD section
    qq_layers = generate_qq_add(width)
    qq_layers = optimize_layers(qq_layers)
    output.append("// ============================================================================")
    output.append(f"// QQ_ADD WIDTH {width} ({len(qq_layers)} layers)")
    output.append(f"// Qubit layout: [0,{width - 1}] = target, [{width},{2 * width - 1}] = control")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_c_sequence("QQ_ADD", qq_layers, width))
    output.append("")

    # cQQ_ADD section
    cqq_layers = generate_cqq_add(width)
    cqq_layers = optimize_layers(cqq_layers)
    control_qubit = 2 * width
    output.append("// ============================================================================")
    output.append(f"// cQQ_ADD WIDTH {width} ({len(cqq_layers)} layers)")
    output.append(
        f"// Qubit layout: [0,{width - 1}] = target, [{width},{2 * width - 1}] = b, "
        f"[{control_qubit}] = control"
    )
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_c_sequence("cQQ_ADD", cqq_layers, width))
    output.append("")

    # CQ_ADD template-init section
    cq_layers = generate_cq_add_template_layers(width)
    output.append("// ============================================================================")
    output.append(f"// CQ_ADD WIDTH {width} (template-init, {len(cq_layers)} layers)")
    output.append(f"// Qubit layout: [0,{width - 1}] = target, classical value injected at runtime")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_cq_add_template_c(width))
    output.append("")

    # cCQ_ADD template-init section
    ccq_layers = generate_ccq_add_template_layers(width)
    output.append("// ============================================================================")
    output.append(f"// cCQ_ADD WIDTH {width} (template-init, {len(ccq_layers)} layers)")
    output.append(
        f"// Qubit layout: [0,{width - 1}] = target, [{width}] = control, "
        f"classical value injected at runtime"
    )
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_ccq_add_template_c(width))
    output.append("")

    # Per-width dispatch helpers
    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPERS FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_QQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_QQ_ADD_{width};")
    output.append("}")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_cQQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_cQQ_ADD_{width};")
    output.append("}")
    output.append("")
    output.append(f"sequence_t *get_hardcoded_CQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return init_hardcoded_CQ_add_{width}();")
    output.append("}")
    output.append("")
    output.append(f"sequence_t *get_hardcoded_cCQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return init_hardcoded_cCQ_add_{width}();")
    output.append("}")
    output.append("")

    output.append(f"#endif // SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Dispatch file generation
# ============================================================================


def generate_dispatch_file(max_width: int = 16) -> str:
    """Generate add_seq_dispatch.c with unified dispatch functions."""
    output = []

    # Header
    output.append("//")
    output.append("// add_seq_dispatch.c - Unified dispatch for hardcoded addition sequences")
    output.append("//")
    output.append("// Generated by scripts/generate_seq_all.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Routes get_hardcoded_*_add(bits) calls to per-width implementations.")
    output.append("// Each per-width file is conditionally compiled via #ifdef SEQ_WIDTH_N.")
    output.append("//")
    output.append("")
    output.append('#include "sequences.h"')
    output.append("#include <stddef.h>")
    output.append("")

    # Forward declarations for per-width helpers
    output.append("// ============================================================================")
    output.append("// FORWARD DECLARATIONS (conditionally compiled per width)")
    output.append("// ============================================================================")
    output.append("")

    for w in range(1, max_width + 1):
        output.append(f"#ifdef SEQ_WIDTH_{w}")
        output.append(f"const sequence_t *get_hardcoded_QQ_add_{w}(int bits);")
        output.append(f"const sequence_t *get_hardcoded_cQQ_add_{w}(int bits);")
        output.append(f"sequence_t *get_hardcoded_CQ_add_{w}(int bits);")
        output.append(f"sequence_t *get_hardcoded_cCQ_add_{w}(int bits);")
        output.append("#endif")
        output.append("")

    # QQ_add dispatch
    output.append("// ============================================================================")
    output.append("// UNIFIED QQ_add DISPATCH")
    output.append("// ============================================================================")
    output.append("")
    output.append("const sequence_t *get_hardcoded_QQ_add(int bits) {")
    output.append("    switch (bits) {")
    for w in range(1, max_width + 1):
        output.append(f"#ifdef SEQ_WIDTH_{w}")
        output.append(f"    case {w}: return get_hardcoded_QQ_add_{w}(bits);")
        output.append("#endif")
    output.append("    default: return NULL;")
    output.append("    }")
    output.append("}")
    output.append("")

    # cQQ_add dispatch
    output.append("// ============================================================================")
    output.append("// UNIFIED cQQ_add DISPATCH")
    output.append("// ============================================================================")
    output.append("")
    output.append("const sequence_t *get_hardcoded_cQQ_add(int bits) {")
    output.append("    switch (bits) {")
    for w in range(1, max_width + 1):
        output.append(f"#ifdef SEQ_WIDTH_{w}")
        output.append(f"    case {w}: return get_hardcoded_cQQ_add_{w}(bits);")
        output.append("#endif")
    output.append("    default: return NULL;")
    output.append("    }")
    output.append("}")
    output.append("")

    # CQ_add dispatch (mutable return for angle injection)
    output.append("// ============================================================================")
    output.append("// UNIFIED CQ_add DISPATCH (mutable return for angle injection)")
    output.append("// ============================================================================")
    output.append("")
    output.append("sequence_t *get_hardcoded_CQ_add(int bits) {")
    output.append("    switch (bits) {")
    for w in range(1, max_width + 1):
        output.append(f"#ifdef SEQ_WIDTH_{w}")
        output.append(f"    case {w}: return get_hardcoded_CQ_add_{w}(bits);")
        output.append("#endif")
    output.append("    default: return NULL;")
    output.append("    }")
    output.append("}")
    output.append("")

    # cCQ_add dispatch (mutable return for angle injection)
    output.append("// ============================================================================")
    output.append("// UNIFIED cCQ_add DISPATCH (mutable return for angle injection)")
    output.append("// ============================================================================")
    output.append("")
    output.append("sequence_t *get_hardcoded_cCQ_add(int bits) {")
    output.append("    switch (bits) {")
    for w in range(1, max_width + 1):
        output.append(f"#ifdef SEQ_WIDTH_{w}")
        output.append(f"    case {w}: return get_hardcoded_cCQ_add_{w}(bits);")
        output.append("#endif")
    output.append("    default: return NULL;")
    output.append("    }")
    output.append("}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Validation
# ============================================================================


def validate(max_width: int = 8) -> bool:
    """Cross-validate script output against expected layer counts for widths 1-8."""

    # Expected layer counts from existing generated C files (verified reference)
    expected_qq = {1: 3, 2: 8, 3: 14, 4: 23, 5: 35, 6: 50, 7: 68, 8: 89}
    expected_cqq = {1: 7, 2: 15, 3: 26, 4: 40, 5: 57, 6: 77, 7: 100, 8: 126}

    all_ok = True

    print("=" * 60)
    print("QQ_add layer count validation (widths 1-8)")
    print("=" * 60)
    for w in range(1, max_width + 1):
        layers = optimize_layers(generate_qq_add(w))
        actual = len(layers)
        expected = expected_qq[w]
        gate_count = sum(len(layer) for layer in layers)
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(
            f"  width {w:2d}: {actual:4d} layers ({gate_count:4d} gates)  expected {expected:4d}  [{status}]"
        )

    print()
    print("=" * 60)
    print("cQQ_add layer count validation (widths 1-8)")
    print("=" * 60)
    for w in range(1, max_width + 1):
        layers = optimize_layers(generate_cqq_add(w))
        actual = len(layers)
        expected = expected_cqq[w]
        gate_count = sum(len(layer) for layer in layers)
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(
            f"  width {w:2d}: {actual:4d} layers ({gate_count:4d} gates)  expected {expected:4d}  [{status}]"
        )

    print()
    print("=" * 60)
    print("CQ_add template layer count validation (widths 1-16)")
    print("=" * 60)
    for w in range(1, 17):
        layers = generate_cq_add_template_layers(w)
        actual = len(layers)
        expected = 5 * w - 2
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(f"  width {w:2d}: {actual:4d} layers  expected {expected:4d} (5*{w}-2)  [{status}]")

    print()
    print("=" * 60)
    print("cCQ_add template layer count validation (widths 1-16)")
    print("=" * 60)
    for w in range(1, 17):
        layers = generate_ccq_add_template_layers(w)
        actual = len(layers)
        expected = 5 * w - 2
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(f"  width {w:2d}: {actual:4d} layers  expected {expected:4d} (5*{w}-2)  [{status}]")

    # Verify cQQ_add Block 2 uses bits+bit as control (not external control)
    print()
    print("=" * 60)
    print("cQQ_add Block 2 control verification")
    print("=" * 60)
    for w in range(1, max_width + 1):
        layers = generate_cqq_add(w)  # Unoptimized to inspect structure
        control = 2 * w
        # Find Block 2 negative half-rotation gates (between CNOTs)
        # Block 2 starts after QFT + Block 1
        qft_count = sum(1 + max(0, t) for t in range(w - 1, -1, -1))
        block1_count = w
        block2_start = qft_count + block1_count
        # Check that negative rotations use bits+bit, not control
        block2_ok = True
        for bit in range(w - 1, -1, -1):  # noqa: B007
            # Skip CNOT, check rotation gates, skip CNOT
            # In unoptimized layers, we look at each P gate in Block 2
            for layer in layers[block2_start:]:
                for g in layer:
                    if g.gate_type == "P" and g.value < 0:
                        if g.control == control:
                            block2_ok = False
                            print(
                                f"  width {w}: FAIL - Block 2 uses external control {control} for negative rotation"
                            )
                            break
        if block2_ok:
            print(f"  width {w}: OK - Block 2 uses b-register qubit as control")

    print()
    if all_ok:
        print("ALL VALIDATIONS PASSED")
    else:
        print("VALIDATION FAILED - see mismatches above")

    return all_ok


# ============================================================================
# CLI entry point
# ============================================================================


def main():
    parser = argparse.ArgumentParser(
        description="Generate hardcoded addition sequence C files for widths 1-16."
    )
    parser.add_argument(
        "--width", type=int, metavar="N", help="Generate only for width N (default: all 1-16)"
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print to stdout instead of writing files"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory (default: c_backend/src/sequences/)",
    )
    parser.add_argument(
        "--validate", action="store_true", help="Cross-validate against expected layer counts"
    )
    parser.add_argument(
        "--max-width", type=int, default=16, help="Maximum width to generate (default: 16)"
    )

    args = parser.parse_args()

    if args.validate:
        ok = validate()
        sys.exit(0 if ok else 1)

    # Determine output directory
    if args.output_dir:
        output_dir = args.output_dir
    else:
        # Default: relative to script location
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_dir = os.path.join(script_dir, "..", "c_backend", "src", "sequences")
        output_dir = os.path.normpath(output_dir)

    max_width = args.max_width

    if args.width:
        # Single width mode
        if args.width < 1 or args.width > max_width:
            print(f"Error: width must be 1-{max_width}", file=sys.stderr)
            sys.exit(1)
        content = generate_width_file(args.width)
        if args.dry_run:
            print(content)
        else:
            os.makedirs(output_dir, exist_ok=True)
            path = os.path.join(output_dir, f"add_seq_{args.width}.c")
            with open(path, "w") as f:
                f.write(content)
            print(f"Written: {path}")
    else:
        # Full generation mode: all per-width files + dispatch
        if args.dry_run:
            # In dry-run mode, print all files separated by markers
            for w in range(1, max_width + 1):
                print(f"// === FILE: add_seq_{w}.c ===")
                print(generate_width_file(w))
                print()
            print("// === FILE: add_seq_dispatch.c ===")
            print(generate_dispatch_file(max_width))
        else:
            os.makedirs(output_dir, exist_ok=True)
            for w in range(1, max_width + 1):
                content = generate_width_file(w)
                path = os.path.join(output_dir, f"add_seq_{w}.c")
                with open(path, "w") as f:
                    f.write(content)
                print(f"Written: {path}")

            dispatch_content = generate_dispatch_file(max_width)
            dispatch_path = os.path.join(output_dir, "add_seq_dispatch.c")
            with open(dispatch_path, "w") as f:
                f.write(dispatch_content)
            print(f"Written: {dispatch_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
