#!/usr/bin/env python3
"""Toffoli hardcoded sequence generation script for CDKM addition (widths 1-8).

This script generates per-width C source files (toffoli_add_seq_N.c) and a unified
dispatch file (toffoli_add_seq_dispatch.c) for Toffoli-based addition sequences.

Generated files contain two addition variants per width:
  - QQ_add:  Quantum-quantum CDKM addition (static const sequence)
  - cQQ_add: Controlled quantum-quantum CDKM addition (dynamic init, cached)

The cQQ variant uses MCX(3 controls) which requires large_control heap allocation,
so it cannot be truly static const. Instead, a one-time init function builds and
caches the sequence.

Gate encoding:
  - CX:  .Gate=X, .Target=t, .NumControls=1, .Control={c}, .GateValue=1
  - CCX: .Gate=X, .Target=t, .NumControls=2, .Control={c1,c2}, .GateValue=1
  - MCX(3): Dynamically allocated with large_control for 3 controls

Algorithm: CDKM ripple-carry adder (Cuccaro et al., 2004)
  - MAJ(a,b,c) = CX(b,c), CX(a,c), CCX(c,a,b)
  - UMA(a,b,c) = CCX(c,a,b), CX(a,c), CX(b,a)
  - cMAJ(a,b,c,ext) = CCX(b,c,ext), CCX(a,c,ext), MCX(c,[a,b,ext])
  - cUMA(a,b,c,ext) = MCX(c,[a,b,ext]), CCX(a,c,ext), CCX(b,a,ext)

Usage:
  python scripts/generate_toffoli_seq.py                  # Generate all files
  python scripts/generate_toffoli_seq.py --width 4        # Generate only width 4
  python scripts/generate_toffoli_seq.py --dry-run        # Print to stdout
  python scripts/generate_toffoli_seq.py --validate       # Validate layer counts

Generated by: scripts/generate_toffoli_seq.py
Phase 72, Plan 01: Toffoli hardcoded sequence infrastructure
"""

import argparse
import os
import sys
from dataclasses import dataclass, field

# ============================================================================
# Gate dataclass for Toffoli sequences
# ============================================================================


@dataclass
class CliffordTGate:
    """Gate in Clifford+T basis: H, T, Tdg, X (0 controls), CX (1 control)."""

    gate_type: str  # "H", "T", "Tdg", "X", "CX"
    target: int
    control: int = -1  # Only for CX

    def to_c_static(self) -> str:
        """Generate C static const initializer."""
        gate_enum = {
            "H": "H",
            "T": "T_GATE",
            "Tdg": "TDG_GATE",
            "X": "X",
            "CX": "X",  # CX is X with 1 control
        }[self.gate_type]

        gate_value = {
            "H": "0",
            "T": "M_PI / 4.0",
            "Tdg": "-M_PI / 4.0",
            "X": "1",
            "CX": "1",
        }[self.gate_type]

        num_controls = 1 if self.gate_type == "CX" else 0
        ctrl_init = f"{{{self.control}}}" if num_controls == 1 else "{0}"

        return (
            f"{{.Gate = {gate_enum},\n"
            f"                                      .Target = {self.target},\n"
            f"                                      .NumControls = {num_controls},\n"
            f"                                      .Control = {ctrl_init},\n"
            f"                                      .large_control = NULL,\n"
            f"                                      .GateValue = {gate_value},\n"
            f"                                      .NumBasisGates = 0}}"
        )


def ccx_to_clifford_t(target: int, ctrl1: int, ctrl2: int) -> list[CliffordTGate]:
    """Expand CCX(target, ctrl1, ctrl2) into 15 Clifford+T gates.

    Sequence matches gate.c:emit_ccx_clifford_t exactly:
      1.  H(target)
      2.  CX(target, ctrl2)
      3.  Tdg(target)
      4.  CX(target, ctrl1)
      5.  T(target)
      6.  CX(target, ctrl2)
      7.  Tdg(target)
      8.  CX(target, ctrl1)
      9.  T(target)
      10. T(ctrl2)
      11. H(target)
      12. CX(ctrl2, ctrl1)
      13. T(ctrl1)
      14. Tdg(ctrl2)
      15. CX(ctrl2, ctrl1)
    """
    return [
        CliffordTGate("H", target),
        CliffordTGate("CX", target, ctrl2),
        CliffordTGate("Tdg", target),
        CliffordTGate("CX", target, ctrl1),
        CliffordTGate("T", target),
        CliffordTGate("CX", target, ctrl2),
        CliffordTGate("Tdg", target),
        CliffordTGate("CX", target, ctrl1),
        CliffordTGate("T", target),
        CliffordTGate("T", ctrl2),
        CliffordTGate("H", target),
        CliffordTGate("CX", ctrl2, ctrl1),
        CliffordTGate("T", ctrl1),
        CliffordTGate("Tdg", ctrl2),
        CliffordTGate("CX", ctrl2, ctrl1),
    ]


def toffoli_to_clifford_t(gates: list["ToffoliGate"]) -> list[CliffordTGate]:
    """Convert a list of ToffoliGate (X/CX/CCX) to CliffordTGate (H/T/Tdg/X/CX).

    CX and X gates pass through. CCX gates expand to 15 Clifford+T gates.
    """
    result = []
    for gate in gates:
        if gate.num_controls == 0:
            result.append(CliffordTGate("X", gate.target))
        elif gate.num_controls == 1:
            result.append(CliffordTGate("CX", gate.target, gate.controls[0]))
        elif gate.num_controls == 2:
            result.extend(ccx_to_clifford_t(gate.target, gate.controls[0], gate.controls[1]))
        else:
            raise ValueError(
                f"Cannot convert gate with {gate.num_controls} controls to Clifford+T. "
                f"Decompose MCX to CCX first."
            )
    return result


def _clifft_gate_description(gate: CliffordTGate) -> str:
    """Human-readable Clifford+T gate description for comments."""
    if gate.gate_type == "CX":
        return f"CX(target={gate.target}, ctrl={gate.control})"
    else:
        return f"{gate.gate_type}(target={gate.target})"


# ============================================================================


@dataclass
class ToffoliGate:
    """Represents a single gate in a Toffoli sequence."""

    gate_type: str  # "X" (with controls: CX, CCX, MCX)
    target: int
    controls: list[int] = field(default_factory=list)

    @property
    def num_controls(self) -> int:
        return len(self.controls)

    def to_c_static(self) -> str:
        """Generate C static const initializer (only for gates with <= 2 controls)."""
        if self.num_controls == 0:
            # X gate (no controls)
            return (
                f"{{.Gate = X,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 0,\n"
                f"                                      .Control = {{0}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = 1,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        elif self.num_controls == 1:
            # CX gate
            return (
                f"{{.Gate = X,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 1,\n"
                f"                                      .Control = {{{self.controls[0]}}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = 1,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        elif self.num_controls == 2:
            # CCX gate
            return (
                f"{{.Gate = X,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 2,\n"
                f"                                      .Control = {{{self.controls[0]}, {self.controls[1]}}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = 1,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        else:
            raise ValueError(f"Cannot generate static const for {self.num_controls} controls")

    def to_c_dynamic(self, var_name: str) -> str:
        """Generate C dynamic initialization code for a gate (any number of controls)."""
        lines = []
        if self.num_controls <= 2:
            ctrl_str = ", ".join(str(c) for c in self.controls) if self.controls else "0"
            if self.num_controls < 2:
                ctrl_init = f"{{{ctrl_str}}}"
            else:
                ctrl_init = f"{{{ctrl_str}}}"
            lines.append(
                f"    {var_name} = (gate_t){{.Gate = X, .Target = {self.target}, "
                f".NumControls = {self.num_controls}, .Control = {ctrl_init}, "
                f".large_control = NULL, .GateValue = 1, .NumBasisGates = 0}};"
            )
        else:
            # MCX with 3+ controls: need large_control allocation
            lines.append(f"    {var_name}.Gate = X;")
            lines.append(f"    {var_name}.Target = {self.target};")
            lines.append(f"    {var_name}.NumControls = {self.num_controls};")
            lines.append(f"    {var_name}.Control[0] = {self.controls[0]};")
            lines.append(f"    {var_name}.Control[1] = {self.controls[1]};")
            lines.append(f"    {var_name}.GateValue = 1;")
            lines.append(f"    {var_name}.NumBasisGates = 0;")
            lines.append(
                f"    {var_name}.large_control = malloc({self.num_controls} * sizeof(qubit_t));"
            )
            for i, c in enumerate(self.controls):
                lines.append(f"    {var_name}.large_control[{i}] = (qubit_t){c};")
        return "\n".join(lines)


# ============================================================================
# CDKM algorithm: generate gate sequences
# ============================================================================


def generate_qq_gates(bits: int) -> list[ToffoliGate]:
    """Generate QQ CDKM adder gate sequence for given width.

    Qubit layout:
      [0..bits-1]       = register a (target)
      [bits..2*bits-1]  = register b (source)
      [2*bits]          = ancilla carry (bits >= 2)

    Width 1: single CX(target=0, control=1)
    Width N >= 2: MAJ/UMA chain with ancilla at 2*N
    """
    gates = []

    if bits == 1:
        # Single CX: a[0] ^= b[0]
        gates.append(ToffoliGate("X", target=0, controls=[1]))
        return gates

    ancilla = 2 * bits

    # Forward MAJ sweep
    # MAJ(ancilla, b[0], a[0])
    gates.extend(_maj(ancilla, bits + 0, 0))
    for i in range(1, bits):
        # MAJ(a[i-1], b[i], a[i])
        gates.extend(_maj(i - 1, bits + i, i))

    # Reverse UMA sweep
    for i in range(bits - 1, 0, -1):
        # UMA(a[i-1], b[i], a[i])
        gates.extend(_uma(i - 1, bits + i, i))
    # UMA(ancilla, b[0], a[0])
    gates.extend(_uma(ancilla, bits + 0, 0))

    return gates


def generate_cqq_gates(bits: int) -> list[ToffoliGate]:
    """Generate controlled QQ CDKM adder gate sequence for given width.

    Qubit layout:
      [0..bits-1]       = register a (target)
      [bits..2*bits-1]  = register b (source)
      [2*bits]          = ancilla carry (bits >= 2)
      [2*bits+1]        = external control qubit (bits >= 2)

    Width 1: [0]=a, [1]=b, [2]=ext_control. Single CCX(target=0, ctrl1=1, ctrl2=2)
    Width N >= 2: cMAJ/cUMA chain
    """
    gates = []

    if bits == 1:
        # Single CCX: controlled a[0] ^= b[0]
        gates.append(ToffoliGate("X", target=0, controls=[1, 2]))
        return gates

    ancilla = 2 * bits
    ext_ctrl = 2 * bits + 1

    # Forward cMAJ sweep
    gates.extend(_cmaj(ancilla, bits + 0, 0, ext_ctrl))
    for i in range(1, bits):
        gates.extend(_cmaj(i - 1, bits + i, i, ext_ctrl))

    # Reverse cUMA sweep
    for i in range(bits - 1, 0, -1):
        gates.extend(_cuma(i - 1, bits + i, i, ext_ctrl))
    gates.extend(_cuma(ancilla, bits + 0, 0, ext_ctrl))

    return gates


def _maj(a: int, b: int, c: int) -> list[ToffoliGate]:
    """MAJ(a, b, c): CX(b,c), CX(a,c), CCX(c,a,b)"""
    return [
        ToffoliGate("X", target=b, controls=[c]),  # CX(target=b, control=c)
        ToffoliGate("X", target=a, controls=[c]),  # CX(target=a, control=c)
        ToffoliGate("X", target=c, controls=[a, b]),  # CCX(target=c, ctrl1=a, ctrl2=b)
    ]


def _uma(a: int, b: int, c: int) -> list[ToffoliGate]:
    """UMA(a, b, c): CCX(c,a,b), CX(a,c), CX(b,a)"""
    return [
        ToffoliGate("X", target=c, controls=[a, b]),  # CCX(target=c, ctrl1=a, ctrl2=b)
        ToffoliGate("X", target=a, controls=[c]),  # CX(target=a, control=c)
        ToffoliGate("X", target=b, controls=[a]),  # CX(target=b, control=a)
    ]


def _cmaj(a: int, b: int, c: int, ext: int) -> list[ToffoliGate]:
    """cMAJ(a, b, c, ext): CCX(b,c,ext), CCX(a,c,ext), MCX(c,[a,b,ext])"""
    return [
        ToffoliGate("X", target=b, controls=[c, ext]),  # CCX
        ToffoliGate("X", target=a, controls=[c, ext]),  # CCX
        ToffoliGate("X", target=c, controls=[a, b, ext]),  # MCX(3 controls)
    ]


def _cuma(a: int, b: int, c: int, ext: int) -> list[ToffoliGate]:
    """cUMA(a, b, c, ext): MCX(c,[a,b,ext]), CCX(a,c,ext), CCX(b,a,ext)"""
    return [
        ToffoliGate("X", target=c, controls=[a, b, ext]),  # MCX(3 controls)
        ToffoliGate("X", target=a, controls=[c, ext]),  # CCX
        ToffoliGate("X", target=b, controls=[a, ext]),  # CCX
    ]


# ============================================================================
# C code generation for QQ (static const)
# ============================================================================


def generate_qq_static_c(gates: list[ToffoliGate], width: int) -> str:
    """Generate static const C code for QQ variant (all gates have <= 2 controls)."""
    lines = []
    num_layers = len(gates)

    # Each gate is on its own layer (CDKM: 1 gate per layer)
    for i, gate in enumerate(gates):
        gate_str = gate.to_c_static()
        lines.append(f"static const gate_t TOFFOLI_QQ_{width}_L{i}[] = {{{gate_str}}};")
        lines.append("")

    # Layer pointer array
    if num_layers > 6:
        chunks = [list(range(i, min(i + 6, num_layers))) for i in range(0, num_layers, 6)]
        chunk_lines = []
        for chunk in chunks:
            names = ", ".join(f"TOFFOLI_QQ_{width}_L{j}" for j in chunk)
            chunk_lines.append(f"    {names}")
        layers_str = ",\n".join(chunk_lines)
        lines.append(f"static const gate_t *TOFFOLI_QQ_{width}_LAYERS[] = {{\n{layers_str}}};")
    else:
        names = ", ".join(f"TOFFOLI_QQ_{width}_L{i}" for i in range(num_layers))
        lines.append(f"static const gate_t *TOFFOLI_QQ_{width}_LAYERS[] = {{{names}}};")

    # Gates per layer array (all 1s for CDKM)
    gpl_str = ", ".join("1" for _ in range(num_layers))
    lines.append(f"static const num_t TOFFOLI_QQ_{width}_GPL[] = {{{gpl_str}}};")
    lines.append("")

    # Sequence struct
    lines.append(
        f"static const sequence_t HARDCODED_TOFFOLI_QQ_{width} = "
        f"{{.seq = (gate_t **)TOFFOLI_QQ_{width}_LAYERS,"
    )
    lines.append(f"                                              .num_layer = {num_layers},")
    lines.append(f"                                              .used_layer = {num_layers},")
    lines.append(
        f"                                              .gates_per_layer = "
        f"(num_t *)TOFFOLI_QQ_{width}_GPL}};"
    )

    return "\n".join(lines)


# ============================================================================
# C code generation for cQQ (dynamic init with caching)
# ============================================================================


def generate_cqq_init_c(gates: list[ToffoliGate], width: int) -> str:
    """Generate dynamic init function for cQQ variant (has MCX with 3 controls)."""
    lines = []
    num_layers = len(gates)

    lines.append(f"static sequence_t *cached_toffoli_cQQ_{width} = NULL;")
    lines.append("")
    lines.append(f"static sequence_t *init_toffoli_cQQ_{width}(void) {{")
    lines.append(f"    if (cached_toffoli_cQQ_{width} != NULL) return cached_toffoli_cQQ_{width};")
    lines.append("")
    lines.append("    sequence_t *seq = malloc(sizeof(sequence_t));")
    lines.append("    if (seq == NULL) return NULL;")
    lines.append(f"    seq->num_layer = {num_layers};")
    lines.append(f"    seq->used_layer = {num_layers};")
    lines.append(f"    seq->gates_per_layer = calloc({num_layers}, sizeof(num_t));")
    lines.append(f"    seq->seq = calloc({num_layers}, sizeof(gate_t *));")
    lines.append("    if (seq->gates_per_layer == NULL || seq->seq == NULL) {")
    lines.append("        free(seq->gates_per_layer); free(seq->seq); free(seq); return NULL;")
    lines.append("    }")
    lines.append("")

    for i, gate in enumerate(gates):
        lines.append(f"    // Layer {i}: {_gate_description(gate)}")
        lines.append(f"    seq->gates_per_layer[{i}] = 1;")
        lines.append(f"    seq->seq[{i}] = calloc(1, sizeof(gate_t));")
        lines.append(f"    if (seq->seq[{i}] == NULL) goto cleanup;")
        lines.append(gate.to_c_dynamic(f"seq->seq[{i}][0]"))
        lines.append("")

    lines.append(f"    cached_toffoli_cQQ_{width} = seq;")
    lines.append("    return seq;")
    lines.append("")
    lines.append("cleanup:")
    lines.append("    for (int i = 0; i < " + str(num_layers) + "; i++) {")
    lines.append("        if (seq->seq[i] != NULL) {")
    lines.append("            if (seq->seq[i][0].large_control != NULL)")
    lines.append("                free(seq->seq[i][0].large_control);")
    lines.append("            free(seq->seq[i]);")
    lines.append("        }")
    lines.append("    }")
    lines.append("    free(seq->seq); free(seq->gates_per_layer); free(seq);")
    lines.append("    return NULL;")
    lines.append("}")

    return "\n".join(lines)


def _gate_description(gate: ToffoliGate) -> str:
    """Human-readable gate description for comments."""
    if gate.num_controls == 0:
        return f"X(target={gate.target})"
    elif gate.num_controls == 1:
        return f"CX(target={gate.target}, ctrl={gate.controls[0]})"
    elif gate.num_controls == 2:
        return f"CCX(target={gate.target}, ctrl1={gate.controls[0]}, ctrl2={gate.controls[1]})"
    else:
        ctrls = ",".join(str(c) for c in gate.controls)
        return f"MCX(target={gate.target}, ctrls=[{ctrls}])"


# ============================================================================
# C code generation for Clifford+T QQ (static const)
# ============================================================================


def generate_clifft_qq_static_c(gates: list[CliffordTGate], width: int) -> str:
    """Generate static const C code for QQ Clifford+T variant (all gates max 1 control)."""
    lines = []
    num_layers = len(gates)

    # Each gate is on its own layer
    for i, gate in enumerate(gates):
        gate_str = gate.to_c_static()
        lines.append(f"static const gate_t TOFFOLI_CLIFFT_QQ_{width}_L{i}[] = {{{gate_str}}};")
        lines.append("")

    # Layer pointer array
    if num_layers > 6:
        chunks = [list(range(i, min(i + 6, num_layers))) for i in range(0, num_layers, 6)]
        chunk_lines = []
        for chunk in chunks:
            names = ", ".join(f"TOFFOLI_CLIFFT_QQ_{width}_L{j}" for j in chunk)
            chunk_lines.append(f"    {names}")
        layers_str = ",\n".join(chunk_lines)
        lines.append(
            f"static const gate_t *TOFFOLI_CLIFFT_QQ_{width}_LAYERS[] = {{\n{layers_str}}};"
        )
    else:
        names = ", ".join(f"TOFFOLI_CLIFFT_QQ_{width}_L{i}" for i in range(num_layers))
        lines.append(f"static const gate_t *TOFFOLI_CLIFFT_QQ_{width}_LAYERS[] = {{{names}}};")

    # Gates per layer array (all 1s)
    gpl_str = ", ".join("1" for _ in range(num_layers))
    lines.append(f"static const num_t TOFFOLI_CLIFFT_QQ_{width}_GPL[] = {{{gpl_str}}};")
    lines.append("")

    # Sequence struct
    lines.append(
        f"static const sequence_t HARDCODED_TOFFOLI_CLIFFT_QQ_{width} = "
        f"{{.seq = (gate_t **)TOFFOLI_CLIFFT_QQ_{width}_LAYERS,"
    )
    lines.append(f"                                              .num_layer = {num_layers},")
    lines.append(f"                                              .used_layer = {num_layers},")
    lines.append(
        f"                                              .gates_per_layer = "
        f"(num_t *)TOFFOLI_CLIFFT_QQ_{width}_GPL}};"
    )

    return "\n".join(lines)


# ============================================================================
# Clifford+T per-width file generation
# ============================================================================


def generate_clifft_qq_width_file(width: int) -> str:
    """Generate complete C source file for QQ Clifford+T at one width."""
    output = []

    # Header
    output.append("//")
    output.append(
        f"// toffoli_clifft_qq_{width}.c - CDKM QQ Clifford+T addition for {width}-bit width"
    )
    output.append("//")
    output.append(
        "// Generated by scripts/generate_toffoli_seq.py --clifford-t - DO NOT EDIT MANUALLY"
    )
    output.append("//")
    output.append("// Contains: Toffoli CDKM QQ Clifford+T addition (static const, zero CCX)")
    output.append("// Algorithm: CDKM ripple-carry adder with CCX->Clifford+T decomposition")
    output.append("// All gates: H/T/Tdg/CX/X (max 1 control) -- fully static const.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")
    output.append("#include <math.h>")
    output.append("")

    # Generate gate sequences
    qq_gates = generate_qq_gates(width)
    clifft_gates = toffoli_to_clifford_t(qq_gates)

    qq_num_qubits = 2 * width + (1 if width >= 2 else 0)
    output.append("// ============================================================================")
    output.append(f"// TOFFOLI CLIFFT QQ_ADD WIDTH {width} ({len(clifft_gates)} layers)")
    if width == 1:
        output.append("// Qubit layout: [0] = target, [1] = source")
    else:
        output.append(
            f"// Qubit layout: [0,{width - 1}] = target (a), "
            f"[{width},{2 * width - 1}] = source (b), [{2 * width}] = ancilla"
        )
    output.append(f"// Total qubits: {qq_num_qubits}")
    output.append("// All gates: H/T/Tdg/CX/X (max 1 control) -- zero CCX")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_clifft_qq_static_c(clifft_gates, width))
    output.append("")

    # Dispatch helper
    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_clifft_QQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_CLIFFT_QQ_{width};")
    output.append("}")
    output.append("")

    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Per-width file generation
# ============================================================================


def generate_width_file(width: int) -> str:
    """Generate complete C source file for one width."""
    output = []

    # Header
    output.append("//")
    output.append(
        f"// toffoli_add_seq_{width}.c - Hardcoded Toffoli addition sequences for {width}-bit width"
    )
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_seq.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Contains: Toffoli QQ_add (static const), cQQ_add (dynamic init, cached)")
    output.append("// Algorithm: CDKM ripple-carry adder (Cuccaro et al., 2004)")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")
    output.append("#include <stdlib.h>")
    output.append("")

    # Generate gate sequences
    qq_gates = generate_qq_gates(width)
    cqq_gates = generate_cqq_gates(width)

    # QQ section (static const)
    qq_num_qubits = 2 * width + (1 if width >= 2 else 0)
    output.append("// ============================================================================")
    output.append(f"// TOFFOLI QQ_ADD WIDTH {width} ({len(qq_gates)} layers)")
    if width == 1:
        output.append("// Qubit layout: [0] = target, [1] = source")
    else:
        output.append(
            f"// Qubit layout: [0,{width - 1}] = target (a), "
            f"[{width},{2 * width - 1}] = source (b), [{2 * width}] = ancilla"
        )
    output.append(f"// Total qubits: {qq_num_qubits}")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_qq_static_c(qq_gates, width))
    output.append("")

    # cQQ section (dynamic init)
    if width == 1:
        cqq_num_qubits = 3
    else:
        cqq_num_qubits = 2 * width + 2
    output.append("// ============================================================================")
    output.append(f"// TOFFOLI cQQ_ADD WIDTH {width} ({len(cqq_gates)} layers)")
    if width == 1:
        output.append("// Qubit layout: [0] = target, [1] = source, [2] = ext_ctrl")
    else:
        output.append(
            f"// Qubit layout: [0,{width - 1}] = target (a), "
            f"[{width},{2 * width - 1}] = source (b), "
            f"[{2 * width}] = ancilla, [{2 * width + 1}] = ext_ctrl"
        )
    output.append(f"// Total qubits: {cqq_num_qubits}")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_cqq_init_c(cqq_gates, width))
    output.append("")

    # Dispatch helpers
    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPERS FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_QQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_QQ_{width};")
    output.append("}")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_cQQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return (const sequence_t *)init_toffoli_cQQ_{width}();")
    output.append("}")
    output.append("")

    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Dispatch file generation
# ============================================================================


def generate_dispatch_file(max_width: int = 8) -> str:
    """Generate toffoli_add_seq_dispatch.c with unified dispatch functions."""
    output = []

    output.append("//")
    output.append(
        "// toffoli_add_seq_dispatch.c - Unified dispatch for hardcoded Toffoli addition sequences"
    )
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_seq.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Routes get_hardcoded_toffoli_*_add(bits) calls to per-width implementations.")
    output.append(
        "// Each per-width file is conditionally compiled via #ifdef TOFFOLI_SEQ_WIDTH_N."
    )
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("#include <stddef.h>")
    output.append("")

    # Forward declarations
    output.append("// ============================================================================")
    output.append("// FORWARD DECLARATIONS (conditionally compiled per width)")
    output.append("// ============================================================================")
    output.append("")

    for w in range(1, max_width + 1):
        output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
        output.append(f"const sequence_t *get_hardcoded_toffoli_QQ_add_{w}(int bits);")
        output.append(f"const sequence_t *get_hardcoded_toffoli_cQQ_add_{w}(int bits);")
        output.append("#endif")
        output.append("")

    # QQ dispatch
    output.append("// ============================================================================")
    output.append("// UNIFIED TOFFOLI QQ_add DISPATCH")
    output.append("// ============================================================================")
    output.append("")
    output.append("const sequence_t *get_hardcoded_toffoli_QQ_add(int bits) {")
    output.append("    switch (bits) {")
    for w in range(1, max_width + 1):
        output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
        output.append(f"    case {w}: return get_hardcoded_toffoli_QQ_add_{w}(bits);")
        output.append("#endif")
    output.append("    default: return NULL;")
    output.append("    }")
    output.append("}")
    output.append("")

    # cQQ dispatch
    output.append("// ============================================================================")
    output.append("// UNIFIED TOFFOLI cQQ_add DISPATCH")
    output.append("// ============================================================================")
    output.append("")
    output.append("const sequence_t *get_hardcoded_toffoli_cQQ_add(int bits) {")
    output.append("    switch (bits) {")
    for w in range(1, max_width + 1):
        output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
        output.append(f"    case {w}: return get_hardcoded_toffoli_cQQ_add_{w}(bits);")
        output.append("#endif")
    output.append("    default: return NULL;")
    output.append("    }")
    output.append("}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Header file generation
# ============================================================================


def generate_header_file(max_width: int = 8) -> str:
    """Generate toffoli_sequences.h header file."""
    output = []

    output.append("//")
    output.append("// toffoli_sequences.h - Hardcoded Toffoli gate sequences for CDKM addition")
    output.append("//")
    output.append("// This module provides pre-computed Toffoli gate sequences for CDKM")
    output.append(f"// ripple-carry addition up to {max_width}-bit width. These avoid runtime")
    output.append("// malloc/build overhead for the most common Toffoli addition widths.")
    output.append("//")
    output.append("// Two variants are supported:")
    output.append("//   QQ_add  - Quantum-quantum CDKM addition (static const)")
    output.append("//   cQQ_add - Controlled quantum-quantum CDKM addition (dynamic init, cached)")
    output.append("//")
    output.append("// PUBLIC API:")
    output.append(
        "//   get_hardcoded_toffoli_QQ_add(bits)  - Returns Toffoli QQ_add sequence or NULL"
    )
    output.append(
        "//   get_hardcoded_toffoli_cQQ_add(bits) - Returns Toffoli cQQ_add sequence or NULL"
    )
    output.append("//")
    output.append(f"// Returns NULL for widths > TOFFOLI_HARDCODED_MAX_WIDTH ({max_width}).")
    output.append("// Caller must fall back to dynamic generation for NULL returns.")
    output.append("//")
    output.append("// IMPLEMENTATION:")
    output.append(
        "//   - Per-width files: toffoli_add_seq_N.c (N=1..8), via #ifdef TOFFOLI_SEQ_WIDTH_N"
    )
    output.append("//   - Unified dispatch: toffoli_add_seq_dispatch.c routes to per-width impls")
    output.append("//   - Define TOFFOLI_SEQ_NO_WIDTH_N before including to disable width N")
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_seq.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("")
    output.append("#ifndef QUANTUM_TOFFOLI_SEQUENCES_H")
    output.append("#define QUANTUM_TOFFOLI_SEQUENCES_H")
    output.append("")
    output.append('#include "types.h"')
    output.append("")

    # Preprocessor guards
    output.append("// ======================================================")
    output.append("// PREPROCESSOR GUARDS - All widths enabled by default")
    output.append("// Define TOFFOLI_SEQ_NO_WIDTH_N before including to disable width N")
    output.append("// ======================================================")
    output.append("")

    for w in range(1, max_width + 1):
        output.append(f"#ifndef TOFFOLI_SEQ_NO_WIDTH_{w}")
        output.append(f"#define TOFFOLI_SEQ_WIDTH_{w}")
        output.append("#endif")

    output.append("")
    output.append("// Maximum width for which hardcoded Toffoli sequences are available")
    output.append(f"#define TOFFOLI_HARDCODED_MAX_WIDTH {max_width}")
    output.append("")

    # Public API
    output.append("// ======================================================")
    output.append("// PUBLIC API - 2 dispatch functions")
    output.append("// ======================================================")
    output.append("")
    output.append("// Returns pre-computed Toffoli QQ_add sequence for given bit width")
    output.append("// Returns NULL if bits > TOFFOLI_HARDCODED_MAX_WIDTH or bits < 1")
    output.append("const sequence_t *get_hardcoded_toffoli_QQ_add(int bits);")
    output.append("")
    output.append("// Returns pre-computed Toffoli cQQ_add (controlled QQ_add) sequence")
    output.append("// Returns NULL if bits > TOFFOLI_HARDCODED_MAX_WIDTH or bits < 1")
    output.append("const sequence_t *get_hardcoded_toffoli_cQQ_add(int bits);")
    output.append("")
    output.append("#endif // QUANTUM_TOFFOLI_SEQUENCES_H")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Validation
# ============================================================================


def validate_clifford_t(max_width: int = 8) -> bool:
    """Validate Clifford+T QQ generated gate sequences against expected counts."""
    all_ok = True

    # Expected Clifford+T QQ layer counts:
    # Width 1: 1 gate (single CX, no CCX to expand)
    # Width N >= 2: 4N CX + 4N*15 CCX = 4N + 60N = 64N layers
    print("=" * 60)
    print("Clifford+T QQ_add layer count validation")
    print("=" * 60)
    for w in range(1, max_width + 1):
        qq_gates = generate_qq_gates(w)
        clifft_gates = toffoli_to_clifford_t(qq_gates)
        actual = len(clifft_gates)
        if w == 1:
            expected = 1  # single CX
        else:
            # Count CX and CCX in original
            cx_count = sum(1 for g in qq_gates if g.num_controls <= 1)
            ccx_count = sum(1 for g in qq_gates if g.num_controls == 2)
            expected = cx_count + ccx_count * 15
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(f"  width {w:2d}: {actual:4d} layers  expected {expected:4d}  [{status}]")

    print()

    # Verify all Clifford+T gates have max 1 control
    print("=" * 60)
    print("Clifford+T QQ gate control count validation (must be <= 1)")
    print("=" * 60)
    for w in range(1, max_width + 1):
        qq_gates = generate_qq_gates(w)
        clifft_gates = toffoli_to_clifford_t(qq_gates)
        max_ctrl = 0
        for g in clifft_gates:
            ctrl = 1 if g.gate_type == "CX" else 0
            max_ctrl = max(max_ctrl, ctrl)
        ccx_count = sum(1 for g in clifft_gates if g.gate_type == "CX" and False)  # always 0
        status = "OK" if max_ctrl <= 1 else "FAIL"
        if max_ctrl > 1:
            all_ok = False
        print(f"  width {w:2d}: max controls = {max_ctrl}  [{status}]")

    print()

    # Verify gate type distribution
    print("=" * 60)
    print("Clifford+T QQ gate type distribution")
    print("=" * 60)
    for w in range(1, max_width + 1):
        qq_gates = generate_qq_gates(w)
        clifft_gates = toffoli_to_clifford_t(qq_gates)
        counts = {"H": 0, "T": 0, "Tdg": 0, "X": 0, "CX": 0}
        for g in clifft_gates:
            counts[g.gate_type] += 1
        parts = ", ".join(f"{k}={v}" for k, v in counts.items() if v > 0)
        print(f"  width {w:2d}: {parts}, total={len(clifft_gates)}")

    print()

    if all_ok:
        print("ALL CLIFFORD+T QQ VALIDATIONS PASSED")
    else:
        print("CLIFFORD+T QQ VALIDATION FAILED - see mismatches above")

    return all_ok


def validate(max_width: int = 8) -> bool:
    """Validate generated gate sequences against expected counts."""
    all_ok = True

    # Expected QQ layer counts:
    # Width 1: 1 gate (single CX)
    # Width N >= 2: 6*N gates (N MAJ + N UMA, each 3 gates)
    print("=" * 60)
    print("Toffoli QQ_add layer count validation")
    print("=" * 60)
    for w in range(1, max_width + 1):
        gates = generate_qq_gates(w)
        actual = len(gates)
        expected = 1 if w == 1 else 6 * w
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(f"  width {w:2d}: {actual:4d} layers  expected {expected:4d}  [{status}]")

    print()

    # Expected cQQ layer counts:
    # Width 1: 1 gate (single CCX)
    # Width N >= 2: 6*N gates (N cMAJ + N cUMA, each 3 gates)
    print("=" * 60)
    print("Toffoli cQQ_add layer count validation")
    print("=" * 60)
    for w in range(1, max_width + 1):
        gates = generate_cqq_gates(w)
        actual = len(gates)
        expected = 1 if w == 1 else 6 * w
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(f"  width {w:2d}: {actual:4d} layers  expected {expected:4d}  [{status}]")

    print()

    # Verify QQ gates use only CX and CCX (max 2 controls)
    print("=" * 60)
    print("QQ gate control count validation (must be <= 2)")
    print("=" * 60)
    for w in range(1, max_width + 1):
        gates = generate_qq_gates(w)
        max_ctrl = max(g.num_controls for g in gates)
        status = "OK" if max_ctrl <= 2 else "FAIL"
        if max_ctrl > 2:
            all_ok = False
        print(f"  width {w:2d}: max controls = {max_ctrl}  [{status}]")

    print()

    # Verify cQQ gates with MCX (3 controls) for width >= 2
    print("=" * 60)
    print("cQQ gate control count validation")
    print("=" * 60)
    for w in range(1, max_width + 1):
        gates = generate_cqq_gates(w)
        max_ctrl = max(g.num_controls for g in gates)
        mcx_count = sum(1 for g in gates if g.num_controls == 3)
        if w == 1:
            expected_max = 2  # Single CCX
            expected_mcx = 0
        else:
            expected_max = 3  # MCX from cMAJ/cUMA
            expected_mcx = 2 * w  # 1 MCX per cMAJ + 1 per cUMA, N of each
        status = "OK" if max_ctrl == expected_max and mcx_count == expected_mcx else "MISMATCH"
        if max_ctrl != expected_max or mcx_count != expected_mcx:
            all_ok = False
        print(
            f"  width {w:2d}: max controls = {max_ctrl}, "
            f"MCX(3) count = {mcx_count} (expected {expected_mcx})  [{status}]"
        )

    print()

    # Verify gate sequence matches ToffoliAddition.c patterns
    print("=" * 60)
    print("Width 2 QQ gate sequence verification (should match CDKM)")
    print("=" * 60)
    gates = generate_qq_gates(2)
    # Width 2 QQ: MAJ(4,2,0), MAJ(0,3,1), UMA(0,3,1), UMA(4,2,0)
    # ancilla=4, b[0]=2, a[0]=0, b[1]=3, a[1]=1
    expected_seq = [
        # MAJ(4, 2, 0)
        ("CX", 2, [0]),  # CX(target=b, control=c) = CX(2, 0)
        ("CX", 4, [0]),  # CX(target=a, control=c) = CX(4, 0)
        ("CCX", 0, [4, 2]),  # CCX(target=c, ctrl=a, ctrl=b) = CCX(0, 4, 2)
        # MAJ(0, 3, 1)
        ("CX", 3, [1]),
        ("CX", 0, [1]),
        ("CCX", 1, [0, 3]),
        # UMA(0, 3, 1)
        ("CCX", 1, [0, 3]),
        ("CX", 0, [1]),
        ("CX", 3, [0]),
        # UMA(4, 2, 0)
        ("CCX", 0, [4, 2]),
        ("CX", 4, [0]),
        ("CX", 2, [4]),
    ]

    all_match = True
    for i, (_exp_type, exp_target, exp_ctrls) in enumerate(expected_seq):
        gate = gates[i]
        match = gate.target == exp_target and gate.controls == exp_ctrls
        if not match:
            all_match = False
            print(
                f"  Layer {i}: MISMATCH - got ({gate.target}, {gate.controls}), "
                f"expected ({exp_target}, {exp_ctrls})"
            )

    if all_match:
        print("  All 12 gates match expected CDKM pattern")
    else:
        all_ok = False

    print()
    if all_ok:
        print("ALL VALIDATIONS PASSED")
    else:
        print("VALIDATION FAILED - see mismatches above")

    return all_ok


# ============================================================================
# CLI entry point
# ============================================================================


def main():
    parser = argparse.ArgumentParser(
        description="Generate hardcoded Toffoli addition sequence C files for widths 1-8."
    )
    parser.add_argument(
        "--width",
        type=int,
        metavar="N",
        help="Generate only for width N (default: all 1-8)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing files",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory for C files (default: c_backend/src/sequences/)",
    )
    parser.add_argument(
        "--header-dir",
        type=str,
        default=None,
        help="Output directory for header file (default: c_backend/include/)",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Cross-validate against expected layer counts",
    )
    parser.add_argument(
        "--max-width",
        type=int,
        default=8,
        help="Maximum width to generate (default: 8)",
    )
    parser.add_argument(
        "--clifford-t",
        action="store_true",
        help="Generate Clifford+T decomposed sequences (CCX expanded to 15 H/T/Tdg/CX gates)",
    )

    args = parser.parse_args()

    if args.validate and args.clifford_t:
        ok = validate_clifford_t(args.max_width)
        sys.exit(0 if ok else 1)

    if args.validate:
        ok = validate(args.max_width)
        sys.exit(0 if ok else 1)

    # Determine output directories
    script_dir = os.path.dirname(os.path.abspath(__file__))

    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = os.path.normpath(
            os.path.join(script_dir, "..", "c_backend", "src", "sequences")
        )

    if args.header_dir:
        header_dir = args.header_dir
    else:
        header_dir = os.path.normpath(os.path.join(script_dir, "..", "c_backend", "include"))

    max_width = args.max_width

    if args.clifford_t:
        # Clifford+T QQ generation mode
        if args.width:
            if args.width < 1 or args.width > max_width:
                print(f"Error: width must be 1-{max_width}", file=sys.stderr)
                sys.exit(1)
            content = generate_clifft_qq_width_file(args.width)
            if args.dry_run:
                print(content)
            else:
                os.makedirs(output_dir, exist_ok=True)
                path = os.path.join(output_dir, f"toffoli_clifft_qq_{args.width}.c")
                with open(path, "w") as f:
                    f.write(content)
                print(f"Written: {path}")
        else:
            # Full Clifford+T QQ generation
            if args.dry_run:
                for w in range(1, max_width + 1):
                    print(f"// === FILE: toffoli_clifft_qq_{w}.c ===")
                    print(generate_clifft_qq_width_file(w))
                    print()
            else:
                os.makedirs(output_dir, exist_ok=True)
                for w in range(1, max_width + 1):
                    content = generate_clifft_qq_width_file(w)
                    path = os.path.join(output_dir, f"toffoli_clifft_qq_{w}.c")
                    with open(path, "w") as f:
                        f.write(content)
                    print(f"Written: {path}")
    elif args.width:
        # Single width mode
        if args.width < 1 or args.width > max_width:
            print(f"Error: width must be 1-{max_width}", file=sys.stderr)
            sys.exit(1)
        content = generate_width_file(args.width)
        if args.dry_run:
            print(content)
        else:
            os.makedirs(output_dir, exist_ok=True)
            path = os.path.join(output_dir, f"toffoli_add_seq_{args.width}.c")
            with open(path, "w") as f:
                f.write(content)
            print(f"Written: {path}")
    else:
        # Full generation mode
        if args.dry_run:
            print("// === FILE: toffoli_sequences.h ===")
            print(generate_header_file(max_width))
            print()
            for w in range(1, max_width + 1):
                print(f"// === FILE: toffoli_add_seq_{w}.c ===")
                print(generate_width_file(w))
                print()
            print("// === FILE: toffoli_add_seq_dispatch.c ===")
            print(generate_dispatch_file(max_width))
        else:
            # Write header
            os.makedirs(header_dir, exist_ok=True)
            header_path = os.path.join(header_dir, "toffoli_sequences.h")
            with open(header_path, "w") as f:
                f.write(generate_header_file(max_width))
            print(f"Written: {header_path}")

            # Write per-width files
            os.makedirs(output_dir, exist_ok=True)
            for w in range(1, max_width + 1):
                content = generate_width_file(w)
                path = os.path.join(output_dir, f"toffoli_add_seq_{w}.c")
                with open(path, "w") as f:
                    f.write(content)
                print(f"Written: {path}")

            # Write dispatch file
            dispatch_content = generate_dispatch_file(max_width)
            dispatch_path = os.path.join(output_dir, "toffoli_add_seq_dispatch.c")
            with open(dispatch_path, "w") as f:
                f.write(dispatch_content)
            print(f"Written: {dispatch_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
