#!/usr/bin/env python3
"""BK CLA Clifford+T hardcoded sequence generation (widths 2-8).

This script generates per-width C source files and a unified dispatch file
for Clifford+T decomposed Brent-Kung Carry Look-Ahead addition sequences.

Four variants are supported:
  QQ      - Quantum-quantum BK CLA addition
  cQQ     - Controlled quantum-quantum BK CLA addition
  CQ_inc  - Classical-quantum increment (value=1) BK CLA
  cCQ_inc - Controlled classical-quantum increment (value=1) BK CLA

Width 1 is excluded because BK CLA returns NULL for bits < 2 (falls back to
CDKM/RCA at width 1).

CCX -> Clifford+T decomposition (15 gates per CCX):
  H(t), CX(t,c2), Tdg(t), CX(t,c1), T(t), CX(t,c2), Tdg(t), CX(t,c1),
  T(t), T(c2), H(t), CX(c2,c1), T(c1), Tdg(c2), CX(c2,c1)
  = 2H + 4T + 3Tdg + 6CX

Gate encoding in generated C:
  - H:   .Gate=H,       .Target=t, .NumControls=0, .Control={0}, .GateValue=0
  - T:   .Gate=T_GATE,  .Target=t, .NumControls=0, .Control={0}, .GateValue=M_PI/4.0
  - Tdg: .Gate=TDG_GATE,.Target=t, .NumControls=0, .Control={0}, .GateValue=-M_PI/4.0
  - X:   .Gate=X,       .Target=t, .NumControls=0, .Control={0}, .GateValue=1
  - CX:  .Gate=X,       .Target=t, .NumControls=1, .Control={c}, .GateValue=1

Algorithm: Brent-Kung parallel prefix CLA adder (Brent & Kung, 1982)
  Phase A: Initialize single-bit generates and propagates
  Phase B: BK prefix tree (up-sweep + down-sweep)
  Phase C: Copy carries from generate ancilla to carry-copy ancilla
  Phase D: Reverse Phase B (uncompute tree)
  Phase E: Uncompute propagates and generates
  Phase F: Sum extraction using carries

Generated by: scripts/generate_toffoli_clifft_cla.py
Phase 75, Plan 02: BK CLA Clifford+T hardcoded sequence generation
"""

import argparse
import os
import sys
from dataclasses import dataclass, field

# ============================================================================
# CliffordTGate dataclass
# ============================================================================


@dataclass
class CliffordTGate:
    """Represents a single Clifford+T gate (max 1 control)."""

    gate_type: str  # "H", "T", "Tdg", "X", "CX"
    target: int
    controls: list[int] = field(default_factory=list)

    @property
    def num_controls(self) -> int:
        return len(self.controls)

    def to_c_static(self) -> str:
        """Generate C static const initializer."""
        if self.gate_type == "H":
            return (
                f"{{.Gate = H,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 0,\n"
                f"                                      .Control = {{0}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = 0,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        elif self.gate_type == "T":
            return (
                f"{{.Gate = T_GATE,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 0,\n"
                f"                                      .Control = {{0}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = M_PI/4.0,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        elif self.gate_type == "Tdg":
            return (
                f"{{.Gate = TDG_GATE,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 0,\n"
                f"                                      .Control = {{0}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = -M_PI/4.0,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        elif self.gate_type == "X":
            if self.num_controls == 0:
                return (
                    f"{{.Gate = X,\n"
                    f"                                      .Target = {self.target},\n"
                    f"                                      .NumControls = 0,\n"
                    f"                                      .Control = {{0}},\n"
                    f"                                      .large_control = NULL,\n"
                    f"                                      .GateValue = 1,\n"
                    f"                                      .NumBasisGates = 0}}"
                )
            else:
                raise ValueError("X gate with controls not supported; use CX")
        elif self.gate_type == "CX":
            if self.num_controls != 1:
                raise ValueError(f"CX must have exactly 1 control, got {self.num_controls}")
            return (
                f"{{.Gate = X,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 1,\n"
                f"                                      .Control = {{{self.controls[0]}}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = 1,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        else:
            raise ValueError(f"Unknown gate type: {self.gate_type}")


# ============================================================================
# CCX -> Clifford+T expansion
# ============================================================================


def ccx_to_clifford_t(target: int, ctrl1: int, ctrl2: int) -> list[CliffordTGate]:
    """Expand one CCX into 15 Clifford+T gates.

    Matches emit_ccx_clifford_t_seq() from gate.c exactly:
      H(t), CX(t,c2), Tdg(t), CX(t,c1), T(t), CX(t,c2), Tdg(t), CX(t,c1),
      T(t), T(c2), H(t), CX(c2,c1), T(c1), Tdg(c2), CX(c2,c1)
    """
    return [
        CliffordTGate("H", target),
        CliffordTGate("CX", target, [ctrl2]),
        CliffordTGate("Tdg", target),
        CliffordTGate("CX", target, [ctrl1]),
        CliffordTGate("T", target),
        CliffordTGate("CX", target, [ctrl2]),
        CliffordTGate("Tdg", target),
        CliffordTGate("CX", target, [ctrl1]),
        CliffordTGate("T", target),
        CliffordTGate("T", ctrl2),
        CliffordTGate("H", target),
        CliffordTGate("CX", ctrl2, [ctrl1]),
        CliffordTGate("T", ctrl1),
        CliffordTGate("Tdg", ctrl2),
        CliffordTGate("CX", ctrl2, [ctrl1]),
    ]


# ============================================================================
# Intermediate gate (X/CX/CCX) before Clifford+T expansion
# ============================================================================


@dataclass
class ToffoliGate:
    """Intermediate gate before Clifford+T expansion (max 2 controls)."""

    gate_type: str  # "X", "CX", "CCX"
    target: int
    controls: list[int] = field(default_factory=list)

    @property
    def num_controls(self) -> int:
        return len(self.controls)


def expand_to_clifford_t(gates: list[ToffoliGate]) -> list[CliffordTGate]:
    """Expand a list of ToffoliGates into CliffordTGates.

    X -> X (pass through)
    CX -> CX (pass through)
    CCX -> 15 Clifford+T gates
    """
    result = []
    for g in gates:
        if g.gate_type == "X" and g.num_controls == 0:
            result.append(CliffordTGate("X", g.target))
        elif g.gate_type == "CX" and g.num_controls == 1:
            result.append(CliffordTGate("CX", g.target, list(g.controls)))
        elif g.gate_type == "CCX" and g.num_controls == 2:
            result.extend(ccx_to_clifford_t(g.target, g.controls[0], g.controls[1]))
        else:
            raise ValueError(f"Unsupported gate: {g.gate_type} with {g.num_controls} controls")
    return result


# ============================================================================
# Python BK prefix tree implementation (port from ToffoliAdditionCLA.c)
# ============================================================================


def bk_compute_merges(n_carries: int) -> list[tuple[int, int]]:
    """Compute BK prefix tree merge list.

    Port of bk_compute_merges() from ToffoliAdditionCLA.c (lines 58-151).

    Args:
        n_carries: Number of carry positions (bits - 1)

    Returns:
        List of (pos, partner) merge tuples in execution order.
    """
    if n_carries <= 1:
        return []

    merges = []
    up_sweep = [False] * n_carries
    covered = [False] * n_carries
    covered[0] = True  # position 0 is trivially complete

    leftmost = list(range(n_carries))

    # Up-sweep: reduce phase
    max_level = -1
    k = 0
    while True:
        stride = 1 << (k + 1)
        half = 1 << k
        found = False
        pos = stride - 1
        while pos < n_carries:
            partner = pos - half
            if partner >= 0:
                merges.append((pos, partner))
                up_sweep[pos] = True
                leftmost[pos] = leftmost[partner]
                if leftmost[pos] == 0:
                    covered[pos] = True
                found = True
                if k > max_level:
                    max_level = k
            pos += stride
        if not found:
            break
        k += 1

    # Down-sweep: propagate phase
    for dk in range(max_level - 1, -1, -1):
        half = 1 << dk
        stride = half << 1
        pos = stride + half - 1
        while pos < n_carries:
            if not up_sweep[pos]:
                partner = pos - half
                if partner >= 0:
                    merges.append((pos, partner))
                    up_sweep[pos] = True
                    leftmost[pos] = leftmost[partner]
                    if leftmost[pos] == 0:
                        covered[pos] = True
            pos += stride

    # Tail merges: chain from last complete position to uncovered positions
    for i in range(1, n_carries):
        if not covered[i]:
            for j in range(i - 1, -1, -1):
                if covered[j]:
                    merges.append((i, j))
                    leftmost[i] = 0
                    covered[i] = True
                    break

    return merges


# ============================================================================
# BK CLA QQ Clifford+T generation
# ============================================================================


def generate_bk_cla_qq_gates(bits: int) -> list[ToffoliGate]:
    """Generate BK CLA QQ adder gate sequence (X/CX/CCX).

    Qubit layout:
      a[i] = i               (0..n-1)
      b[i] = n+i             (n..2n-1)
      g[i] = 2n+i            (2n..3n-2)  generate ancilla
      tree_anc = 3n-1..       tree propagate-product ancilla
      carry_copy = 3n-1+num_merges..  carry-copy ancilla

    Phase A: Initialize generates and propagates
    Phase B: BK prefix tree
    Phase C: Copy carries
    Phase D: Reverse Phase B
    Phase E: Uncompute propagates and generates
    Phase F: Sum extraction
    """
    if bits < 2:
        return []

    n = bits
    n_carries = n - 1

    merges = bk_compute_merges(n_carries)
    num_merges = len(merges)

    tree_base = 3 * n - 1
    carry_base = tree_base + num_merges

    # Track propagate source for each carry position
    prop_src = [n + i for i in range(n_carries)]  # Initially b[i]

    gates = []

    # Phase A: Initialize generate and propagate
    for i in range(n_carries):
        gates.append(ToffoliGate("CCX", 2 * n + i, [i, n + i]))  # CCX(g[i], a[i], b[i])
    for i in range(n):
        gates.append(ToffoliGate("CX", n + i, [i]))  # CX(b[i], a[i])

    # Phase B: BK prefix tree
    phase_b_gates = []
    tree_anc_idx = 0
    for m_pos, m_partner in merges:
        tree_qubit = tree_base + tree_anc_idx

        # Step 1: Update group generate
        g1 = ToffoliGate("CCX", 2 * n + m_pos, [prop_src[m_pos], 2 * n + m_partner])
        gates.append(g1)
        phase_b_gates.append(g1)

        # Step 2: Compute group propagate product
        g2 = ToffoliGate("CCX", tree_qubit, [prop_src[m_pos], prop_src[m_partner]])
        gates.append(g2)
        phase_b_gates.append(g2)

        # Update prop_src
        prop_src[m_pos] = tree_qubit
        tree_anc_idx += 1

    # Phase C: Copy carries
    for i in range(n_carries):
        gates.append(ToffoliGate("CX", carry_base + i, [2 * n + i]))  # CX(c[i], g[i])

    # Phase D: Reverse Phase B
    for g in reversed(phase_b_gates):
        gates.append(ToffoliGate(g.gate_type, g.target, list(g.controls)))

    # Phase E: Uncompute propagates and generates
    for i in range(n - 1, -1, -1):
        gates.append(ToffoliGate("CX", n + i, [i]))  # CX(b[i], a[i])
    for i in range(n_carries - 1, -1, -1):
        gates.append(ToffoliGate("CCX", 2 * n + i, [i, n + i]))  # CCX(g[i], a[i], b[i])

    # Phase F: Sum extraction
    for i in range(n):
        gates.append(ToffoliGate("CX", n + i, [i]))  # CX(b[i], a[i])
    for i in range(1, n):
        gates.append(ToffoliGate("CX", n + i, [carry_base + i - 1]))  # CX(b[i], c[i-1])

    return gates


def generate_bk_cla_qq_clifft(bits: int) -> list[CliffordTGate]:
    """Generate BK CLA QQ Clifford+T sequence."""
    toffoli_gates = generate_bk_cla_qq_gates(bits)
    return expand_to_clifford_t(toffoli_gates)


# ============================================================================
# BK CLA cQQ Clifford+T generation
# ============================================================================


def generate_bk_cla_cqq_gates(bits: int) -> list[ToffoliGate]:
    """Generate BK CLA cQQ adder gate sequence (controlled by ext_ctrl).

    Derive from QQ sequence by injecting ext_ctrl into every gate:
      X -> CX(target, ext_ctrl)
      CX(target, ctrl) -> CCX(target, ctrl, ext_ctrl)
      CCX(target, c1, c2) -> MCX(3) -> decomposed into 3 CCX via AND-ancilla

    Qubit layout:
      Same as QQ, with ext_ctrl and and_anc appended.
      ext_ctrl = 2*bits + ancilla_count
      and_anc = ext_ctrl + 1
    """
    if bits < 2:
        return []

    n = bits
    n_carries = n - 1
    merges = bk_compute_merges(n_carries)
    num_merges = len(merges)

    ancilla_count = 2 * n_carries + num_merges  # same as bk_cla_ancilla_count
    ext_ctrl = 2 * bits + ancilla_count
    and_anc = ext_ctrl + 1

    qq_gates = generate_bk_cla_qq_gates(bits)
    gates = []

    for g in qq_gates:
        if g.gate_type == "X" and g.num_controls == 0:
            # X -> CX with ext_ctrl
            gates.append(ToffoliGate("CX", g.target, [ext_ctrl]))
        elif g.gate_type == "CX" and g.num_controls == 1:
            # CX -> CCX with [original_ctrl, ext_ctrl]
            gates.append(ToffoliGate("CCX", g.target, [g.controls[0], ext_ctrl]))
        elif g.gate_type == "CCX" and g.num_controls == 2:
            # CCX -> MCX(3) decomposed via AND-ancilla:
            # CCX(and_anc, c1, c2) -- compute AND
            # CCX(target, and_anc, ext_ctrl) -- apply
            # CCX(and_anc, c1, c2) -- uncompute AND
            gates.append(ToffoliGate("CCX", and_anc, [g.controls[0], g.controls[1]]))
            gates.append(ToffoliGate("CCX", g.target, [and_anc, ext_ctrl]))
            gates.append(ToffoliGate("CCX", and_anc, [g.controls[0], g.controls[1]]))
        else:
            raise ValueError(f"Unexpected gate in QQ sequence: {g}")

    return gates


def generate_bk_cla_cqq_clifft(bits: int) -> list[CliffordTGate]:
    """Generate BK CLA cQQ Clifford+T sequence."""
    toffoli_gates = generate_bk_cla_cqq_gates(bits)
    return expand_to_clifford_t(toffoli_gates)


# ============================================================================
# BK CLA CQ increment (value=1) Clifford+T generation
# ============================================================================


def generate_bk_cla_cq_inc_gates(bits: int) -> list[ToffoliGate]:
    """Generate BK CLA CQ increment (value=1) gate sequence.

    CQ uses temp-register approach: X-init temp to classical value,
    run QQ BK CLA gates (with classical-bit simplification), X-cleanup.

    For value=1 (only LSB=1):
      - Phase A: temp[0]=|1> (X-init), rest =|0>
        - CCX(g[i], temp[i], self[i]) at bit=0: temp[0]=|1> -> CX(g[0], self[0])
        - CCX at bit>0: temp[i]=|0> -> NOP (skip)
        - CX(self[i], temp[i]) at bit=0: temp[0]=|1> -> X(self[0])
        - CX at bit>0: temp[i]=|0> -> NOP (skip)
      - Phase E mirrors Phase A (reverse)
      - Phase F: sum extraction (simplified for value=1)

    Qubit layout (same as C implementation):
      temp[i] = i           (0..n-1)
      self[i] = n+i         (n..2n-1)
      g[i] = 2n+i           (2n..3n-2)
      tree_anc = 3n-1..
      carry_copy = 3n-1+num_merges..
    """
    if bits < 2:
        return []

    n = bits
    n_carries = n - 1
    merges = bk_compute_merges(n_carries)
    num_merges = len(merges)

    tree_base = 3 * n - 1
    carry_base = tree_base + num_merges

    # For value=1: bin = [0,0,...,0,1] MSB-first, so only bit 0 (LSB) is 1
    # bit_i = 1 for i=0, bit_i = 0 for i>0

    gates = []

    # Phase A (simplified for value=1):
    # Generate part: only bit 0 is active
    # bit=0: X-init temp[0], then CX(g[0], self[0])
    gates.append(ToffoliGate("X", 0))  # X(temp[0])
    gates.append(ToffoliGate("CX", 2 * n + 0, [n + 0]))  # CX(g[0], self[0])
    # bits 1..n-2: NOP (temp[i]=|0>)

    # Propagate part: only bit 0 is active
    # bit=0: X(self[0]) (CX with temp[0]=|1> simplifies to X)
    gates.append(ToffoliGate("X", n + 0))  # X(self[0])
    # bits 1..n-1: NOP

    # Phases B, C, D: copied from QQ sequence (all gates unchanged)
    # Build the QQ gates for just B, C, D phases
    prop_src = [n + i for i in range(n_carries)]
    phase_b_gates = []
    tree_anc_idx = 0
    for m_pos, m_partner in merges:
        tree_qubit = tree_base + tree_anc_idx

        g1 = ToffoliGate("CCX", 2 * n + m_pos, [prop_src[m_pos], 2 * n + m_partner])
        gates.append(g1)
        phase_b_gates.append(g1)

        g2 = ToffoliGate("CCX", tree_qubit, [prop_src[m_pos], prop_src[m_partner]])
        gates.append(g2)
        phase_b_gates.append(g2)

        prop_src[m_pos] = tree_qubit
        tree_anc_idx += 1

    # Phase C: Copy carries
    for i in range(n_carries):
        gates.append(ToffoliGate("CX", carry_base + i, [2 * n + i]))

    # Phase D: Reverse Phase B
    for g in reversed(phase_b_gates):
        gates.append(ToffoliGate(g.gate_type, g.target, list(g.controls)))

    # Phase E (simplified, reverse of Phase A for value=1):
    # Propagate uncompute: only bit 0 active
    gates.append(ToffoliGate("X", n + 0))  # X(self[0])

    # Generate uncompute: only bit 0 active
    gates.append(ToffoliGate("CX", 2 * n + 0, [n + 0]))  # CX(g[0], self[0])
    gates.append(ToffoliGate("X", 0))  # X-cleanup(temp[0])

    # Phase F (simplified for value=1):
    # X(self[i]) for bit[i]=1 -> only bit 0
    gates.append(ToffoliGate("X", n + 0))

    # CX(self[i], c[i-1]) for i=1..n-1
    for i in range(1, n):
        gates.append(ToffoliGate("CX", n + i, [carry_base + i - 1]))

    return gates


def generate_bk_cla_cq_inc_clifft(bits: int) -> list[CliffordTGate]:
    """Generate BK CLA CQ increment Clifford+T sequence."""
    toffoli_gates = generate_bk_cla_cq_inc_gates(bits)
    return expand_to_clifford_t(toffoli_gates)


# ============================================================================
# BK CLA cCQ increment (value=1) Clifford+T generation
# ============================================================================


def generate_bk_cla_ccq_inc_gates(bits: int) -> list[ToffoliGate]:
    """Generate BK CLA cCQ increment (value=1) gate sequence.

    Controlled CQ: CX-init (controlled by ext_ctrl) + cQQ BK gates + CX-cleanup.

    For value=1, Phase A becomes:
      - CX-init(temp[0], ext_ctrl) instead of X(temp[0])
      - CCX(g[0], self[0], ext_ctrl) instead of CX(g[0], self[0])
      - CX(self[0], ext_ctrl) instead of X(self[0])

    Phases B, C, D use cQQ gates (all controlled by ext_ctrl).

    Phase E mirrors Phase A.
    Phase F:
      - CX(self[0], ext_ctrl) instead of X(self[0])
      - CCX(self[i], c[i-1], ext_ctrl) instead of CX(self[i], c[i-1])

    Qubit layout:
      Same as CQ, with ext_ctrl and and_anc appended.
    """
    if bits < 2:
        return []

    n = bits
    n_carries = n - 1
    merges = bk_compute_merges(n_carries)
    num_merges = len(merges)

    ancilla_count = 2 * n_carries + num_merges
    ext_ctrl = 2 * bits + ancilla_count
    and_anc = ext_ctrl + 1

    gates = []

    tree_base = 3 * n - 1
    carry_base = tree_base + num_merges

    # Phase A (simplified + controlled for value=1):
    # bit=0 only active:
    gates.append(ToffoliGate("CX", 0, [ext_ctrl]))  # CX-init(temp[0], ext_ctrl)
    gates.append(ToffoliGate("CCX", 2 * n + 0, [n + 0, ext_ctrl]))  # CCX(g[0], self[0], ext_ctrl)
    gates.append(ToffoliGate("CX", n + 0, [ext_ctrl]))  # CX(self[0], ext_ctrl)

    # Phases B, C, D: use cQQ gates (inject ext_ctrl into every QQ gate)
    # Build the QQ gates for B, C, D, then inject ext_ctrl
    prop_src = [n + i for i in range(n_carries)]
    phase_b_qq_gates = []
    tree_anc_idx = 0
    for m_pos, m_partner in merges:
        tree_qubit = tree_base + tree_anc_idx

        g1 = ToffoliGate("CCX", 2 * n + m_pos, [prop_src[m_pos], 2 * n + m_partner])
        phase_b_qq_gates.append(g1)

        g2 = ToffoliGate("CCX", tree_qubit, [prop_src[m_pos], prop_src[m_partner]])
        phase_b_qq_gates.append(g2)

        prop_src[m_pos] = tree_qubit
        tree_anc_idx += 1

    # Phase C QQ gates
    phase_c_qq_gates = []
    for i in range(n_carries):
        phase_c_qq_gates.append(ToffoliGate("CX", carry_base + i, [2 * n + i]))

    # Phase D QQ gates (reverse of Phase B)
    phase_d_qq_gates = list(reversed(phase_b_qq_gates))

    # Inject ext_ctrl into all B+C+D QQ gates
    all_bcd_qq = phase_b_qq_gates + phase_c_qq_gates + phase_d_qq_gates
    for g in all_bcd_qq:
        if g.gate_type == "CX" and g.num_controls == 1:
            # CX -> CCX with ext_ctrl
            gates.append(ToffoliGate("CCX", g.target, [g.controls[0], ext_ctrl]))
        elif g.gate_type == "CCX" and g.num_controls == 2:
            # CCX -> MCX(3) decomposed via AND-ancilla
            gates.append(ToffoliGate("CCX", and_anc, [g.controls[0], g.controls[1]]))
            gates.append(ToffoliGate("CCX", g.target, [and_anc, ext_ctrl]))
            gates.append(ToffoliGate("CCX", and_anc, [g.controls[0], g.controls[1]]))
        else:
            raise ValueError(f"Unexpected gate in BCD: {g}")

    # Phase E (simplified + controlled, reverse of Phase A):
    gates.append(ToffoliGate("CX", n + 0, [ext_ctrl]))  # CX(self[0], ext_ctrl)
    gates.append(ToffoliGate("CCX", 2 * n + 0, [n + 0, ext_ctrl]))  # CCX uncompute
    gates.append(ToffoliGate("CX", 0, [ext_ctrl]))  # CX-cleanup(temp[0], ext_ctrl)

    # Phase F (simplified + controlled for value=1):
    gates.append(ToffoliGate("CX", n + 0, [ext_ctrl]))  # controlled X(self[0])
    for i in range(1, n):
        gates.append(ToffoliGate("CCX", n + i, [carry_base + i - 1, ext_ctrl]))

    return gates


def generate_bk_cla_ccq_inc_clifft(bits: int) -> list[CliffordTGate]:
    """Generate BK CLA cCQ increment Clifford+T sequence."""
    toffoli_gates = generate_bk_cla_ccq_inc_gates(bits)
    return expand_to_clifford_t(toffoli_gates)


# ============================================================================
# C code generation (static const)
# ============================================================================


def generate_static_c(gates: list[CliffordTGate], prefix: str, width: int) -> str:
    """Generate static const C code for a Clifford+T sequence.

    Args:
        gates: List of CliffordTGate
        prefix: Variable name prefix (e.g., "TOFFOLI_CLIFFT_CLA_QQ")
        width: Width for naming
    """
    lines = []
    num_layers = len(gates)

    # Per-layer gate arrays (1 gate per layer)
    for i, gate in enumerate(gates):
        gate_str = gate.to_c_static()
        lines.append(f"static const gate_t {prefix}_{width}_L{i}[] = {{{gate_str}}};")
        lines.append("")

    # Layer pointer array
    if num_layers > 6:
        chunks = [list(range(i, min(i + 6, num_layers))) for i in range(0, num_layers, 6)]
        chunk_lines = []
        for chunk in chunks:
            names = ", ".join(f"{prefix}_{width}_L{j}" for j in chunk)
            chunk_lines.append(f"    {names}")
        layers_str = ",\n".join(chunk_lines)
        lines.append(f"static const gate_t *{prefix}_{width}_LAYERS[] = {{\n{layers_str}}};")
    else:
        names = ", ".join(f"{prefix}_{width}_L{i}" for i in range(num_layers))
        lines.append(f"static const gate_t *{prefix}_{width}_LAYERS[] = {{{names}}};")

    # Gates per layer array (all 1s)
    gpl_str = ", ".join("1" for _ in range(num_layers))
    lines.append(f"static const num_t {prefix}_{width}_GPL[] = {{{gpl_str}}};")
    lines.append("")

    # Sequence struct
    lines.append(
        f"static const sequence_t HARDCODED_{prefix}_{width} = "
        f"{{.seq = (gate_t **){prefix}_{width}_LAYERS,"
    )
    lines.append(f"                                              .num_layer = {num_layers},")
    lines.append(f"                                              .used_layer = {num_layers},")
    lines.append(
        f"                                              .gates_per_layer = "
        f"(num_t *){prefix}_{width}_GPL}};"
    )

    return "\n".join(lines)


# ============================================================================
# Per-width file generation
# ============================================================================


def _variant_comment(
    variant: str, width: int, gates: list[CliffordTGate], toffoli_gates: list, qubit_desc: str
) -> list[str]:
    """Generate comment block for a variant section."""
    prefix_map = {
        "qq": "TOFFOLI CLIFFT CLA QQ",
        "cqq": "TOFFOLI CLIFFT CLA cQQ",
        "cq_inc": "TOFFOLI CLIFFT CLA CQ_INC",
        "ccq_inc": "TOFFOLI CLIFFT CLA cCQ_INC",
    }
    ccx_count = sum(1 for g in toffoli_gates if g.gate_type == "CCX")
    cx_count = sum(1 for g in toffoli_gates if g.gate_type == "CX")
    x_count = sum(1 for g in toffoli_gates if g.gate_type == "X")
    lines = [
        "// ============================================================================",
        f"// {prefix_map[variant]} WIDTH {width} ({len(gates)} Clifford+T layers)",
        f"// Source: {x_count} X + {cx_count} CX + {ccx_count} CCX = {len(toffoli_gates)} Toffoli gates",
        f"// Clifford+T: {ccx_count}*15 + {cx_count}*1 + {x_count}*1 = {ccx_count * 15 + cx_count + x_count} gates",
        f"// Qubit layout: {qubit_desc}",
        "// All gates: H/T/Tdg/CX/X (zero CCX)",
        "// ============================================================================",
    ]
    return lines


def generate_width_file_qq(width: int) -> tuple[str, list[CliffordTGate]]:
    """Generate QQ section for one width."""
    toffoli_gates = generate_bk_cla_qq_gates(width)
    clifft_gates = expand_to_clifford_t(toffoli_gates)

    n = width
    merges = bk_compute_merges(n - 1)
    num_merges = len(merges)
    tree_base = 3 * n - 1
    carry_base = tree_base + num_merges

    qubit_desc = (
        f"a[0..{n - 1}], b[{n}..{2 * n - 1}], g[{2 * n}..{3 * n - 2}], "
        f"tree_anc[{tree_base}..{tree_base + num_merges - 1 if num_merges > 0 else tree_base}], "
        f"carry[{carry_base}..{carry_base + n - 2}]"
    )

    lines = _variant_comment("qq", width, clifft_gates, toffoli_gates, qubit_desc)
    lines.append("")
    lines.append(generate_static_c(clifft_gates, "TOFFOLI_CLIFFT_CLA_QQ", width))
    lines.append("")

    return "\n".join(lines), clifft_gates


def generate_width_file_cqq(width: int) -> tuple[str, list[CliffordTGate]]:
    """Generate cQQ section for one width."""
    toffoli_gates = generate_bk_cla_cqq_gates(width)
    clifft_gates = expand_to_clifford_t(toffoli_gates)

    n = width
    merges = bk_compute_merges(n - 1)
    num_merges = len(merges)
    ancilla_count = 2 * (n - 1) + num_merges
    ext_ctrl = 2 * n + ancilla_count
    and_anc = ext_ctrl + 1

    qubit_desc = (
        f"a[0..{n - 1}], b[{n}..{2 * n - 1}], ancilla, ext_ctrl={ext_ctrl}, and_anc={and_anc}"
    )

    lines = _variant_comment("cqq", width, clifft_gates, toffoli_gates, qubit_desc)
    lines.append("")
    lines.append(generate_static_c(clifft_gates, "TOFFOLI_CLIFFT_CLA_CQQ", width))
    lines.append("")

    return "\n".join(lines), clifft_gates


def generate_width_file_cq_inc(width: int) -> tuple[str, list[CliffordTGate]]:
    """Generate CQ increment (value=1) section for one width."""
    toffoli_gates = generate_bk_cla_cq_inc_gates(width)
    clifft_gates = expand_to_clifford_t(toffoli_gates)

    n = width
    merges = bk_compute_merges(n - 1)
    num_merges = len(merges)
    tree_base = 3 * n - 1
    carry_end = tree_base + num_merges + n - 2

    qubit_desc = (
        f"temp[0..{n - 1}], self[{n}..{2 * n - 1}], g[{2 * n}..{3 * n - 2}], "
        f"tree/carry[{tree_base}..{carry_end}]"
    )

    lines = _variant_comment("cq_inc", width, clifft_gates, toffoli_gates, qubit_desc)
    lines.append("")
    lines.append(generate_static_c(clifft_gates, "TOFFOLI_CLIFFT_CLA_CQ_INC", width))
    lines.append("")

    return "\n".join(lines), clifft_gates


def generate_width_file_ccq_inc(width: int) -> tuple[str, list[CliffordTGate]]:
    """Generate cCQ increment (value=1) section for one width."""
    toffoli_gates = generate_bk_cla_ccq_inc_gates(width)
    clifft_gates = expand_to_clifford_t(toffoli_gates)

    n = width
    merges = bk_compute_merges(n - 1)
    num_merges = len(merges)
    ancilla_count = 2 * (n - 1) + num_merges
    ext_ctrl = 2 * n + ancilla_count
    and_anc = ext_ctrl + 1

    qubit_desc = (
        f"temp[0..{n - 1}], self[{n}..{2 * n - 1}], ancilla, ext_ctrl={ext_ctrl}, and_anc={and_anc}"
    )

    lines = _variant_comment("ccq_inc", width, clifft_gates, toffoli_gates, qubit_desc)
    lines.append("")
    lines.append(generate_static_c(clifft_gates, "TOFFOLI_CLIFFT_CLA_CCQ_INC", width))
    lines.append("")

    return "\n".join(lines), clifft_gates


def generate_qq_file(width: int) -> str:
    """Generate complete QQ C source file for one width."""
    output = []
    output.append("//")
    output.append(
        f"// toffoli_clifft_cla_qq_{width}.c - BK CLA QQ Clifford+T addition for {width}-bit width"
    )
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Contains: BK CLA QQ_add Clifford+T (static const, zero CCX)")
    output.append("// Algorithm: Brent-Kung parallel prefix CLA with CCX->Clifford+T decomposition")
    output.append("// All gates are H/T/Tdg/CX/X (max 1 control) -- no dynamic allocation needed.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("#include <math.h>")
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    section, _ = generate_width_file_qq(width)
    output.append(section)

    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_CLIFFT_CLA_QQ_{width};")
    output.append("}")
    output.append("")
    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


def generate_cqq_file(width: int) -> str:
    """Generate complete cQQ C source file for one width."""
    output = []
    output.append("//")
    output.append(
        f"// toffoli_clifft_cla_cqq_{width}.c - BK CLA cQQ Clifford+T addition for {width}-bit width"
    )
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Contains: BK CLA cQQ_add Clifford+T (static const, zero CCX)")
    output.append(
        "// Algorithm: Brent-Kung parallel prefix CLA with ext_ctrl + AND-ancilla MCX decomp + CCX->Clifford+T"
    )
    output.append("// All gates are H/T/Tdg/CX/X (max 1 control) -- no dynamic allocation needed.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("#include <math.h>")
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    section, _ = generate_width_file_cqq(width)
    output.append(section)

    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(
        f"const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add_{width}(int bits) {{"
    )
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_CLIFFT_CLA_CQQ_{width};")
    output.append("}")
    output.append("")
    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


def generate_cq_inc_file(width: int) -> str:
    """Generate complete CQ increment C source file for one width."""
    output = []
    output.append("//")
    output.append(
        f"// toffoli_clifft_cla_cq_inc_{width}.c - BK CLA CQ increment Clifford+T for {width}-bit width"
    )
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Contains: BK CLA CQ_inc (value=1) Clifford+T (static const, zero CCX)")
    output.append(
        "// Algorithm: Brent-Kung CLA with temp-register CQ + classical-bit simplification + CCX->Clifford+T"
    )
    output.append("// All gates are H/T/Tdg/CX/X (max 1 control) -- no dynamic allocation needed.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("#include <math.h>")
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    section, _ = generate_width_file_cq_inc(width)
    output.append(section)

    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_CLIFFT_CLA_CQ_INC_{width};")
    output.append("}")
    output.append("")
    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


def generate_ccq_inc_file(width: int) -> str:
    """Generate complete cCQ increment C source file for one width."""
    output = []
    output.append("//")
    output.append(
        f"// toffoli_clifft_cla_ccq_inc_{width}.c - BK CLA cCQ increment Clifford+T for {width}-bit width"
    )
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Contains: BK CLA cCQ_inc (value=1) Clifford+T (static const, zero CCX)")
    output.append(
        "// Algorithm: Brent-Kung CLA with controlled temp-register + AND-ancilla MCX decomp + CCX->Clifford+T"
    )
    output.append("// All gates are H/T/Tdg/CX/X (max 1 control) -- no dynamic allocation needed.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("#include <math.h>")
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    section, _ = generate_width_file_ccq_inc(width)
    output.append(section)

    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(
        f"const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc_{width}(int bits) {{"
    )
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_CLIFFT_CLA_CCQ_INC_{width};")
    output.append("}")
    output.append("")
    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Dispatch file generation
# ============================================================================


def generate_dispatch_file(min_width: int = 2, max_width: int = 8) -> str:
    """Generate toffoli_clifft_cla_dispatch.c with unified dispatch functions."""
    output = []

    output.append("//")
    output.append("// toffoli_clifft_cla_dispatch.c - Dispatch for BK CLA Clifford+T sequences")
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_clifft_cla.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Routes get_hardcoded_toffoli_clifft_cla_*() to per-width implementations.")
    output.append("// BK CLA requires bits >= 2, so no width-1 entries.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("#include <stddef.h>")
    output.append("")

    # Forward declarations for all 4 variants
    variants = [
        ("QQ_add", "QQ add"),
        ("cQQ_add", "cQQ add"),
        ("CQ_inc", "CQ increment (value=1)"),
        ("cCQ_inc", "cCQ increment (value=1)"),
    ]

    for func_suffix, desc in variants:
        output.append(
            "// ============================================================================"
        )
        output.append(f"// FORWARD DECLARATIONS - {desc} (conditionally compiled per width)")
        output.append(
            "// ============================================================================"
        )
        output.append("")
        for w in range(min_width, max_width + 1):
            output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
            output.append(
                f"const sequence_t *get_hardcoded_toffoli_clifft_cla_{func_suffix}_{w}(int bits);"
            )
            output.append("#endif")
            output.append("")

    # Dispatch functions
    for func_suffix, desc in variants:
        output.append(
            "// ============================================================================"
        )
        output.append(f"// UNIFIED BK CLA CLIFFORD+T {desc.upper()} DISPATCH")
        output.append(
            "// ============================================================================"
        )
        output.append("")
        output.append(
            f"const sequence_t *get_hardcoded_toffoli_clifft_cla_{func_suffix}(int bits) {{"
        )
        output.append("    switch (bits) {")
        for w in range(min_width, max_width + 1):
            output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
            output.append(f"    case {w}:")
            output.append(
                f"        return get_hardcoded_toffoli_clifft_cla_{func_suffix}_{w}(bits);"
            )
            output.append("#endif")
        output.append("    default:")
        output.append("        return NULL;")
        output.append("    }")
        output.append("}")
        output.append("")

    return "\n".join(output)


# ============================================================================
# Validation
# ============================================================================


def validate(min_width: int = 2, max_width: int = 8) -> bool:
    """Validate generated gate sequences."""
    all_ok = True

    # Expected BK merge counts (verified against C bk_compute_merges())
    expected_merge_counts = {
        2: 0,  # n_carries=1 -> 0 merges
        3: 1,  # n_carries=2 -> 1 merge
        4: 2,  # n_carries=3 -> 2 merges
        5: 4,  # n_carries=4 -> 4 merges
        6: 5,  # n_carries=5 -> 5 merges (up-sweep: 2, down-sweep: 1, tail: 2)
        7: 7,  # n_carries=6 -> 7 merges (up-sweep: 2, down-sweep: 1, tail: 4)
        8: 9,  # n_carries=7 -> 9 merges (up-sweep: 3, down-sweep: 1, tail: 5)
    }

    print("=" * 70)
    print("BK merge count validation")
    print("=" * 70)
    for w in range(min_width, max_width + 1):
        merges = bk_compute_merges(w - 1)
        actual = len(merges)
        expected = expected_merge_counts.get(w)
        if expected is not None:
            status = "OK" if actual == expected else "MISMATCH"
            if actual != expected:
                all_ok = False
        else:
            status = "N/A"
        print(
            f"  width {w:2d}: n_carries={w - 1:2d}, merges={actual:2d}  expected={expected}  [{status}]"
        )
    print()

    # QQ layer counts
    print("=" * 70)
    print("BK CLA QQ Toffoli gate counts")
    print("=" * 70)
    for w in range(min_width, max_width + 1):
        toff_gates = generate_bk_cla_qq_gates(w)
        ccx_count = sum(1 for g in toff_gates if g.gate_type == "CCX")
        cx_count = sum(1 for g in toff_gates if g.gate_type == "CX")
        x_count = sum(1 for g in toff_gates if g.gate_type == "X")
        merges = bk_compute_merges(w - 1)
        num_merges = len(merges)
        expected_layers = 7 * w - 4 + 4 * num_merges
        actual = len(toff_gates)
        status = "OK" if actual == expected_layers else "MISMATCH"
        if actual != expected_layers:
            all_ok = False
        clifft_count = ccx_count * 15 + cx_count + x_count
        clifft_gates = expand_to_clifford_t(toff_gates)
        clifft_status = "OK" if len(clifft_gates) == clifft_count else "MISMATCH"
        if len(clifft_gates) != clifft_count:
            all_ok = False
        print(
            f"  width {w:2d}: {x_count} X + {cx_count} CX + {ccx_count} CCX = {actual} Toffoli "
            f"(expected {expected_layers}) [{status}]  "
            f"-> {len(clifft_gates)} Clifford+T (expected {clifft_count}) [{clifft_status}]"
        )
    print()

    # Verify no CCX in Clifford+T output for all variants
    print("=" * 70)
    print("Gate purity validation (zero CCX in Clifford+T output)")
    print("=" * 70)
    variant_generators = [
        ("QQ", generate_bk_cla_qq_clifft),
        ("cQQ", generate_bk_cla_cqq_clifft),
        ("CQ_inc", generate_bk_cla_cq_inc_clifft),
        ("cCQ_inc", generate_bk_cla_ccq_inc_clifft),
    ]
    for variant_name, gen_func in variant_generators:
        for w in range(min_width, max_width + 1):
            gates = gen_func(w)
            # Check no gate has more than 1 control
            max_ctrl = max(g.num_controls for g in gates) if gates else 0
            # Check all gate types are valid Clifford+T
            valid_types = {"H", "T", "Tdg", "X", "CX"}
            bad_types = {g.gate_type for g in gates} - valid_types
            status = "OK" if max_ctrl <= 1 and not bad_types else "FAIL"
            if max_ctrl > 1 or bad_types:
                all_ok = False
            print(
                f"  {variant_name:8s} width {w:2d}: {len(gates):5d} gates, "
                f"max_ctrl={max_ctrl}, bad_types={bad_types or 'none'}  [{status}]"
            )
    print()

    # Layer count consistency for all variants
    print("=" * 70)
    print("Clifford+T layer counts by variant")
    print("=" * 70)
    for w in range(min_width, max_width + 1):
        qq = generate_bk_cla_qq_clifft(w)
        cqq = generate_bk_cla_cqq_clifft(w)
        cq = generate_bk_cla_cq_inc_clifft(w)
        ccq = generate_bk_cla_ccq_inc_clifft(w)
        print(
            f"  width {w:2d}: QQ={len(qq):5d}  cQQ={len(cqq):5d}  "
            f"CQ_inc={len(cq):5d}  cCQ_inc={len(ccq):5d}"
        )
    print()

    if all_ok:
        print("ALL VALIDATIONS PASSED")
    else:
        print("VALIDATION FAILED - see mismatches above")

    return all_ok


# ============================================================================
# CLI entry point
# ============================================================================


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate BK CLA Clifford+T hardcoded Toffoli addition sequence C files for widths 2-8."
        )
    )
    parser.add_argument(
        "--width",
        type=int,
        metavar="N",
        help="Generate only for width N (default: all 2-8)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing files",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory for C files (default: c_backend/src/sequences/)",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Cross-validate against expected layer and merge counts",
    )
    parser.add_argument(
        "--min-width",
        type=int,
        default=2,
        help="Minimum width to generate (default: 2, BK CLA needs >= 2)",
    )
    parser.add_argument(
        "--max-width",
        type=int,
        default=8,
        help="Maximum width to generate (default: 8)",
    )

    args = parser.parse_args()

    min_width = args.min_width
    max_width = args.max_width

    if args.validate:
        ok = validate(min_width, max_width)
        sys.exit(0 if ok else 1)

    # Determine output directory
    script_dir = os.path.dirname(os.path.abspath(__file__))

    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = os.path.normpath(
            os.path.join(script_dir, "..", "c_backend", "src", "sequences")
        )

    if args.width:
        # Single width mode
        if args.width < min_width or args.width > max_width:
            print(f"Error: width must be {min_width}-{max_width}", file=sys.stderr)
            sys.exit(1)
        w = args.width
        if args.dry_run:
            print(f"// === QQ width {w} ===")
            print(generate_qq_file(w))
            print(f"// === cQQ width {w} ===")
            print(generate_cqq_file(w))
            print(f"// === CQ_inc width {w} ===")
            print(generate_cq_inc_file(w))
            print(f"// === cCQ_inc width {w} ===")
            print(generate_ccq_inc_file(w))
        else:
            os.makedirs(output_dir, exist_ok=True)
            for gen_func, fname in [
                (generate_qq_file, f"toffoli_clifft_cla_qq_{w}.c"),
                (generate_cqq_file, f"toffoli_clifft_cla_cqq_{w}.c"),
                (generate_cq_inc_file, f"toffoli_clifft_cla_cq_inc_{w}.c"),
                (generate_ccq_inc_file, f"toffoli_clifft_cla_ccq_inc_{w}.c"),
            ]:
                content = gen_func(w)
                path = os.path.join(output_dir, fname)
                with open(path, "w") as f:
                    f.write(content)
                print(f"Written: {path}")
    else:
        # Full generation mode
        if args.dry_run:
            for w in range(min_width, max_width + 1):
                for gen_func, fname in [
                    (generate_qq_file, f"toffoli_clifft_cla_qq_{w}.c"),
                    (generate_cqq_file, f"toffoli_clifft_cla_cqq_{w}.c"),
                    (generate_cq_inc_file, f"toffoli_clifft_cla_cq_inc_{w}.c"),
                    (generate_ccq_inc_file, f"toffoli_clifft_cla_ccq_inc_{w}.c"),
                ]:
                    print(f"// === FILE: {fname} ===")
                    print(gen_func(w))
                    print()
            print("// === FILE: toffoli_clifft_cla_dispatch.c ===")
            print(generate_dispatch_file(min_width, max_width))
        else:
            os.makedirs(output_dir, exist_ok=True)
            file_count = 0

            for w in range(min_width, max_width + 1):
                for gen_func, fname in [
                    (generate_qq_file, f"toffoli_clifft_cla_qq_{w}.c"),
                    (generate_cqq_file, f"toffoli_clifft_cla_cqq_{w}.c"),
                    (generate_cq_inc_file, f"toffoli_clifft_cla_cq_inc_{w}.c"),
                    (generate_ccq_inc_file, f"toffoli_clifft_cla_ccq_inc_{w}.c"),
                ]:
                    content = gen_func(w)
                    path = os.path.join(output_dir, fname)
                    with open(path, "w") as f:
                        f.write(content)
                    print(f"Written: {path}")
                    file_count += 1

            # Write dispatch file
            dispatch_content = generate_dispatch_file(min_width, max_width)
            dispatch_path = os.path.join(output_dir, "toffoli_clifft_cla_dispatch.c")
            with open(dispatch_path, "w") as f:
                f.write(dispatch_content)
            print(f"Written: {dispatch_path}")
            file_count += 1

            print(f"\nTotal: {file_count} files written")

    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
