#!/usr/bin/env python3
"""Toffoli MCX-decomposed hardcoded sequence generation (widths 1-8).

This script generates per-width C source files (toffoli_decomp_seq_N.c) and a
unified dispatch file (toffoli_decomp_seq_dispatch.c) for MCX-decomposed
controlled quantum-quantum (cQQ) CDKM addition sequences.

Unlike generate_toffoli_seq.py which produces cQQ sequences with MCX(3 controls)
requiring dynamic allocation, this script decomposes every MCX(3) into 3 CCX
gates via the AND-ancilla pattern. The resulting sequences use only X/CX/CCX
(max 2 controls) and can be fully static const.

AND-ancilla MCX decomposition (Phase 74-03):
  MCX(target, [c1, c2, c3]) ->
    CCX(and_anc, c1, c2)     -- compute partial AND
    CCX(target, and_anc, c3)  -- apply via AND-ancilla
    CCX(and_anc, c1, c2)     -- uncompute AND

Gate encoding:
  - X:   .Gate=X, .Target=t, .NumControls=0, .Control={0}, .GateValue=1
  - CX:  .Gate=X, .Target=t, .NumControls=1, .Control={c}, .GateValue=1
  - CCX: .Gate=X, .Target=t, .NumControls=2, .Control={c1,c2}, .GateValue=1

Algorithm: CDKM ripple-carry adder (Cuccaro et al., 2004)
  Controlled variant with AND-ancilla MCX decomposition:
  - cMAJ(a,b,c,ext,and_anc) = CCX(b,c,ext), CCX(a,c,ext),
      CCX(and_anc,a,b), CCX(c,and_anc,ext), CCX(and_anc,a,b)
  - cUMA(a,b,c,ext,and_anc) =
      CCX(and_anc,a,b), CCX(c,and_anc,ext), CCX(and_anc,a,b),
      CCX(a,c,ext), CCX(b,a,ext)

Qubit layout for width N (N >= 2):
  [0..N-1]   = register a (target)
  [N..2N-1]  = register b (source)
  [2N]       = carry ancilla
  [2N+1]     = external control qubit
  [2N+2]     = AND-ancilla
  Total: 2N+3 qubits

Usage:
  python scripts/generate_toffoli_decomp_seq.py                  # Generate all files
  python scripts/generate_toffoli_decomp_seq.py --width 4        # Generate only width 4
  python scripts/generate_toffoli_decomp_seq.py --dry-run        # Print to stdout
  python scripts/generate_toffoli_decomp_seq.py --validate       # Validate layer counts

Generated by: scripts/generate_toffoli_decomp_seq.py
Phase 74, Plan 05: Hardcoded MCX-decomposed sequences
"""

import argparse
import os
import sys
from dataclasses import dataclass, field

# ============================================================================
# Gate dataclass for Clifford+T sequences
# ============================================================================


@dataclass
class CliffordTGate:
    """Gate in Clifford+T basis: H, T, Tdg, X (0 controls), CX (1 control)."""

    gate_type: str  # "H", "T", "Tdg", "X", "CX"
    target: int
    control: int = -1  # Only for CX

    def to_c_static(self) -> str:
        """Generate C static const initializer."""
        gate_enum = {
            "H": "H",
            "T": "T_GATE",
            "Tdg": "TDG_GATE",
            "X": "X",
            "CX": "X",  # CX is X with 1 control
        }[self.gate_type]

        gate_value = {
            "H": "0",
            "T": "M_PI / 4.0",
            "Tdg": "-M_PI / 4.0",
            "X": "1",
            "CX": "1",
        }[self.gate_type]

        num_controls = 1 if self.gate_type == "CX" else 0
        ctrl_init = f"{{{self.control}}}" if num_controls == 1 else "{0}"

        return (
            f"{{.Gate = {gate_enum},\n"
            f"                                      .Target = {self.target},\n"
            f"                                      .NumControls = {num_controls},\n"
            f"                                      .Control = {ctrl_init},\n"
            f"                                      .large_control = NULL,\n"
            f"                                      .GateValue = {gate_value},\n"
            f"                                      .NumBasisGates = 0}}"
        )


def ccx_to_clifford_t(target: int, ctrl1: int, ctrl2: int) -> list[CliffordTGate]:
    """Expand CCX(target, ctrl1, ctrl2) into 15 Clifford+T gates.

    Sequence matches gate.c:emit_ccx_clifford_t exactly.
    """
    return [
        CliffordTGate("H", target),
        CliffordTGate("CX", target, ctrl2),
        CliffordTGate("Tdg", target),
        CliffordTGate("CX", target, ctrl1),
        CliffordTGate("T", target),
        CliffordTGate("CX", target, ctrl2),
        CliffordTGate("Tdg", target),
        CliffordTGate("CX", target, ctrl1),
        CliffordTGate("T", target),
        CliffordTGate("T", ctrl2),
        CliffordTGate("H", target),
        CliffordTGate("CX", ctrl2, ctrl1),
        CliffordTGate("T", ctrl1),
        CliffordTGate("Tdg", ctrl2),
        CliffordTGate("CX", ctrl2, ctrl1),
    ]


def toffoli_to_clifford_t(gates: list["ToffoliGate"]) -> list[CliffordTGate]:
    """Convert a list of ToffoliGate (X/CX/CCX) to CliffordTGate (H/T/Tdg/X/CX).

    CX and X gates pass through. CCX gates expand to 15 Clifford+T gates.
    """
    result = []
    for gate in gates:
        if gate.num_controls == 0:
            result.append(CliffordTGate("X", gate.target))
        elif gate.num_controls == 1:
            result.append(CliffordTGate("CX", gate.target, gate.controls[0]))
        elif gate.num_controls == 2:
            result.extend(ccx_to_clifford_t(gate.target, gate.controls[0], gate.controls[1]))
        else:
            raise ValueError(
                f"Cannot convert gate with {gate.num_controls} controls to Clifford+T."
            )
    return result


# ============================================================================
# Gate dataclass for decomposed Toffoli sequences
# ============================================================================


@dataclass
class ToffoliGate:
    """Represents a single gate in a Toffoli sequence (max 2 controls)."""

    gate_type: str  # "X" (with controls: CX, CCX)
    target: int
    controls: list[int] = field(default_factory=list)

    @property
    def num_controls(self) -> int:
        return len(self.controls)

    def to_c_static(self) -> str:
        """Generate C static const initializer (only for gates with <= 2 controls)."""
        if self.num_controls > 2:
            raise ValueError(f"Cannot generate static const for {self.num_controls} controls")

        if self.num_controls == 0:
            return (
                f"{{.Gate = X,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 0,\n"
                f"                                      .Control = {{0}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = 1,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        elif self.num_controls == 1:
            return (
                f"{{.Gate = X,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 1,\n"
                f"                                      .Control = {{{self.controls[0]}}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = 1,\n"
                f"                                      .NumBasisGates = 0}}"
            )
        else:  # num_controls == 2
            return (
                f"{{.Gate = X,\n"
                f"                                      .Target = {self.target},\n"
                f"                                      .NumControls = 2,\n"
                f"                                      .Control = {{{self.controls[0]}, {self.controls[1]}}},\n"
                f"                                      .large_control = NULL,\n"
                f"                                      .GateValue = 1,\n"
                f"                                      .NumBasisGates = 0}}"
            )


# ============================================================================
# CDKM algorithm: decomposed controlled gate sequences
# ============================================================================


def generate_decomp_cqq_gates(bits: int) -> list[ToffoliGate]:
    """Generate MCX-decomposed controlled QQ CDKM adder gate sequence.

    Qubit layout:
      [0..bits-1]       = register a (target)
      [bits..2*bits-1]  = register b (source)
      [2*bits]          = ancilla carry (bits >= 2)
      [2*bits+1]        = external control qubit
      [2*bits+2]        = AND-ancilla (bits >= 2)

    Width 1: [0]=a, [1]=b, [2]=ext_control. Single CCX. No AND-ancilla needed.
    Width N >= 2: decomposed cMAJ/cUMA chain. Total qubits: 2N+3.
    """
    gates = []

    if bits == 1:
        # Single CCX: controlled a[0] ^= b[0]
        gates.append(ToffoliGate("X", target=0, controls=[1, 2]))
        return gates

    ancilla = 2 * bits
    ext_ctrl = 2 * bits + 1
    and_anc = 2 * bits + 2

    # Forward decomposed cMAJ sweep
    gates.extend(_cmaj_decomp(ancilla, bits + 0, 0, ext_ctrl, and_anc))
    for i in range(1, bits):
        gates.extend(_cmaj_decomp(i - 1, bits + i, i, ext_ctrl, and_anc))

    # Reverse decomposed cUMA sweep
    for i in range(bits - 1, 0, -1):
        gates.extend(_cuma_decomp(i - 1, bits + i, i, ext_ctrl, and_anc))
    gates.extend(_cuma_decomp(ancilla, bits + 0, 0, ext_ctrl, and_anc))

    return gates


def _cmaj_decomp(a: int, b: int, c: int, ext: int, and_anc: int) -> list[ToffoliGate]:
    """Decomposed cMAJ(a, b, c, ext, and_anc):

    Step 1: CCX(target=b, ctrl1=c, ctrl2=ext)
    Step 2: CCX(target=a, ctrl1=c, ctrl2=ext)
    Step 3a: CCX(target=and_anc, ctrl1=a, ctrl2=b)  -- compute AND
    Step 3b: CCX(target=c, ctrl1=and_anc, ctrl2=ext) -- apply
    Step 3c: CCX(target=and_anc, ctrl1=a, ctrl2=b)  -- uncompute AND
    """
    return [
        ToffoliGate("X", target=b, controls=[c, ext]),
        ToffoliGate("X", target=a, controls=[c, ext]),
        ToffoliGate("X", target=and_anc, controls=[a, b]),
        ToffoliGate("X", target=c, controls=[and_anc, ext]),
        ToffoliGate("X", target=and_anc, controls=[a, b]),
    ]


def _cuma_decomp(a: int, b: int, c: int, ext: int, and_anc: int) -> list[ToffoliGate]:
    """Decomposed cUMA(a, b, c, ext, and_anc):

    Step 1a: CCX(target=and_anc, ctrl1=a, ctrl2=b)  -- compute AND
    Step 1b: CCX(target=c, ctrl1=and_anc, ctrl2=ext) -- apply
    Step 1c: CCX(target=and_anc, ctrl1=a, ctrl2=b)  -- uncompute AND
    Step 2:  CCX(target=a, ctrl1=c, ctrl2=ext)
    Step 3:  CCX(target=b, ctrl1=a, ctrl2=ext)
    """
    return [
        ToffoliGate("X", target=and_anc, controls=[a, b]),
        ToffoliGate("X", target=c, controls=[and_anc, ext]),
        ToffoliGate("X", target=and_anc, controls=[a, b]),
        ToffoliGate("X", target=a, controls=[c, ext]),
        ToffoliGate("X", target=b, controls=[a, ext]),
    ]


def _gate_description(gate: ToffoliGate) -> str:
    """Human-readable gate description for comments."""
    if gate.num_controls == 0:
        return f"X(target={gate.target})"
    elif gate.num_controls == 1:
        return f"CX(target={gate.target}, ctrl={gate.controls[0]})"
    elif gate.num_controls == 2:
        return f"CCX(target={gate.target}, ctrl1={gate.controls[0]}, ctrl2={gate.controls[1]})"
    else:
        ctrls = ",".join(str(c) for c in gate.controls)
        return f"MCX(target={gate.target}, ctrls=[{ctrls}])"


# ============================================================================
# C code generation for Clifford+T cQQ (static const -- max 1 control!)
# ============================================================================


def generate_clifft_cqq_static_c(gates: list[CliffordTGate], width: int) -> str:
    """Generate static const C code for cQQ Clifford+T variant (all gates max 1 control)."""
    lines = []
    num_layers = len(gates)

    # Each gate is on its own layer
    for i, gate in enumerate(gates):
        gate_str = gate.to_c_static()
        lines.append(f"static const gate_t TOFFOLI_CLIFFT_CQQ_{width}_L{i}[] = {{{gate_str}}};")
        lines.append("")

    # Layer pointer array
    if num_layers > 6:
        chunks = [list(range(i, min(i + 6, num_layers))) for i in range(0, num_layers, 6)]
        chunk_lines = []
        for chunk in chunks:
            names = ", ".join(f"TOFFOLI_CLIFFT_CQQ_{width}_L{j}" for j in chunk)
            chunk_lines.append(f"    {names}")
        layers_str = ",\n".join(chunk_lines)
        lines.append(
            f"static const gate_t *TOFFOLI_CLIFFT_CQQ_{width}_LAYERS[] = {{\n{layers_str}}};"
        )
    else:
        names = ", ".join(f"TOFFOLI_CLIFFT_CQQ_{width}_L{i}" for i in range(num_layers))
        lines.append(f"static const gate_t *TOFFOLI_CLIFFT_CQQ_{width}_LAYERS[] = {{{names}}};")

    # Gates per layer array (all 1s)
    gpl_str = ", ".join("1" for _ in range(num_layers))
    lines.append(f"static const num_t TOFFOLI_CLIFFT_CQQ_{width}_GPL[] = {{{gpl_str}}};")
    lines.append("")

    # Sequence struct
    lines.append(
        f"static const sequence_t HARDCODED_TOFFOLI_CLIFFT_CQQ_{width} = "
        f"{{.seq = (gate_t **)TOFFOLI_CLIFFT_CQQ_{width}_LAYERS,"
    )
    lines.append(f"                                              .num_layer = {num_layers},")
    lines.append(f"                                              .used_layer = {num_layers},")
    lines.append(
        f"                                              .gates_per_layer = "
        f"(num_t *)TOFFOLI_CLIFFT_CQQ_{width}_GPL}};"
    )

    return "\n".join(lines)


def generate_clifft_cqq_width_file(width: int) -> str:
    """Generate complete C source file for cQQ Clifford+T at one width."""
    output = []

    # Header
    output.append("//")
    output.append(
        f"// toffoli_clifft_cqq_{width}.c - CDKM cQQ Clifford+T addition for {width}-bit width"
    )
    output.append("//")
    output.append(
        "// Generated by scripts/generate_toffoli_decomp_seq.py --clifford-t - DO NOT EDIT MANUALLY"
    )
    output.append("//")
    output.append("// Contains: Toffoli CDKM cQQ Clifford+T addition (static const, zero CCX/MCX)")
    output.append(
        "// Algorithm: CDKM ripple-carry adder with AND-ancilla MCX decomposition + CCX->Clifford+T"
    )
    output.append("// All gates: H/T/Tdg/CX/X (max 1 control) -- fully static const.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")
    output.append("#include <math.h>")
    output.append("")

    # Generate gate sequences
    cqq_gates = generate_decomp_cqq_gates(width)
    clifft_gates = toffoli_to_clifford_t(cqq_gates)

    if width == 1:
        cqq_num_qubits = 3
    else:
        cqq_num_qubits = 2 * width + 3
    output.append("// ============================================================================")
    output.append(f"// TOFFOLI CLIFFT cQQ_ADD WIDTH {width} ({len(clifft_gates)} layers)")
    if width == 1:
        output.append("// Qubit layout: [0] = target, [1] = source, [2] = ext_ctrl")
    else:
        output.append(
            f"// Qubit layout: [0,{width - 1}] = target (a), "
            f"[{width},{2 * width - 1}] = source (b), "
            f"[{2 * width}] = carry, [{2 * width + 1}] = ext_ctrl, [{2 * width + 2}] = and_anc"
        )
    output.append(f"// Total qubits: {cqq_num_qubits}")
    output.append("// All gates: H/T/Tdg/CX/X (max 1 control) -- zero CCX, zero MCX")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_clifft_cqq_static_c(clifft_gates, width))
    output.append("")

    # Dispatch helper
    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_clifft_cQQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_CLIFFT_CQQ_{width};")
    output.append("}")
    output.append("")

    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# C code generation for decomposed cQQ (static const -- no MCX!)
# ============================================================================


def generate_decomp_cqq_static_c(gates: list[ToffoliGate], width: int) -> str:
    """Generate static const C code for decomposed cQQ variant.

    Key advantage: all gates have <= 2 controls, so everything is static const.
    No dynamic allocation needed (unlike original cQQ with MCX).
    """
    lines = []
    num_layers = len(gates)

    # Each gate is on its own layer (1 gate per layer)
    for i, gate in enumerate(gates):
        gate_str = gate.to_c_static()
        lines.append(f"static const gate_t TOFFOLI_DECOMP_CQQ_{width}_L{i}[] = {{{gate_str}}};")
        lines.append("")

    # Layer pointer array
    if num_layers > 6:
        chunks = [list(range(i, min(i + 6, num_layers))) for i in range(0, num_layers, 6)]
        chunk_lines = []
        for chunk in chunks:
            names = ", ".join(f"TOFFOLI_DECOMP_CQQ_{width}_L{j}" for j in chunk)
            chunk_lines.append(f"    {names}")
        layers_str = ",\n".join(chunk_lines)
        lines.append(
            f"static const gate_t *TOFFOLI_DECOMP_CQQ_{width}_LAYERS[] = {{\n{layers_str}}};"
        )
    else:
        names = ", ".join(f"TOFFOLI_DECOMP_CQQ_{width}_L{i}" for i in range(num_layers))
        lines.append(f"static const gate_t *TOFFOLI_DECOMP_CQQ_{width}_LAYERS[] = {{{names}}};")

    # Gates per layer array (all 1s)
    gpl_str = ", ".join("1" for _ in range(num_layers))
    lines.append(f"static const num_t TOFFOLI_DECOMP_CQQ_{width}_GPL[] = {{{gpl_str}}};")
    lines.append("")

    # Sequence struct
    lines.append(
        f"static const sequence_t HARDCODED_TOFFOLI_DECOMP_CQQ_{width} = "
        f"{{.seq = (gate_t **)TOFFOLI_DECOMP_CQQ_{width}_LAYERS,"
    )
    lines.append(f"                                              .num_layer = {num_layers},")
    lines.append(f"                                              .used_layer = {num_layers},")
    lines.append(
        f"                                              .gates_per_layer = "
        f"(num_t *)TOFFOLI_DECOMP_CQQ_{width}_GPL}};"
    )

    return "\n".join(lines)


# ============================================================================
# Per-width file generation
# ============================================================================


def generate_width_file(width: int) -> str:
    """Generate complete C source file for one width."""
    output = []

    # Header
    output.append("//")
    output.append(
        f"// toffoli_decomp_seq_{width}.c - MCX-decomposed Toffoli cQQ addition for {width}-bit width"
    )
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_decomp_seq.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append("// Contains: Toffoli decomposed cQQ_add (static const, zero MCX)")
    output.append("// Algorithm: CDKM ripple-carry adder with AND-ancilla MCX decomposition")
    output.append("// All gates are X/CX/CCX (max 2 controls) -- no dynamic allocation needed.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    # Generate gate sequence
    cqq_gates = generate_decomp_cqq_gates(width)

    # Verify no gate has more than 2 controls
    for i, gate in enumerate(cqq_gates):
        if gate.num_controls > 2:
            raise ValueError(
                f"Width {width}: gate {i} has {gate.num_controls} controls "
                f"(expected max 2). Decomposition bug!"
            )

    # cQQ decomposed section (static const!)
    if width == 1:
        cqq_num_qubits = 3
    else:
        cqq_num_qubits = 2 * width + 3
    output.append("// ============================================================================")
    output.append(f"// TOFFOLI DECOMPOSED cQQ_ADD WIDTH {width} ({len(cqq_gates)} layers)")
    if width == 1:
        output.append("// Qubit layout: [0] = target, [1] = source, [2] = ext_ctrl")
    else:
        output.append(
            f"// Qubit layout: [0,{width - 1}] = target (a), "
            f"[{width},{2 * width - 1}] = source (b), "
            f"[{2 * width}] = carry, [{2 * width + 1}] = ext_ctrl, [{2 * width + 2}] = and_anc"
        )
    output.append(f"// Total qubits: {cqq_num_qubits}")
    output.append("// All gates: CCX (max 2 controls) -- zero MCX, zero dynamic allocation")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_decomp_cqq_static_c(cqq_gates, width))
    output.append("")

    # Dispatch helper
    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_decomp_cQQ_add_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_DECOMP_CQQ_{width};")
    output.append("}")
    output.append("")

    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Dispatch file generation
# ============================================================================


def generate_dispatch_file(max_width: int = 8) -> str:
    """Generate toffoli_decomp_seq_dispatch.c with unified dispatch function."""
    output = []

    output.append("//")
    output.append(
        "// toffoli_decomp_seq_dispatch.c - Dispatch for MCX-decomposed Toffoli cQQ sequences"
    )
    output.append("//")
    output.append("// Generated by scripts/generate_toffoli_decomp_seq.py - DO NOT EDIT MANUALLY")
    output.append("//")
    output.append(
        "// Routes get_hardcoded_toffoli_decomp_cQQ_add(bits) to per-width implementations."
    )
    output.append(
        "// Each per-width file is conditionally compiled via #ifdef TOFFOLI_SEQ_WIDTH_N."
    )
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("#include <stddef.h>")
    output.append("")

    # Forward declarations
    output.append("// ============================================================================")
    output.append("// FORWARD DECLARATIONS (conditionally compiled per width)")
    output.append("// ============================================================================")
    output.append("")

    for w in range(1, max_width + 1):
        output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
        output.append(f"const sequence_t *get_hardcoded_toffoli_decomp_cQQ_add_{w}(int bits);")
        output.append("#endif")
        output.append("")

    # Dispatch function
    output.append("// ============================================================================")
    output.append("// UNIFIED TOFFOLI DECOMPOSED cQQ_add DISPATCH")
    output.append("// ============================================================================")
    output.append("")
    output.append("const sequence_t *get_hardcoded_toffoli_decomp_cQQ_add(int bits) {")
    output.append("    switch (bits) {")
    for w in range(1, max_width + 1):
        output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
        output.append(f"    case {w}:")
        output.append(f"        return get_hardcoded_toffoli_decomp_cQQ_add_{w}(bits);")
        output.append("#endif")
    output.append("    default:")
    output.append("        return NULL;")
    output.append("    }")
    output.append("}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Validation
# ============================================================================


def validate_clifford_t(max_width: int = 8) -> bool:
    """Validate Clifford+T cQQ generated gate sequences against expected counts."""
    all_ok = True

    # Expected Clifford+T cQQ layer counts:
    # Width 1: 1 CCX -> 15 Clifford+T gates
    # Width N >= 2: 10*N CCX -> 150*N Clifford+T gates
    print("=" * 60)
    print("Clifford+T cQQ_add layer count validation")
    print("=" * 60)
    for w in range(1, max_width + 1):
        cqq_gates = generate_decomp_cqq_gates(w)
        clifft_gates = toffoli_to_clifford_t(cqq_gates)
        actual = len(clifft_gates)
        # Count by type in source
        cx_count = sum(1 for g in cqq_gates if g.num_controls <= 1)
        ccx_count = sum(1 for g in cqq_gates if g.num_controls == 2)
        x_count = sum(1 for g in cqq_gates if g.num_controls == 0)
        expected = x_count + cx_count + ccx_count * 15  # X->1, CX->1, CCX->15
        # For width 1: 1 CCX -> 15
        # For width N >= 2: all are CCX, so 10*N * 15 = 150*N
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(f"  width {w:2d}: {actual:4d} layers  expected {expected:4d}  [{status}]")

    print()

    # Verify all Clifford+T gates have max 1 control
    print("=" * 60)
    print("Clifford+T cQQ gate control count validation (must be <= 1)")
    print("=" * 60)
    for w in range(1, max_width + 1):
        cqq_gates = generate_decomp_cqq_gates(w)
        clifft_gates = toffoli_to_clifford_t(cqq_gates)
        max_ctrl = 0
        for g in clifft_gates:
            ctrl = 1 if g.gate_type == "CX" else 0
            max_ctrl = max(max_ctrl, ctrl)
        status = "OK" if max_ctrl <= 1 else "FAIL"
        if max_ctrl > 1:
            all_ok = False
        print(f"  width {w:2d}: max controls = {max_ctrl}  [{status}]")

    print()

    # Verify gate type distribution
    print("=" * 60)
    print("Clifford+T cQQ gate type distribution")
    print("=" * 60)
    for w in range(1, max_width + 1):
        cqq_gates = generate_decomp_cqq_gates(w)
        clifft_gates = toffoli_to_clifford_t(cqq_gates)
        counts = {"H": 0, "T": 0, "Tdg": 0, "X": 0, "CX": 0}
        for g in clifft_gates:
            counts[g.gate_type] += 1
        parts = ", ".join(f"{k}={v}" for k, v in counts.items() if v > 0)
        print(f"  width {w:2d}: {parts}, total={len(clifft_gates)}")

    print()

    if all_ok:
        print("ALL CLIFFORD+T cQQ VALIDATIONS PASSED")
    else:
        print("CLIFFORD+T cQQ VALIDATION FAILED - see mismatches above")

    return all_ok


def validate(max_width: int = 8) -> bool:
    """Validate generated gate sequences against expected counts."""
    all_ok = True

    # Expected decomposed cQQ layer counts:
    # Width 1: 1 gate (single CCX, no decomposition needed)
    # Width N >= 2: 10*N gates (N decomposed cMAJ + N decomposed cUMA, each 5 gates)
    print("=" * 60)
    print("Decomposed cQQ_add layer count validation")
    print("=" * 60)
    for w in range(1, max_width + 1):
        gates = generate_decomp_cqq_gates(w)
        actual = len(gates)
        expected = 1 if w == 1 else 10 * w
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(f"  width {w:2d}: {actual:4d} layers  expected {expected:4d}  [{status}]")

    print()

    # Verify all gates have <= 2 controls (no MCX)
    print("=" * 60)
    print("Gate control count validation (must be <= 2, zero MCX)")
    print("=" * 60)
    for w in range(1, max_width + 1):
        gates = generate_decomp_cqq_gates(w)
        max_ctrl = max(g.num_controls for g in gates)
        mcx_count = sum(1 for g in gates if g.num_controls > 2)
        status = "OK" if max_ctrl <= 2 and mcx_count == 0 else "FAIL"
        if max_ctrl > 2 or mcx_count > 0:
            all_ok = False
        print(f"  width {w:2d}: max controls = {max_ctrl}, MCX count = {mcx_count}  [{status}]")

    print()

    # Verify gate type distribution (CCX count)
    print("=" * 60)
    print("Gate type distribution")
    print("=" * 60)
    for w in range(1, max_width + 1):
        gates = generate_decomp_cqq_gates(w)
        cx_count = sum(1 for g in gates if g.num_controls == 1)
        ccx_count = sum(1 for g in gates if g.num_controls == 2)
        x_count = sum(1 for g in gates if g.num_controls == 0)
        print(f"  width {w:2d}: X={x_count}, CX={cx_count}, CCX={ccx_count}, total={len(gates)}")

    print()

    # Verify width 2 sequence matches expected decomposed cMAJ/cUMA pattern
    print("=" * 60)
    print("Width 2 decomposed cQQ gate sequence verification")
    print("=" * 60)
    gates = generate_decomp_cqq_gates(2)
    # Width 2: ancilla=4, ext_ctrl=5, and_anc=6
    # cMAJ(4, 2, 0, 5, 6) + cMAJ(0, 3, 1, 5, 6) + cUMA(0, 3, 1, 5, 6) + cUMA(4, 2, 0, 5, 6)
    expected = [
        # cMAJ(4, 2, 0, 5, 6)
        (2, [0, 5]),  # CCX(b=2, c=0, ext=5)
        (4, [0, 5]),  # CCX(a=4, c=0, ext=5)
        (6, [4, 2]),  # CCX(and_anc=6, a=4, b=2)
        (0, [6, 5]),  # CCX(c=0, and_anc=6, ext=5)
        (6, [4, 2]),  # CCX(and_anc=6, a=4, b=2)
        # cMAJ(0, 3, 1, 5, 6)
        (3, [1, 5]),  # CCX(b=3, c=1, ext=5)
        (0, [1, 5]),  # CCX(a=0, c=1, ext=5)
        (6, [0, 3]),  # CCX(and_anc=6, a=0, b=3)
        (1, [6, 5]),  # CCX(c=1, and_anc=6, ext=5)
        (6, [0, 3]),  # CCX(and_anc=6, a=0, b=3)
        # cUMA(0, 3, 1, 5, 6)
        (6, [0, 3]),  # CCX(and_anc=6, a=0, b=3)
        (1, [6, 5]),  # CCX(c=1, and_anc=6, ext=5)
        (6, [0, 3]),  # CCX(and_anc=6, a=0, b=3)
        (0, [1, 5]),  # CCX(a=0, c=1, ext=5)
        (3, [0, 5]),  # CCX(b=3, a=0, ext=5)
        # cUMA(4, 2, 0, 5, 6)
        (6, [4, 2]),  # CCX(and_anc=6, a=4, b=2)
        (0, [6, 5]),  # CCX(c=0, and_anc=6, ext=5)
        (6, [4, 2]),  # CCX(and_anc=6, a=4, b=2)
        (4, [0, 5]),  # CCX(a=4, c=0, ext=5)
        (2, [4, 5]),  # CCX(b=2, a=4, ext=5)
    ]

    all_match = True
    for i, (exp_target, exp_ctrls) in enumerate(expected):
        if i >= len(gates):
            all_match = False
            print(f"  Layer {i}: MISSING")
            continue
        gate = gates[i]
        match = gate.target == exp_target and gate.controls == exp_ctrls
        if not match:
            all_match = False
            print(
                f"  Layer {i}: MISMATCH - got ({gate.target}, {gate.controls}), "
                f"expected ({exp_target}, {exp_ctrls})"
            )

    if all_match:
        print(f"  All {len(expected)} gates match expected decomposed pattern")
    else:
        all_ok = False

    print()
    if all_ok:
        print("ALL VALIDATIONS PASSED")
    else:
        print("VALIDATION FAILED - see mismatches above")

    return all_ok


# ============================================================================
# CLI entry point
# ============================================================================


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate MCX-decomposed hardcoded Toffoli cQQ addition "
            "sequence C files for widths 1-8."
        )
    )
    parser.add_argument(
        "--width",
        type=int,
        metavar="N",
        help="Generate only for width N (default: all 1-8)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing files",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory for C files (default: c_backend/src/sequences/)",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Cross-validate against expected layer counts",
    )
    parser.add_argument(
        "--max-width",
        type=int,
        default=8,
        help="Maximum width to generate (default: 8)",
    )
    parser.add_argument(
        "--clifford-t",
        action="store_true",
        help="Generate Clifford+T decomposed cQQ sequences (CCX expanded to 15 H/T/Tdg/CX gates)",
    )

    args = parser.parse_args()

    if args.validate and args.clifford_t:
        ok = validate_clifford_t(args.max_width)
        sys.exit(0 if ok else 1)

    if args.validate:
        ok = validate(args.max_width)
        sys.exit(0 if ok else 1)

    # Determine output directory
    script_dir = os.path.dirname(os.path.abspath(__file__))

    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = os.path.normpath(
            os.path.join(script_dir, "..", "c_backend", "src", "sequences")
        )

    max_width = args.max_width

    if args.clifford_t:
        # Clifford+T cQQ generation mode
        if args.width:
            if args.width < 1 or args.width > max_width:
                print(f"Error: width must be 1-{max_width}", file=sys.stderr)
                sys.exit(1)
            content = generate_clifft_cqq_width_file(args.width)
            if args.dry_run:
                print(content)
            else:
                os.makedirs(output_dir, exist_ok=True)
                path = os.path.join(output_dir, f"toffoli_clifft_cqq_{args.width}.c")
                with open(path, "w") as f:
                    f.write(content)
                print(f"Written: {path}")
        else:
            # Full Clifford+T cQQ generation
            if args.dry_run:
                for w in range(1, max_width + 1):
                    print(f"// === FILE: toffoli_clifft_cqq_{w}.c ===")
                    print(generate_clifft_cqq_width_file(w))
                    print()
            else:
                os.makedirs(output_dir, exist_ok=True)
                for w in range(1, max_width + 1):
                    content = generate_clifft_cqq_width_file(w)
                    path = os.path.join(output_dir, f"toffoli_clifft_cqq_{w}.c")
                    with open(path, "w") as f:
                        f.write(content)
                    print(f"Written: {path}")
    elif args.width:
        # Single width mode
        if args.width < 1 or args.width > max_width:
            print(f"Error: width must be 1-{max_width}", file=sys.stderr)
            sys.exit(1)
        content = generate_width_file(args.width)
        if args.dry_run:
            print(content)
        else:
            os.makedirs(output_dir, exist_ok=True)
            path = os.path.join(output_dir, f"toffoli_decomp_seq_{args.width}.c")
            with open(path, "w") as f:
                f.write(content)
            print(f"Written: {path}")
    else:
        # Full generation mode
        if args.dry_run:
            for w in range(1, max_width + 1):
                print(f"// === FILE: toffoli_decomp_seq_{w}.c ===")
                print(generate_width_file(w))
                print()
            print("// === FILE: toffoli_decomp_seq_dispatch.c ===")
            print(generate_dispatch_file(max_width))
        else:
            # Write per-width files
            os.makedirs(output_dir, exist_ok=True)
            for w in range(1, max_width + 1):
                content = generate_width_file(w)
                path = os.path.join(output_dir, f"toffoli_decomp_seq_{w}.c")
                with open(path, "w") as f:
                    f.write(content)
                print(f"Written: {path}")

            # Write dispatch file
            dispatch_content = generate_dispatch_file(max_width)
            dispatch_path = os.path.join(output_dir, "toffoli_decomp_seq_dispatch.c")
            with open(dispatch_path, "w") as f:
                f.write(dispatch_content)
            print(f"Written: {dispatch_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
