#!/usr/bin/env python3
"""Record baseline code coverage and identify critical untested paths.

Parses the coverage JSON report (generated by pytest --cov --cov-report=json)
and records a structured baseline for future comparison across v4.1 phases.

Usage:
    python scripts/record_baseline.py

Prerequisites:
    Run coverage first:
        QUANTUM_COVERAGE=1 python3 setup.py build_ext --inplace --force
        pytest tests/python -v --cov=quantum_language \
            --cov-report=json:reports/coverage/coverage.json
"""

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

# Paths
COVERAGE_JSON = Path("reports/coverage/coverage.json")
BASELINE_JSON = Path("reports/coverage/baseline.json")


def get_git_metadata() -> dict:
    """Get current git commit hash, branch, and timestamp."""
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        commit = "unknown"

    try:
        branch = subprocess.check_output(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        branch = "unknown"

    timestamp = datetime.now(UTC).isoformat()

    return {"commit": commit, "branch": branch, "timestamp": timestamp}


def parse_coverage(coverage_path: Path) -> dict:
    """Parse pytest-cov JSON report and extract per-file metrics."""
    with open(coverage_path) as f:
        data = json.load(f)

    totals = data.get("totals", {})
    files = data.get("files", {})

    overall_percent = totals.get("percent_covered", 0.0)
    total_covered = totals.get("covered_lines", 0)
    total_missing = totals.get("missing_lines", 0)
    total_lines = total_covered + total_missing

    modules = {}
    for filepath, file_data in files.items():
        summary = file_data.get("summary", {})
        covered = summary.get("covered_lines", 0)
        missing = summary.get("missing_lines", 0)
        total = covered + missing
        percent = summary.get("percent_covered", 0.0)

        modules[filepath] = {
            "percent": round(percent, 1),
            "covered_lines": covered,
            "missing_lines": missing,
            "total_lines": total,
        }

    return {
        "overall_percent": round(overall_percent, 1),
        "total_lines": total_lines,
        "covered_lines": total_covered,
        "missing_lines": total_missing,
        "modules": modules,
    }


def identify_gaps(modules: dict) -> tuple[list, list]:
    """Identify critical untested and partially tested files.

    Critical untested: coverage < 50%
    Partially tested: coverage between 50-80%

    Returns:
        (critical_untested, partially_tested) sorted by missing_lines desc
    """
    critical = []
    partial = []

    for filepath, data in modules.items():
        percent = data["percent"]
        missing = data["missing_lines"]

        if percent < 50.0:
            critical.append({"file": filepath, "percent": percent, "missing_lines": missing})
        elif percent < 80.0:
            partial.append({"file": filepath, "percent": percent, "missing_lines": missing})

    # Sort by missing lines (most missing first)
    critical.sort(key=lambda x: x["missing_lines"], reverse=True)
    partial.sort(key=lambda x: x["missing_lines"], reverse=True)

    return critical, partial


def print_summary(baseline: dict) -> None:
    """Print a human-readable summary to stdout."""
    print()
    print("=" * 60)
    print("  Baseline Coverage Report")
    print("=" * 60)
    print()
    print(f"  Overall coverage: {baseline['overall_percent']:.1f}%")
    print(f"  Total lines:      {baseline['total_lines']}")
    print(f"  Covered lines:    {baseline['covered_lines']}")
    print(f"  Missing lines:    {baseline['missing_lines']}")
    print(f"  Commit:           {baseline['commit'][:12]}")
    print(f"  Branch:           {baseline['branch']}")
    print(f"  Timestamp:        {baseline['timestamp']}")
    print()

    critical = baseline.get("critical_untested", [])
    partial = baseline.get("partially_tested", [])

    print(f"  Critical untested files (< 50%): {len(critical)}")
    print(f"  Partially tested files (50-80%): {len(partial)}")
    print()

    # Top 5 files by missing lines
    all_gaps = critical + partial
    all_gaps.sort(key=lambda x: x["missing_lines"], reverse=True)
    top5 = all_gaps[:5]

    if top5:
        print("  Top 5 files by missing lines:")
        for entry in top5:
            print(
                f"    {entry['file']}: {entry['percent']:.1f}% "
                f"({entry['missing_lines']} lines missing)"
            )
        print()

    print(f"  Baseline recorded at {BASELINE_JSON}")
    print()


def main() -> int:
    """Main entry point."""
    # Check that coverage.json exists
    if not COVERAGE_JSON.exists():
        print(f"ERROR: {COVERAGE_JSON} not found.", file=sys.stderr)
        print(
            "Run coverage first:",
            file=sys.stderr,
        )
        print(
            "  QUANTUM_COVERAGE=1 python3 setup.py build_ext --inplace --force",
            file=sys.stderr,
        )
        print(
            "  pytest tests/python -v --cov=quantum_language "
            "--cov-report=json:reports/coverage/coverage.json",
            file=sys.stderr,
        )
        return 1

    # Create output directory if needed
    BASELINE_JSON.parent.mkdir(parents=True, exist_ok=True)

    # Warn if overwriting
    if BASELINE_JSON.exists():
        print(f"WARNING: Overwriting existing baseline at {BASELINE_JSON}")

    # Get git metadata
    git_meta = get_git_metadata()

    # Parse coverage data
    coverage_data = parse_coverage(COVERAGE_JSON)

    # Identify gaps
    critical, partial = identify_gaps(coverage_data["modules"])

    # Build baseline record
    baseline = {
        "timestamp": git_meta["timestamp"],
        "commit": git_meta["commit"],
        "branch": git_meta["branch"],
        "overall_percent": coverage_data["overall_percent"],
        "total_lines": coverage_data["total_lines"],
        "covered_lines": coverage_data["covered_lines"],
        "missing_lines": coverage_data["missing_lines"],
        "modules": coverage_data["modules"],
        "critical_untested": critical,
        "partially_tested": partial,
    }

    # Write baseline
    with open(BASELINE_JSON, "w") as f:
        json.dump(baseline, f, indent=2)
        f.write("\n")

    # Print summary
    print_summary(baseline)

    return 0


if __name__ == "__main__":
    sys.exit(main())
